// Community & political cards: political worker, elected representative, NGO, samaj / samiti, temple trust, club, union, housing society.
// See types.ts for the rules (no numbers, no claims; true of any decent organisation of the kind).
import type { TradeData } from "./types";

export const COMMUNITY: Record<string, TradeData> = {
  political: {
    explain: [
      "who you are — your post, your party and the area you work in",
      "the issues you work on (water, roads, youth, women, jobs) and the people you stand with",
      "how people can reach you for help and how they can join the work",
      "public meetings, janta darbar and where to find you",
    ],
    services: [
      { en: "Janta darbar", hi: "जनता दरबार", desc: "Meet people, hear their problems and take them up.", descHi: "लोगों से मिलना, उनकी समस्या सुनना और आगे उठाना।" },
      { en: "Help with government schemes", hi: "सरकारी योजनाओं में मदद", desc: "Forms and follow-up for pension, ration card, housing and scholarships.", descHi: "पेंशन, राशन कार्ड, आवास और छात्रवृत्ति के फ़ॉर्म और फ़ॉलो-अप।" },
      { en: "Local issues", hi: "इलाक़े की समस्याएँ", desc: "Roads, water, drains and streetlights taken to the right department.", descHi: "सड़क, पानी, नाली और स्ट्रीटलाइट की बात सही विभाग तक।" },
      { en: "Hospital & emergency help", hi: "अस्पताल और आपात मदद", desc: "Help reaching the right hospital or office when it is urgent.", descHi: "ज़रूरत पड़ने पर सही अस्पताल या दफ़्तर तक पहुँचने में मदद।" },
      { en: "Youth & women programmes", hi: "युवा और महिला कार्यक्रम", desc: "Camps, sports, training and gatherings in the area.", descHi: "इलाक़े में कैम्प, खेल, ट्रेनिंग और सभाएँ।" },
      { en: "Join the karyakarta team", hi: "कार्यकर्ता बनें", desc: "Become a booth-level member and work for your own area.", descHi: "बूथ स्तर के सदस्य बनें और अपने इलाक़े के लिए काम करें।" },
      { en: "Area visits & meetings", hi: "क्षेत्र भ्रमण और बैठकें", desc: "Regular visits to wards, villages and colonies.", descHi: "वार्ड, गाँव और कॉलोनियों में नियमित दौरे।" },
    ],
    whyUs: [
      { en: "Reachable on phone", hi: "फ़ोन पर सीधे उपलब्ध" },
      { en: "From your own area", hi: "आपके ही इलाक़े से" },
      { en: "Problems heard in person", hi: "समस्या आमने-सामने सुनते हैं" },
      { en: "Follow-up till it is done", hi: "काम होने तक फ़ॉलो-अप" },
      { en: "Work for every community", hi: "हर समाज के लिए काम" },
      { en: "Clean, open working", hi: "साफ़, खुला काम" },
      { en: "Message on WhatsApp", hi: "WhatsApp पर मैसेज" },
    ],
    steps: [
      { en: "Message or call", hi: "मैसेज या फ़ोन करें", desc: "Tell us your area and the problem, in short.", descHi: "अपना इलाक़ा और समस्या छोटे में बताएँ।" },
      { en: "We note it down", hi: "हम दर्ज करते हैं", desc: "Your issue is noted and taken to the right office or person.", descHi: "आपकी बात दर्ज होती है और सही दफ़्तर या व्यक्ति तक जाती है।" },
      { en: "Follow-up", hi: "फ़ॉलो-अप", desc: "We stay in touch till there is a result.", descHi: "नतीजा आने तक हम संपर्क में रहते हैं।" },
      { en: "Join the work", hi: "काम से जुड़ें", desc: "Come to meetings, drives and rallies in your area.", descHi: "अपने इलाक़े की बैठकों, अभियानों और रैलियों में आएँ।" },
    ],
    faq: [
      { q: "How do I reach you with a problem?", qHi: "समस्या के लिए आपसे कैसे संपर्क करें?", a: "Message on WhatsApp with your name, area and the issue; call for anything urgent.", aHi: "WhatsApp पर नाम, इलाक़ा और समस्या भेजें; बहुत ज़रूरी हो तो फ़ोन करें।" },
      { q: "Which area do you work in?", qHi: "आप किस क्षेत्र में काम करते हैं?", a: "See the area on this page; for a nearby area message us and we will guide you.", aHi: "इसी पेज पर क्षेत्र देखें; आस-पास के इलाक़े के लिए मैसेज करें, हम रास्ता बताएँगे।" },
      { q: "Can you help with a ration card or pension?", qHi: "राशन कार्ड या पेंशन में मदद मिलेगी?", a: "Yes, we help with the forms and follow-up at the office; bring your documents.", aHi: "हाँ, फ़ॉर्म और दफ़्तर में फ़ॉलो-अप में मदद करते हैं; अपने दस्तावेज़ साथ लाएँ।" },
      { q: "How can I join as a karyakarta?", qHi: "कार्यकर्ता कैसे बनें?", a: "Message us your name and ward; we add you to the local team and tell you about the next meeting.", aHi: "अपना नाम और वार्ड भेजें; हम आपको लोकल टीम में जोड़ेंगे और अगली बैठक बताएँगे।" },
      { q: "When is the janta darbar?", qHi: "जनता दरबार कब होता है?", a: "Message us for the next date and place; it is also announced on WhatsApp.", aHi: "अगली तारीख़ और जगह के लिए मैसेज करें; WhatsApp पर भी सूचना दी जाती है।" },
      { q: "Do you charge for any help?", qHi: "क्या मदद के लिए कोई शुल्क है?", a: "No. Public work is free; never pay anyone who claims to work on our behalf.", aHi: "नहीं। जनता का काम मुफ़्त है; हमारे नाम पर कोई पैसे माँगे तो न दें।" },
      { q: "Can you come to our colony or village?", qHi: "क्या आप हमारी कॉलोनी या गाँव आ सकते हैं?", a: "Yes, message the place and the issue; visits are planned area by area.", aHi: "हाँ, जगह और मुद्दा भेजें; दौरे इलाक़े के हिसाब से तय होते हैं।" },
    ],
    generic: ["connect with us", "explore options", "public service", "for the people", "development", "serving the nation"],
  },

  mla: {
    explain: [
      "the post and the constituency, ward or panchayat you represent",
      "work done and in progress for the area (roads, water, schools, health) in plain words",
      "how people can reach the office — janta darbar, helpline, WhatsApp",
      "help with schemes, certificates and recommendation letters",
    ],
    services: [
      { en: "Office & janta darbar", hi: "कार्यालय और जनता दरबार", desc: "Meet at the office or janta darbar for any public matter.", descHi: "किसी भी जनहित के काम के लिए कार्यालय या जनता दरबार में मिलें।" },
      { en: "Development works", hi: "विकास कार्य", desc: "Roads, water, drains, lights and schools in the area.", descHi: "क्षेत्र में सड़क, पानी, नाली, लाइट और स्कूल के काम।" },
      { en: "Government schemes", hi: "सरकारी योजनाएँ", desc: "Help applying for housing, pension, scholarship and other schemes.", descHi: "आवास, पेंशन, छात्रवृत्ति और दूसरी योजनाओं के आवेदन में मदद।" },
      { en: "Recommendation letters", hi: "अनुशंसा पत्र", desc: "Letters for hospital, education and official work, as rules allow.", descHi: "अस्पताल, पढ़ाई और सरकारी काम के लिए पत्र, नियमों के अनुसार।" },
      { en: "Grievance follow-up", hi: "शिकायत पर फ़ॉलो-अप", desc: "Complaints sent to the department and followed till resolved.", descHi: "शिकायत विभाग तक भेजी जाती है और हल होने तक फ़ॉलो-अप।" },
      { en: "Local works from area funds", hi: "क्षेत्र निधि से काम", desc: "Community halls, hand pumps, paths and lights proposed for the area.", descHi: "सामुदायिक भवन, हैंडपंप, रास्ते और लाइट के प्रस्ताव।" },
      { en: "Emergency help", hi: "आपात मदद", desc: "Hospital admission, ambulance or relief in an emergency — call the office.", descHi: "आपात स्थिति में अस्पताल, एम्बुलेंस या राहत — कार्यालय को फ़ोन करें।" },
    ],
    whyUs: [
      { en: "Office open to everyone", hi: "कार्यालय सबके लिए खुला" },
      { en: "Your representative, your area", hi: "आपका प्रतिनिधि, आपका क्षेत्र" },
      { en: "Complaints followed to the end", hi: "शिकायत पर अंत तक काम" },
      { en: "Regular area visits", hi: "नियमित क्षेत्र दौरा" },
      { en: "Work shown openly", hi: "काम सबके सामने" },
      { en: "Help in emergencies", hi: "आपात स्थिति में मदद" },
      { en: "Reach us on WhatsApp", hi: "WhatsApp पर संपर्क" },
    ],
    steps: [
      { en: "Send your matter", hi: "अपनी बात भेजें", desc: "Your name, village or ward, and what the problem is.", descHi: "अपना नाम, गाँव या वार्ड, और समस्या क्या है।" },
      { en: "Office registers it", hi: "कार्यालय दर्ज करता है", desc: "Your matter is noted and sent to the concerned department.", descHi: "आपकी बात दर्ज होकर संबंधित विभाग को भेजी जाती है।" },
      { en: "Follow-up", hi: "फ़ॉलो-अप", desc: "The office keeps track and tells you the progress.", descHi: "कार्यालय नज़र रखता है और आपको प्रगति बताता है।" },
      { en: "Meet if needed", hi: "ज़रूरत हो तो मिलें", desc: "Come to the janta darbar or office with your papers.", descHi: "अपने काग़ज़ लेकर जनता दरबार या कार्यालय आएँ।" },
    ],
    faq: [
      { q: "How do I contact the office?", qHi: "कार्यालय से कैसे संपर्क करें?", a: "Message on WhatsApp or come to the office in working hours; the address is on this page.", aHi: "WhatsApp पर मैसेज करें या काम के समय कार्यालय आएँ; पता इसी पेज पर है।" },
      { q: "Can I get a recommendation letter?", qHi: "क्या अनुशंसा पत्र मिल सकता है?", a: "For hospital, school or official work, bring your papers to the office; letters are given as rules allow.", aHi: "अस्पताल, स्कूल या सरकारी काम के लिए काग़ज़ लेकर कार्यालय आएँ; पत्र नियमों के अनुसार दिया जाता है।" },
      { q: "Can you help with a road, water or light problem?", qHi: "सड़क, पानी या बिजली की समस्या में मदद?", a: "Yes, send the location and a photo on WhatsApp; it is taken up with the department.", aHi: "हाँ, WhatsApp पर लोकेशन और फ़ोटो भेजें; विभाग से बात की जाती है।" },
      { q: "Which area does this cover?", qHi: "यह किस क्षेत्र के लिए है?", a: "The constituency or ward named on this page; for others we guide you to the right representative.", aHi: "इसी पेज पर लिखा क्षेत्र या वार्ड; दूसरे इलाक़े के लिए सही प्रतिनिधि तक पहुँचाते हैं।" },
      { q: "What are the office timings?", qHi: "कार्यालय का समय क्या है?", a: "See the timings on this page, or message before coming so someone is there.", aHi: "इसी पेज पर समय देखें, या आने से पहले मैसेज कर लें।" },
      { q: "Is there a fee for any work?", qHi: "क्या किसी काम का शुल्क है?", a: "No. Public service is free; do not pay anyone who asks for money in our name.", aHi: "नहीं। जनसेवा मुफ़्त है; हमारे नाम पर कोई पैसे माँगे तो न दें।" },
      { q: "How do I know what work has been done?", qHi: "कौन से काम हुए हैं, कैसे पता चलेगा?", a: "Updates are shared on this page and on WhatsApp; ask the office about your area.", aHi: "इसी पेज और WhatsApp पर अपडेट दिए जाते हैं; अपने इलाक़े के बारे में कार्यालय से पूछें।" },
    ],
    generic: ["connect with us", "explore options", "public service", "development", "for the people", "committed to progress"],
  },

  ngo: {
    explain: [
      "what the organisation works on (education, health, women, environment, animals, elderly) and where",
      "who it helps and how — camps, drives, centres, counselling",
      "how to volunteer, donate or get help",
      "openness — registration, how funds are used, receipts",
    ],
    services: [
      { en: "Help for those in need", hi: "ज़रूरतमंदों की मदद", desc: "Food, clothes, books or medicines reaching the people who need them.", descHi: "खाना, कपड़े, किताबें या दवाइयाँ उन तक, जिन्हें ज़रूरत है।" },
      { en: "Education support", hi: "शिक्षा में सहयोग", desc: "Tuition classes, school kits and help with admissions for children.", descHi: "बच्चों के लिए ट्यूशन, स्कूल किट और दाख़िले में मदद।" },
      { en: "Health camps", hi: "स्वास्थ्य शिविर", desc: "Check-up, blood donation and awareness camps with doctors.", descHi: "डॉक्टरों के साथ जाँच, रक्तदान और जागरूकता शिविर।" },
      { en: "Women & skill training", hi: "महिला और कौशल प्रशिक्षण", desc: "Sewing, computer and self-help group training.", descHi: "सिलाई, कंप्यूटर और स्वयं सहायता समूह की ट्रेनिंग।" },
      { en: "Volunteer with us", hi: "स्वयंसेवक बनें", desc: "Give a few hours a week for drives and events.", descHi: "हफ़्ते में कुछ घंटे अभियानों और आयोजनों के लिए दें।" },
      { en: "Donate & sponsor", hi: "दान और सहयोग", desc: "Support a child, a camp or a drive; receipt for every donation.", descHi: "किसी बच्चे, कैम्प या अभियान का सहयोग करें; हर दान की रसीद।" },
      { en: "Awareness drives", hi: "जागरूकता अभियान", desc: "Cleanliness, tree planting, road safety and health awareness.", descHi: "स्वच्छता, पौधारोपण, सड़क सुरक्षा और स्वास्थ्य जागरूकता।" },
    ],
    whyUs: [
      { en: "Registered, open accounts", hi: "पंजीकृत, खुला हिसाब" },
      { en: "Work on the ground", hi: "ज़मीन पर काम" },
      { en: "Help reaches directly", hi: "मदद सीधे पहुँचती है" },
      { en: "Local volunteers", hi: "स्थानीय स्वयंसेवक" },
      { en: "Receipt for every donation", hi: "हर दान की रसीद" },
      { en: "Photos and updates shared", hi: "फ़ोटो और अपडेट साझा" },
      { en: "Join on WhatsApp", hi: "WhatsApp पर जुड़ें" },
    ],
    steps: [
      { en: "Message us", hi: "मैसेज करें", desc: "Tell us if you need help, want to volunteer or wish to donate.", descHi: "बताएँ कि मदद चाहिए, स्वयंसेवक बनना है या दान करना है।" },
      { en: "We talk", hi: "हम बात करते हैं", desc: "A volunteer calls to understand what is needed.", descHi: "एक स्वयंसेवक फ़ोन करके ज़रूरत समझता है।" },
      { en: "Help or join", hi: "मदद या जुड़ाव", desc: "Help is arranged, or you are added to the volunteer group.", descHi: "मदद का इंतज़ाम होता है, या आप स्वयंसेवक ग्रुप में जुड़ते हैं।" },
      { en: "Stay updated", hi: "जुड़े रहें", desc: "Photos and updates of the work are shared with you.", descHi: "काम की फ़ोटो और अपडेट आपके साथ साझा होते हैं।" },
    ],
    faq: [
      { q: "How can I volunteer?", qHi: "स्वयंसेवक कैसे बनें?", a: "Message your name, area and free time; we add you to the volunteer group and the next drive.", aHi: "अपना नाम, इलाक़ा और खाली समय भेजें; हम आपको स्वयंसेवक ग्रुप और अगले अभियान में जोड़ेंगे।" },
      { q: "How do I donate?", qHi: "दान कैसे करें?", a: "By UPI or bank transfer; a receipt is sent for every donation. Message us for the details.", aHi: "UPI या बैंक ट्रांसफ़र से; हर दान की रसीद भेजी जाती है। डिटेल के लिए मैसेज करें।" },
      { q: "Is the organisation registered?", qHi: "क्या संस्था पंजीकृत है?", a: "Ask us — registration and account details are shared on request.", aHi: "पूछ लें — पंजीकरण और हिसाब की जानकारी माँगने पर दी जाती है।" },
      { q: "Can I donate things instead of money?", qHi: "पैसे की जगह सामान दान कर सकते हैं?", a: "Yes — clothes, books, grains, in good condition; message us before sending.", aHi: "हाँ — कपड़े, किताबें, अनाज, अच्छी हालत में; भेजने से पहले मैसेज कर लें।" },
      { q: "Where does the money go?", qHi: "पैसा कहाँ जाता है?", a: "To the work you choose — camps, kits, meals; updates and photos are shared with donors.", aHi: "आपके चुने काम में — कैम्प, किट, भोजन; दानदाताओं को अपडेट और फ़ोटो भेजे जाते हैं।" },
      { q: "Can I get help from the organisation?", qHi: "क्या मुझे संस्था से मदद मिल सकती है?", a: "Message us your need; a volunteer will call and guide you to the right help.", aHi: "अपनी ज़रूरत मैसेज करें; एक स्वयंसेवक फ़ोन करके सही मदद तक पहुँचाएगा।" },
      { q: "Can students do an internship?", qHi: "क्या छात्र इंटर्नशिप कर सकते हैं?", a: "Yes, for projects and social work credit; message us with your course and college.", aHi: "हाँ, प्रोजेक्ट और सामाजिक कार्य के लिए; अपना कोर्स और कॉलेज बताकर मैसेज करें।" },
    ],
    generic: ["connect with us", "explore options", "social service", "helping society", "making a difference", "noble cause"],
  },

  samaj: {
    explain: [
      "which samaj or samiti it is, the area it covers and the office bearers",
      "what it does — gatherings, matrimonial introductions, help for students, hall or dharamshala, support in hard times",
      "membership — who can join and how",
      "upcoming events, annual meet and festivals",
    ],
    services: [
      { en: "Samaj gatherings", hi: "समाज के सम्मेलन", desc: "Annual meet, festivals and family gatherings of the community.", descHi: "वार्षिक सम्मेलन, त्योहार और समाज के पारिवारिक मिलन।" },
      { en: "Matrimonial introductions", hi: "रिश्तों की जानकारी", desc: "Bio-data exchange and introductions within the samaj.", descHi: "समाज के भीतर बायोडाटा का आदान-प्रदान और परिचय।" },
      { en: "Help for students", hi: "छात्रों के लिए सहयोग", desc: "Books, fees or hostel help for students, as the samiti decides.", descHi: "छात्रों के लिए किताबें, फ़ीस या हॉस्टल में मदद, समिति के निर्णय से।" },
      { en: "Hall or dharamshala", hi: "भवन या धर्मशाला", desc: "Hall or dharamshala for weddings and functions, where the samaj has one.", descHi: "शादी और फ़ंक्शन के लिए भवन या धर्मशाला, जहाँ समाज के पास हो।" },
      { en: "Support in hard times", hi: "मुश्किल में सहयोग", desc: "Standing with families in illness, death or loss.", descHi: "बीमारी, मृत्यु या नुक़सान में परिवार के साथ खड़े रहना।" },
      { en: "Membership & directory", hi: "सदस्यता और निर्देशिका", desc: "Register your family in the samaj directory.", descHi: "अपने परिवार को समाज की निर्देशिका में दर्ज कराएँ।" },
      { en: "Youth & mahila mandal", hi: "युवा और महिला मंडल", desc: "Sports, cultural programmes and women's gatherings.", descHi: "खेल, सांस्कृतिक कार्यक्रम और महिलाओं की सभाएँ।" },
    ],
    whyUs: [
      { en: "One platform for the samaj", hi: "पूरे समाज का एक मंच" },
      { en: "Families stand together", hi: "परिवार साथ खड़े होते हैं" },
      { en: "Elected office bearers", hi: "चुने हुए पदाधिकारी" },
      { en: "Accounts shown every year", hi: "हर साल हिसाब सामने" },
      { en: "Help within the community", hi: "समाज के भीतर मदद" },
      { en: "Events for every age", hi: "हर उम्र के कार्यक्रम" },
      { en: "Notices on WhatsApp", hi: "WhatsApp पर सूचना" },
    ],
    steps: [
      { en: "Contact a member", hi: "सदस्य से संपर्क करें", desc: "Message the office bearer or the WhatsApp number on this page.", descHi: "इसी पेज पर दिए पदाधिकारी या WhatsApp नंबर पर मैसेज करें।" },
      { en: "Fill the membership form", hi: "सदस्यता फ़ॉर्म भरें", desc: "Family details, address and a photo for the directory.", descHi: "निर्देशिका के लिए परिवार की जानकारी, पता और फ़ोटो।" },
      { en: "Join the group", hi: "ग्रुप से जुड़ें", desc: "Added to the samaj WhatsApp group for events and notices.", descHi: "आयोजनों और सूचनाओं के लिए समाज के WhatsApp ग्रुप में जुड़ें।" },
      { en: "Take part", hi: "भाग लें", desc: "Come to gatherings, help in events, bring your family.", descHi: "सम्मेलनों में आएँ, आयोजनों में हाथ बँटाएँ, परिवार को साथ लाएँ।" },
    ],
    faq: [
      { q: "Who can become a member?", qHi: "सदस्य कौन बन सकता है?", a: "Families of the samaj living in the area; message us and we will guide you.", aHi: "इलाक़े में रहने वाले समाज के परिवार; मैसेज करें, हम रास्ता बताएँगे।" },
      { q: "What is the membership fee?", qHi: "सदस्यता शुल्क कितना है?", a: "It is decided by the samiti; message us for the current details.", aHi: "यह समिति तय करती है; मौजूदा जानकारी के लिए मैसेज करें।" },
      { q: "Do you help with matrimonial matches?", qHi: "क्या रिश्ते में मदद करते हैं?", a: "Yes, bio-data of members is shared within the samaj with the family's consent.", aHi: "हाँ, परिवार की सहमति से सदस्यों का बायोडाटा समाज के भीतर साझा किया जाता है।" },
      { q: "Can we book the hall for a wedding?", qHi: "शादी के लिए भवन बुक हो सकता है?", a: "Where the samaj has a hall, members can book it; message us the date.", aHi: "जहाँ समाज के पास भवन है, सदस्य बुक कर सकते हैं; तारीख़ मैसेज करें।" },
      { q: "When is the annual meet?", qHi: "वार्षिक सम्मेलन कब है?", a: "Dates are announced in the WhatsApp group and on this page.", aHi: "तारीख़ें WhatsApp ग्रुप और इसी पेज पर बताई जाती हैं।" },
      { q: "Is there help for students?", qHi: "छात्रों के लिए सहयोग है?", a: "Ask the samiti — help for books, fees or hostel is given as decided each year.", aHi: "समिति से पूछें — किताबें, फ़ीस या हॉस्टल की मदद हर साल के निर्णय से दी जाती है।" },
      { q: "How can I help the samaj?", qHi: "समाज की मदद कैसे करूँ?", a: "Give time in events, sponsor a programme or donate; a receipt is given and accounts are shared with members.", aHi: "आयोजनों में समय दें, कोई कार्यक्रम स्पॉन्सर करें या दान दें; रसीद दी जाती है और हिसाब सदस्यों के सामने रखा जाता है।" },
    ],
    generic: ["connect with us", "explore options", "unity", "community service", "for the samaj", "tradition and culture"],
  },

  temple: {
    explain: [
      "the deity, the place and its story in a few lines; the trust that runs it",
      "daily darshan and aarti timings, festivals and special days",
      "sevas, pooja booking, prasad, bhandara and donations",
      "facilities for devotees — parking, dharamshala, annakshetra",
    ],
    services: [
      { en: "Daily darshan & aarti", hi: "रोज़ दर्शन और आरती", desc: "Open for darshan every day; morning and evening aarti.", descHi: "रोज़ दर्शन के लिए खुला; सुबह और शाम की आरती।" },
      { en: "Pooja & seva booking", hi: "पूजा और सेवा बुकिंग", desc: "Book a pooja, abhishek or special seva in your name.", descHi: "अपने नाम से पूजा, अभिषेक या विशेष सेवा बुक करें।" },
      { en: "Prasad & bhandara", hi: "प्रसाद और भंडारा", desc: "Prasad for devotees; bhandara on festivals and by sponsors.", descHi: "भक्तों के लिए प्रसाद; त्योहारों पर और दानदाताओं के सहयोग से भंडारा।" },
      { en: "Festivals & utsav", hi: "त्योहार और उत्सव", desc: "Special programmes, jagran and kirtan on festival days.", descHi: "त्योहारों पर विशेष कार्यक्रम, जागरण और कीर्तन।" },
      { en: "Donation & seva", hi: "दान और सेवा", desc: "Donate for annadaan, construction or daily seva; receipt given.", descHi: "अन्नदान, निर्माण या नित्य सेवा के लिए दान; रसीद दी जाती है।" },
      { en: "Dharamshala", hi: "धर्मशाला", desc: "Simple rooms for devotees from outside, where available.", descHi: "बाहर से आए भक्तों के लिए साधारण कमरे, जहाँ उपलब्ध हों।" },
      { en: "Katha, satsang & classes", hi: "कथा, सत्संग और कक्षाएँ", desc: "Satsang, bhajan and religious classes for children.", descHi: "सत्संग, भजन और बच्चों के लिए धार्मिक कक्षाएँ।" },
    ],
    whyUs: [
      { en: "Open to every devotee", hi: "हर भक्त के लिए खुला" },
      { en: "Clean, peaceful premises", hi: "साफ़, शांत परिसर" },
      { en: "Pooja by trained pandits", hi: "योग्य पंडितों द्वारा पूजा" },
      { en: "Receipt for every donation", hi: "हर दान की रसीद" },
      { en: "Trust accounts kept open", hi: "ट्रस्ट का हिसाब खुला" },
      { en: "Festivals celebrated together", hi: "त्योहार सब मिलकर" },
      { en: "Seva booking on WhatsApp", hi: "WhatsApp पर सेवा बुकिंग" },
    ],
    steps: [
      { en: "Check the timings", hi: "समय देखें", desc: "Darshan and aarti timings are on this page.", descHi: "दर्शन और आरती का समय इसी पेज पर है।" },
      { en: "Book a seva", hi: "सेवा बुक करें", desc: "Message the pooja, the date and the devotee's name.", descHi: "पूजा, तारीख़ और भक्त का नाम मैसेज करें।" },
      { en: "Visit the temple", hi: "मंदिर आएँ", desc: "Come for darshan; the seva is done in your name.", descHi: "दर्शन के लिए आएँ; सेवा आपके नाम से होती है।" },
      { en: "Prasad & receipt", hi: "प्रसाद और रसीद", desc: "Receive prasad and a receipt for your offering.", descHi: "प्रसाद और अपने दान की रसीद पाएँ।" },
    ],
    faq: [
      { q: "What are the darshan timings?", qHi: "दर्शन का समय क्या है?", a: "See the timings on this page; they change on festival days, so message to check.", aHi: "इसी पेज पर समय देखें; त्योहारों पर बदलता है, इसलिए मैसेज करके पूछ लें।" },
      { q: "Can I book a pooja from outside the city?", qHi: "शहर से बाहर से पूजा बुक हो सकती है?", a: "Yes, message the pooja and the name; it is done on your behalf and prasad is sent where possible.", aHi: "हाँ, पूजा और नाम मैसेज करें; आपकी ओर से पूजा होती है और जहाँ संभव हो प्रसाद भेजा जाता है।" },
      { q: "How do I donate?", qHi: "दान कैसे करें?", a: "At the donation counter, by UPI or bank transfer; a receipt is given for every donation.", aHi: "दान काउंटर पर, UPI या बैंक ट्रांसफ़र से; हर दान की रसीद दी जाती है।" },
      { q: "Can we sponsor a bhandara?", qHi: "क्या हम भंडारा करवा सकते हैं?", a: "Yes, message the date and the number of people; the trust arranges it.", aHi: "हाँ, तारीख़ और लोगों की संख्या मैसेज करें; ट्रस्ट इंतज़ाम करता है।" },
      { q: "Is there a place to stay?", qHi: "ठहरने की जगह है?", a: "Ask the trust — a dharamshala is available at some temples; message your dates.", aHi: "ट्रस्ट से पूछें — कुछ मंदिरों में धर्मशाला होती है; अपनी तारीख़ें मैसेज करें।" },
      { q: "Is there a dress code?", qHi: "क्या कोई ड्रेस कोड है?", a: "Modest, traditional clothes are preferred; footwear is left outside the temple.", aHi: "सादे, पारंपरिक कपड़े बेहतर हैं; जूते-चप्पल मंदिर के बाहर रखें।" },
      { q: "Can we hold a wedding or function here?", qHi: "क्या यहाँ शादी या फ़ंक्शन हो सकता है?", a: "Where the temple has a hall, yes; message the trust with your date.", aHi: "जहाँ मंदिर में हॉल है, हाँ; अपनी तारीख़ के साथ ट्रस्ट को मैसेज करें।" },
    ],
    generic: ["connect with us", "explore options", "blessings", "spiritual", "devotion", "divine"],
  },

  club: {
    explain: [
      "the club and chapter, and your post or role in it",
      "what the club does — service projects, blood donation, eye camps, school support, tree planting",
      "fellowship — meetings, installation, family events",
      "how to join, sponsor a project or partner with the club",
    ],
    services: [
      { en: "Service projects", hi: "सेवा परियोजनाएँ", desc: "Health camps, school kits, tree planting and relief work in the area.", descHi: "इलाक़े में स्वास्थ्य शिविर, स्कूल किट, पौधारोपण और राहत कार्य।" },
      { en: "Blood donation & eye camps", hi: "रक्तदान और नेत्र शिविर", desc: "Regular camps with hospitals and eye banks.", descHi: "अस्पतालों और नेत्र बैंक के साथ नियमित शिविर।" },
      { en: "School & student support", hi: "स्कूल और छात्र सहयोग", desc: "Help for deserving students and government schools.", descHi: "ज़रूरतमंद छात्रों और सरकारी स्कूलों की मदद।" },
      { en: "Meetings & fellowship", hi: "बैठकें और फ़ेलोशिप", desc: "Meet members, hear speakers and plan projects.", descHi: "सदस्यों से मिलें, वक्ताओं को सुनें और प्रोजेक्ट बनाएँ।" },
      { en: "Join as a member", hi: "सदस्य बनें", desc: "Professionals and business owners invited to serve together.", descHi: "प्रोफ़ेशनल और व्यापारी, मिलकर सेवा के लिए आमंत्रित।" },
      { en: "Sponsor a project", hi: "प्रोजेक्ट स्पॉन्सर करें", desc: "Support a camp or a school in your name or your firm's.", descHi: "अपने या अपनी फ़र्म के नाम से किसी कैम्प या स्कूल का सहयोग करें।" },
      { en: "Youth & community programmes", hi: "युवा और समुदाय कार्यक्रम", desc: "Career talks, sports and cleanliness drives.", descHi: "करियर गाइडेंस, खेल और स्वच्छता अभियान।" },
    ],
    whyUs: [
      { en: "Part of a global network", hi: "वैश्विक नेटवर्क का हिस्सा" },
      { en: "Service with fellowship", hi: "सेवा के साथ दोस्ती" },
      { en: "Projects done, not promised", hi: "काम करके दिखाते हैं" },
      { en: "Accounts audited every year", hi: "हर साल ऑडिट" },
      { en: "Members from every profession", hi: "हर पेशे के सदस्य" },
      { en: "Sponsors acknowledged openly", hi: "स्पॉन्सर को खुला सम्मान" },
      { en: "Reach us on WhatsApp", hi: "WhatsApp पर संपर्क" },
    ],
    steps: [
      { en: "Message the club", hi: "क्लब को मैसेज करें", desc: "Say if you want to join, sponsor or need a camp.", descHi: "बताएँ कि जुड़ना है, स्पॉन्सर करना है या कैम्प चाहिए।" },
      { en: "Attend a meeting", hi: "बैठक में आएँ", desc: "Come as a guest and meet the members.", descHi: "अतिथि के रूप में आएँ और सदस्यों से मिलें।" },
      { en: "Membership", hi: "सदस्यता", desc: "Proposed by a member and inducted at a meeting.", descHi: "किसी सदस्य के प्रस्ताव पर बैठक में सदस्यता दी जाती है।" },
      { en: "Serve together", hi: "मिलकर सेवा करें", desc: "Take part in projects and camps.", descHi: "प्रोजेक्ट और कैम्प में हिस्सा लें।" },
    ],
    faq: [
      { q: "How do I join the club?", qHi: "क्लब में कैसे जुड़ें?", a: "Message us; you attend a meeting as a guest, and a member proposes your name.", aHi: "मैसेज करें; आप अतिथि के रूप में बैठक में आते हैं, फिर कोई सदस्य आपका नाम प्रस्तावित करता है।" },
      { q: "What does membership cost?", qHi: "सदस्यता का खर्च कितना है?", a: "Dues are set by the club each year; message us for the details.", aHi: "शुल्क क्लब हर साल तय करता है; जानकारी के लिए मैसेज करें।" },
      { q: "Can the club hold a camp in our area?", qHi: "हमारे इलाक़े में कैम्प लग सकता है?", a: "Yes, message the place and the need; projects are planned by the committee.", aHi: "हाँ, जगह और ज़रूरत मैसेज करें; प्रोजेक्ट समिति तय करती है।" },
      { q: "How can my firm sponsor?", qHi: "मेरी फ़र्म स्पॉन्सर कैसे करे?", a: "Pick a project or camp; sponsors are acknowledged at the event and on social media.", aHi: "कोई प्रोजेक्ट या कैम्प चुनें; स्पॉन्सर को आयोजन और सोशल मीडिया पर सम्मान दिया जाता है।" },
      { q: "When are the meetings?", qHi: "बैठक कब होती है?", a: "Regularly, at a fixed venue; message us for the next meeting's date and place.", aHi: "नियमित रूप से, तय जगह पर; अगली बैठक की तारीख़ और जगह के लिए मैसेज करें।" },
      { q: "Can I attend without being a member?", qHi: "बिना सदस्य बने आ सकते हैं?", a: "Yes, as a guest of a member; message us first so we can arrange it.", aHi: "हाँ, किसी सदस्य के अतिथि के रूप में; पहले मैसेज कर लें ताकि इंतज़ाम हो सके।" },
      { q: "Do you accept donations?", qHi: "दान लेते हैं?", a: "Yes, for specific projects and camps; a receipt is given for every donation.", aHi: "हाँ, तय प्रोजेक्ट और कैम्प के लिए; हर दान की रसीद दी जाती है।" },
    ],
    generic: ["connect with us", "explore options", "community service", "networking", "giving back", "we serve"],
  },

  union: {
    explain: [
      "which union or association, whom it represents (workers, traders, drivers, teachers) and the area",
      "what it does for members — grievances, meetings with authorities, legal help, welfare",
      "membership — who can join and how",
      "notices, meetings and the issues being taken up",
    ],
    services: [
      { en: "Member grievances", hi: "सदस्यों की शिकायतें", desc: "Workplace, licence or payment issues taken up with the authorities.", descHi: "काम, लाइसेंस या भुगतान की समस्या अधिकारियों तक उठाई जाती है।" },
      { en: "Representation with authorities", hi: "प्रशासन से बातचीत", desc: "Memorandums and meetings with departments and the administration.", descHi: "विभागों और प्रशासन को ज्ञापन और उनके साथ बैठकें।" },
      { en: "Legal help", hi: "क़ानूनी मदद", desc: "Guidance and an advocate's contact for a member's dispute.", descHi: "सदस्य के विवाद में सलाह और वकील से संपर्क।" },
      { en: "Welfare schemes", hi: "कल्याण योजनाएँ", desc: "Help with welfare boards, insurance and government schemes for members.", descHi: "कल्याण बोर्ड, बीमा और सरकारी योजनाओं में सदस्यों की मदद।" },
      { en: "Meetings & notices", hi: "बैठकें और सूचनाएँ", desc: "General body meetings, circulars and updates on WhatsApp.", descHi: "आम सभा, सर्कुलर और WhatsApp पर अपडेट।" },
      { en: "Membership card", hi: "सदस्य पहचान पत्र", desc: "Identity card for every registered member.", descHi: "हर पंजीकृत सदस्य के लिए पहचान पत्र।" },
      { en: "Help in emergencies", hi: "आपात मदद", desc: "Support to a member's family in accident or loss.", descHi: "दुर्घटना या नुक़सान में सदस्य के परिवार का सहारा।" },
    ],
    whyUs: [
      { en: "One voice for all members", hi: "सब सदस्यों की एक आवाज़" },
      { en: "Elected committee", hi: "चुनी हुई कार्यकारिणी" },
      { en: "Issues taken to the top", hi: "बात ऊपर तक पहुँचती है" },
      { en: "With members in trouble", hi: "मुश्किल में सदस्य के साथ" },
      { en: "Accounts open to members", hi: "हिसाब सदस्यों के सामने" },
      { en: "Notices on WhatsApp", hi: "WhatsApp पर सूचना" },
    ],
    steps: [
      { en: "Contact the office", hi: "कार्यालय से संपर्क करें", desc: "Message your name, your work and your area.", descHi: "अपना नाम, काम और इलाक़ा मैसेज करें।" },
      { en: "Membership form", hi: "सदस्यता फ़ॉर्म", desc: "Fill the form with ID proof and the membership fee.", descHi: "ID प्रूफ़ और सदस्यता शुल्क के साथ फ़ॉर्म भरें।" },
      { en: "Card & group", hi: "कार्ड और ग्रुप", desc: "Card issued; added to the members' WhatsApp group.", descHi: "कार्ड जारी; सदस्यों के WhatsApp ग्रुप में जोड़ा जाता है।" },
      { en: "Raise your issue", hi: "अपनी बात रखें", desc: "Send the problem with papers; the committee takes it up.", descHi: "काग़ज़ों के साथ समस्या भेजें; कार्यकारिणी उसे उठाती है।" },
    ],
    faq: [
      { q: "Who can join?", qHi: "कौन जुड़ सकता है?", a: "Anyone in the trade or work the association covers; message us and we will confirm.", aHi: "जिस काम या व्यापार की यह एसोसिएशन है, उसमें लगा कोई भी; मैसेज करें, हम कन्फ़र्म करेंगे।" },
      { q: "What is the membership fee?", qHi: "सदस्यता शुल्क कितना है?", a: "It is decided by the general body; message us for the current fee.", aHi: "यह आम सभा तय करती है; मौजूदा शुल्क के लिए मैसेज करें।" },
      { q: "Will you help with my dispute?", qHi: "मेरे विवाद में मदद करेंगे?", a: "Yes, bring the papers; the committee takes it up and guides you on the legal steps.", aHi: "हाँ, काग़ज़ लेकर आएँ; कार्यकारिणी मामला उठाती है और क़ानूनी रास्ता बताती है।" },
      { q: "How do I raise a complaint?", qHi: "शिकायत कैसे करें?", a: "Message on WhatsApp or write to the office with the details and papers.", aHi: "WhatsApp पर मैसेज करें या पूरी जानकारी और काग़ज़ों के साथ कार्यालय को लिखें।" },
      { q: "Is there any insurance or welfare benefit?", qHi: "बीमा या कल्याण लाभ है?", a: "Ask the office — schemes differ by trade; we help members with the forms.", aHi: "कार्यालय से पूछें — योजनाएँ काम के हिसाब से अलग होती हैं; फ़ॉर्म में हम मदद करते हैं।" },
      { q: "When are the meetings?", qHi: "बैठकें कब होती हैं?", a: "Notices go out on WhatsApp; the general body meets as per the rules.", aHi: "सूचना WhatsApp पर जाती है; आम सभा नियमों के अनुसार होती है।" },
      { q: "Will I get a membership card?", qHi: "सदस्य पहचान पत्र मिलेगा?", a: "Yes, after registration; bring a photo and ID proof to the office.", aHi: "हाँ, पंजीकरण के बाद; फ़ोटो और ID प्रूफ़ लेकर कार्यालय आएँ।" },
    ],
    generic: ["connect with us", "explore options", "unity is strength", "member welfare", "solidarity", "fighting for rights"],
  },

  housing: {
    explain: [
      "the society or RWA — its name, the colony or building, the committee and your post",
      "what the committee handles — maintenance, security, water, parking, cleanliness",
      "how residents raise a complaint and pay maintenance",
      "notices, meetings and events for residents",
    ],
    services: [
      { en: "Maintenance & repairs", hi: "रखरखाव और मरम्मत", desc: "Lifts, pumps, lights and common areas kept in order.", descHi: "लिफ़्ट, पंप, लाइट और कॉमन एरिया का रखरखाव।" },
      { en: "Security & gate", hi: "सुरक्षा और गेट", desc: "Guards, visitor entry and vehicle passes.", descHi: "गार्ड, विज़िटर एंट्री और गाड़ी के पास।" },
      { en: "Complaints & helpdesk", hi: "शिकायत और हेल्पडेस्क", desc: "Raise water, cleaning or parking issues; tracked till closed.", descHi: "पानी, सफ़ाई या पार्किंग की शिकायत करें; हल होने तक ट्रैक।" },
      { en: "Maintenance payment", hi: "मेंटेनेंस भुगतान", desc: "Monthly dues by UPI or bank; receipt sent on WhatsApp.", descHi: "महीने का मेंटेनेंस UPI या बैंक से; रसीद WhatsApp पर।" },
      { en: "NOC & documents", hi: "NOC और दस्तावेज़", desc: "NOC for sale, rent or loan; share certificate and membership.", descHi: "बिक्री, किराये या लोन के लिए NOC; शेयर सर्टिफ़िकेट और सदस्यता।" },
      { en: "Meetings & notices", hi: "बैठकें और सूचनाएँ", desc: "AGM, committee meetings and circulars on WhatsApp.", descHi: "AGM, समिति की बैठकें और WhatsApp पर सर्कुलर।" },
      { en: "Events & festivals", hi: "आयोजन और त्योहार", desc: "Holi, Diwali, Independence Day and sports for residents.", descHi: "निवासियों के लिए होली, दिवाली, स्वतंत्रता दिवस और खेल।" },
    ],
    whyUs: [
      { en: "Elected residents' committee", hi: "निवासियों की चुनी समिति" },
      { en: "Accounts shared with residents", hi: "हिसाब निवासियों के साथ" },
      { en: "Complaints tracked till closed", hi: "शिकायत हल होने तक ट्रैक" },
      { en: "Safe gate, verified visitors", hi: "सुरक्षित गेट, पहचान के बाद एंट्री" },
      { en: "Clean common areas", hi: "साफ़ कॉमन एरिया" },
      { en: "Notices on WhatsApp", hi: "WhatsApp पर सूचना" },
      { en: "Festivals celebrated together", hi: "त्योहार सब साथ" },
    ],
    steps: [
      { en: "Register as a resident", hi: "निवासी के रूप में दर्ज हों", desc: "Flat or house number, name and contact for the records.", descHi: "रिकॉर्ड के लिए फ़्लैट या मकान नंबर, नाम और संपर्क।" },
      { en: "Join the group", hi: "ग्रुप से जुड़ें", desc: "Added to the residents' WhatsApp group for notices.", descHi: "सूचनाओं के लिए निवासियों के WhatsApp ग्रुप में जोड़ा जाता है।" },
      { en: "Raise issues", hi: "समस्या बताएँ", desc: "Message or write at the office; it is assigned and tracked.", descHi: "मैसेज करें या कार्यालय में लिखें; काम सौंपकर ट्रैक किया जाता है।" },
      { en: "Pay dues on time", hi: "समय पर मेंटेनेंस दें", desc: "UPI or bank; receipt sent on WhatsApp.", descHi: "UPI या बैंक से; रसीद WhatsApp पर।" },
    ],
    faq: [
      { q: "How do I pay maintenance?", qHi: "मेंटेनेंस कैसे दें?", a: "By UPI or bank transfer to the society account; the receipt comes on WhatsApp.", aHi: "सोसाइटी के खाते में UPI या बैंक ट्रांसफ़र से; रसीद WhatsApp पर आती है।" },
      { q: "How do I raise a complaint?", qHi: "शिकायत कैसे करें?", a: "Message on WhatsApp or write at the office with your flat number and the issue.", aHi: "अपने फ़्लैट नंबर और समस्या के साथ WhatsApp पर मैसेज करें या कार्यालय में लिखें।" },
      { q: "How do I get an NOC?", qHi: "NOC कैसे मिलेगा?", a: "Apply at the office with your papers and dues cleared; the committee issues it.", aHi: "काग़ज़ और बक़ाया चुकाकर कार्यालय में आवेदन करें; समिति NOC जारी करती है।" },
      { q: "Can tenants join the group?", qHi: "किरायेदार ग्रुप में जुड़ सकते हैं?", a: "Yes, with the owner's details and police verification as the society requires.", aHi: "हाँ, मालिक की जानकारी और सोसाइटी के नियम के अनुसार पुलिस वेरिफ़िकेशन के साथ।" },
      { q: "When is the AGM?", qHi: "AGM कब है?", a: "Notice is sent to all members in advance on WhatsApp and the notice board.", aHi: "सभी सदस्यों को पहले से WhatsApp और नोटिस बोर्ड पर सूचना दी जाती है।" },
      { q: "Where do I get visitor or vehicle passes?", qHi: "विज़िटर या गाड़ी का पास कहाँ मिलेगा?", a: "At the society office or the gate; message us the vehicle details.", aHi: "सोसाइटी कार्यालय या गेट पर; गाड़ी की जानकारी मैसेज करें।" },
      { q: "Can we book the clubhouse or hall?", qHi: "क्लबहाउस या हॉल बुक हो सकता है?", a: "Where the society has one, residents can book it; message the date to the office.", aHi: "जहाँ सोसाइटी के पास है, निवासी बुक कर सकते हैं; तारीख़ कार्यालय को मैसेज करें।" },
    ],
    generic: ["connect with us", "explore options", "community living", "better living", "harmony", "happy homes"],
  },
};

export const COMMUNITY_DEFAULT: TradeData = {
  explain: [
    "who the organisation or person is — the post, the body and the area",
    "what it does for people — help, events, representation, welfare",
    "how to reach, join or get help",
    "upcoming events and notices",
  ],
  services: [
    { en: "Help for people", hi: "लोगों की मदद", desc: "Guidance and support for anyone who reaches out.", descHi: "जो भी संपर्क करे, उसे सलाह और सहयोग।" },
    { en: "Events & gatherings", hi: "आयोजन और सभाएँ", desc: "Meetings, programmes and celebrations for the community.", descHi: "समुदाय के लिए बैठकें, कार्यक्रम और उत्सव।" },
    { en: "Representation", hi: "प्रतिनिधित्व", desc: "Issues taken to the right office or authority.", descHi: "मुद्दे सही दफ़्तर या अधिकारी तक पहुँचाना।" },
    { en: "Membership", hi: "सदस्यता", desc: "Join as a member or a volunteer.", descHi: "सदस्य या स्वयंसेवक के रूप में जुड़ें।" },
    { en: "Welfare & support", hi: "कल्याण और सहयोग", desc: "Help to families in need, as the organisation decides.", descHi: "ज़रूरतमंद परिवारों की मदद, संस्था के निर्णय से।" },
    { en: "Notices & updates", hi: "सूचनाएँ और अपडेट", desc: "News, notices and event dates on WhatsApp.", descHi: "ख़बरें, सूचनाएँ और आयोजनों की तारीख़ें WhatsApp पर।" },
  ],
  whyUs: [
    { en: "Open to everyone", hi: "सबके लिए खुला" },
    { en: "Work on the ground", hi: "ज़मीन पर काम" },
    { en: "Elected, accountable committee", hi: "चुनी हुई, जवाबदेह समिति" },
    { en: "Help reaches directly", hi: "मदद सीधे पहुँचती है" },
    { en: "Accounts kept open", hi: "हिसाब खुला" },
    { en: "Reach us on WhatsApp", hi: "WhatsApp पर संपर्क" },
  ],
  steps: [
    { en: "Message us", hi: "मैसेज करें", desc: "Tell us who you are and what you need.", descHi: "बताएँ आप कौन हैं और क्या चाहिए।" },
    { en: "We talk", hi: "हम बात करते हैं", desc: "Someone from the team calls to understand it.", descHi: "टीम से कोई फ़ोन करके बात समझता है।" },
    { en: "Join or get help", hi: "जुड़ें या मदद पाएँ", desc: "You are added to the group, or your matter is taken up.", descHi: "आप ग्रुप में जुड़ते हैं, या आपकी बात उठाई जाती है।" },
  ],
  faq: [
    { q: "How do I contact you?", qHi: "आपसे संपर्क कैसे करें?", a: "Message on WhatsApp with your name and area; call for anything urgent.", aHi: "WhatsApp पर नाम और इलाक़ा भेजें; बहुत ज़रूरी हो तो फ़ोन करें।" },
    { q: "How can I join?", qHi: "कैसे जुड़ सकते हैं?", a: "Message us; we tell you the membership steps and add you to the group.", aHi: "मैसेज करें; हम सदस्यता की प्रक्रिया बताते हैं और ग्रुप में जोड़ते हैं।" },
    { q: "Is there a fee?", qHi: "क्या कोई शुल्क है?", a: "Membership fees, if any, are decided by the committee; message us for details.", aHi: "सदस्यता शुल्क, अगर है, तो समिति तय करती है; जानकारी के लिए मैसेज करें।" },
    { q: "Can I get help for my problem?", qHi: "मेरी समस्या में मदद मिलेगी?", a: "Message us the details; it is taken to the right person or office.", aHi: "पूरी बात मैसेज करें; उसे सही व्यक्ति या दफ़्तर तक पहुँचाया जाता है।" },
    { q: "When is the next meeting or event?", qHi: "अगली बैठक या आयोजन कब है?", a: "Dates are announced on WhatsApp and on this page; message us to check.", aHi: "तारीख़ें WhatsApp और इसी पेज पर बताई जाती हैं; पूछने के लिए मैसेज करें।" },
    { q: "How can I support the work?", qHi: "काम में सहयोग कैसे करूँ?", a: "Give time as a volunteer or donate; a receipt is given for every donation.", aHi: "स्वयंसेवक बनकर समय दें या दान करें; हर दान की रसीद दी जाती है।" },
  ],
  generic: ["connect with us", "explore options", "community", "together", "service", "for everyone"],
};
