// Education trades: school, play school, coaching / tuition, college, computer / skill centre, teacher / trainer,
// dance / music / art class, student. See types.ts for the rules (no numbers, no claims; true of any decent business of the trade).
import type { TradeData } from "./types";

export const EDUCATION: Record<string, TradeData> = {
  school: {
    explain: [
      "classes offered (nursery to which class), the board and the medium of instruction",
      "the campus and facilities — classrooms, playground, library, computer lab, transport",
      "admission process and the documents needed",
      "the school's approach — activities, sports, values, attention to each child",
    ],
    services: [
      { en: "Pre-primary & nursery", hi: "प्री-प्राइमरी और नर्सरी", desc: "Play-based learning for the youngest children in a safe, caring space.", descHi: "छोटे बच्चों के लिए खेल-खेल में पढ़ाई, सुरक्षित और प्यार भरे माहौल में।" },
      { en: "Primary & secondary classes", hi: "प्राइमरी और सेकेंडरी कक्षाएँ", desc: "Regular classes as per the board syllabus, with tests and homework.", descHi: "बोर्ड के सिलेबस के अनुसार नियमित कक्षाएँ, टेस्ट और होमवर्क के साथ।" },
      { en: "Sports & activities", hi: "खेल और गतिविधियाँ", desc: "Games, music, art, dance and annual functions along with studies.", descHi: "पढ़ाई के साथ खेल, संगीत, आर्ट, डांस और वार्षिक कार्यक्रम।" },
      { en: "School transport", hi: "स्कूल बस / ट्रांसपोर्ट", desc: "Bus or van pick-up and drop on fixed routes — ask for your area.", descHi: "तय रूट पर बस या वैन से लाना-ले जाना — अपने इलाक़े के लिए पूछें।" },
      { en: "Computer & science labs", hi: "कंप्यूटर और साइंस लैब", desc: "Hands-on learning with computers and lab work.", descHi: "कंप्यूटर और लैब में प्रैक्टिकल सीख।" },
      { en: "Parent-teacher meetings", hi: "पेरेंट-टीचर मीटिंग", desc: "Regular meetings and updates on your child's progress.", descHi: "बच्चे की प्रगति पर नियमित मीटिंग और अपडेट।" },
      { en: "Admission help", hi: "एडमिशन में मदद", desc: "Guidance on forms, documents and the right class for your child.", descHi: "फ़ॉर्म, दस्तावेज़ और बच्चे के लिए सही कक्षा — पूरी जानकारी।" },
    ],
    whyUs: [
      { en: "Caring, qualified teachers", hi: "योग्य और स्नेही शिक्षक" },
      { en: "Safe, clean campus", hi: "सुरक्षित, साफ़ कैंपस" },
      { en: "Studies with sports and activities", hi: "पढ़ाई के साथ खेल और गतिविधियाँ" },
      { en: "Attention to every child", hi: "हर बच्चे पर ध्यान" },
      { en: "Parents kept informed", hi: "अभिभावकों को पूरी जानकारी" },
      { en: "Transport on fixed routes", hi: "तय रूट पर ट्रांसपोर्ट" },
      { en: "Fair, transparent fees", hi: "साफ़, पारदर्शी फ़ीस" },
    ],
    steps: [
      { en: "Enquire on WhatsApp", hi: "WhatsApp पर पूछें", desc: "Tell us the child's age and the class you want.", descHi: "बच्चे की उम्र और कौन सी कक्षा चाहिए, बताएँ।" },
      { en: "Visit the school", hi: "स्कूल देखने आएँ", desc: "See the classrooms, meet the teachers and ask your questions.", descHi: "कक्षाएँ देखें, शिक्षकों से मिलें और अपने सवाल पूछें।" },
      { en: "Fill the admission form", hi: "एडमिशन फ़ॉर्म भरें", desc: "Submit the form with the documents; a short interaction if needed.", descHi: "दस्तावेज़ों के साथ फ़ॉर्म जमा करें; ज़रूरत हो तो छोटी बातचीत।" },
      { en: "Welcome to school", hi: "स्कूल में स्वागत", desc: "Fees, books and uniform details are shared; classes begin.", descHi: "फ़ीस, किताबें और यूनिफ़ॉर्म की जानकारी मिलती है; कक्षाएँ शुरू।" },
    ],
    faq: [
      { q: "Which classes do you have?", qHi: "कौन-कौन सी कक्षाएँ हैं?", a: "See the classes on this page; message us on WhatsApp for the class you need.", aHi: "इसी पेज पर कक्षाएँ देखें; जो कक्षा चाहिए, WhatsApp पर पूछ लें।" },
      { q: "When do admissions open?", qHi: "एडमिशन कब शुरू होते हैं?", a: "Admissions usually open before the new session; message us and we will tell you the dates and seats.", aHi: "एडमिशन आमतौर पर नए सत्र से पहले शुरू होते हैं; मैसेज करें, तारीख़ और सीट बता देंगे।" },
      { q: "What documents are needed for admission?", qHi: "एडमिशन के लिए कौन से दस्तावेज़ चाहिए?", a: "Birth certificate, previous report card or transfer certificate, Aadhaar and photos; we confirm the full list.", aHi: "जन्म प्रमाणपत्र, पिछली रिपोर्ट कार्ड या TC, आधार और फ़ोटो; पूरी लिस्ट हम बता देंगे।" },
      { q: "Is there school transport?", qHi: "स्कूल बस है?", a: "Yes, on fixed routes; message us your area to check.", aHi: "हाँ, तय रूट पर; अपना इलाक़ा भेजकर पूछ लें।" },
      { q: "What is the fee?", qHi: "फ़ीस कितनी है?", a: "Fees depend on the class; message us and we will share the structure and what it includes.", aHi: "फ़ीस कक्षा पर निर्भर है; मैसेज करें, पूरा स्ट्रक्चर और उसमें क्या शामिल है बताएँगे।" },
      { q: "Which board and medium?", qHi: "कौन सा बोर्ड और माध्यम?", a: "See this page or ask us — we tell you the board, medium and syllabus followed.", aHi: "इसी पेज पर देखें या पूछ लें — बोर्ड, माध्यम और सिलेबस बता देंगे।" },
      { q: "Can I visit before admission?", qHi: "एडमिशन से पहले स्कूल देख सकते हैं?", a: "Yes, you are welcome; message us to fix a time and we will show you around.", aHi: "हाँ, ज़रूर; समय तय करने के लिए मैसेज करें, हम पूरा स्कूल दिखाएँगे।" },
    ],
    generic: ["connect with us", "explore options", "quality education", "bright future", "best school"],
  },

  playschool: {
    explain: [
      "age groups and programmes (play group, nursery, LKG, UKG; daycare if any) and the timings",
      "how the day goes — play-based learning, activities, rhymes, art, outdoor play, meals or snack time",
      "safety and care — child-safe campus, CCTV, hygiene, trained caretakers, small groups",
      "admission: age for each class, documents, when admissions open",
    ],
    services: [
      { en: "Play group & nursery", hi: "प्ले ग्रुप और नर्सरी", desc: "The first school days — learning through play, songs and stories.", descHi: "स्कूल के पहले दिन — खेल, गाने और कहानियों से सीख।" },
      { en: "LKG & UKG", hi: "LKG और UKG", desc: "Letters, numbers, reading and writing readiness, in a fun way.", descHi: "अक्षर, गिनती, पढ़ने-लिखने की तैयारी — मज़े के साथ।" },
      { en: "Activities & art", hi: "गतिविधियाँ और आर्ट", desc: "Drawing, craft, music, dance and festival celebrations.", descHi: "ड्रॉइंग, क्राफ़्ट, म्यूज़िक, डांस और त्योहारों की धूम।" },
      { en: "Outdoor play", hi: "खेल का मैदान", desc: "Safe play area and games every day for growing bodies.", descHi: "सुरक्षित खेल क्षेत्र और रोज़ खेल, बढ़ते बच्चों के लिए।" },
      { en: "Daycare", hi: "डेकेयर", desc: "Caring supervision beyond school hours for working parents.", descHi: "नौकरी करने वाले माता-पिता के लिए स्कूल के बाद भी देखभाल।" },
      { en: "Parent updates", hi: "अभिभावकों को अपडेट", desc: "Regular updates and meetings about your child's progress.", descHi: "बच्चे की प्रगति पर नियमित अपडेट और मीटिंग।" },
      { en: "Admission help", hi: "एडमिशन में मदद", desc: "The right class for your child's age, forms and documents explained.", descHi: "उम्र के हिसाब से सही कक्षा, फ़ॉर्म और दस्तावेज़ की पूरी जानकारी।" },
    ],
    whyUs: [
      { en: "Child-safe, clean campus", hi: "बच्चों के लिए सुरक्षित, साफ़ कैंपस" },
      { en: "Trained, caring teachers", hi: "प्रशिक्षित, स्नेही शिक्षिकाएँ" },
      { en: "Learning through play", hi: "खेल-खेल में सीख" },
      { en: "Small groups, every child seen", hi: "छोटे ग्रुप, हर बच्चे पर ध्यान" },
      { en: "Parents kept informed", hi: "अभिभावकों को पूरी जानकारी" },
      { en: "Hygienic, happy environment", hi: "साफ़-सुथरा, खुशनुमा माहौल" },
    ],
    steps: [
      { en: "Enquire on WhatsApp", hi: "WhatsApp पर पूछें", desc: "Tell us your child's age; we suggest the right class.", descHi: "बच्चे की उम्र बताएँ; हम सही कक्षा सुझाएँगे।" },
      { en: "Visit with your child", hi: "बच्चे के साथ आएँ", desc: "See the classrooms and play area, meet the teachers.", descHi: "कक्षाएँ और खेल क्षेत्र देखें, शिक्षिकाओं से मिलें।" },
      { en: "Fill the admission form", hi: "एडमिशन फ़ॉर्म भरें", desc: "Form and documents; the first day is fixed.", descHi: "फ़ॉर्म और दस्तावेज़; पहला दिन तय।" },
      { en: "A happy first day", hi: "खुशनुमा पहला दिन", desc: "A gentle settling-in; you get updates from day one.", descHi: "धीरे-धीरे घुलना-मिलना; पहले दिन से अपडेट मिलते हैं।" },
    ],
    faq: [
      { q: "From what age do you take children?", qHi: "कितनी उम्र से बच्चे लेते हैं?", a: "See the age for each class on this page; message us your child's age and we will guide you.", aHi: "हर कक्षा की उम्र इसी पेज पर है; बच्चे की उम्र भेजें, हम बता देंगे।" },
      { q: "What are the timings?", qHi: "समय क्या है?", a: "The timings are on this page; daycare hours, if any, are longer — ask us.", aHi: "समय इसी पेज पर है; डेकेयर का समय ज़्यादा होता है — पूछ लें।" },
      { q: "Is the campus safe?", qHi: "कैंपस सुरक्षित है?", a: "Yes — child-safe furniture, supervision at all times and hygiene are taken care of; come and see.", aHi: "हाँ — बच्चों के लिए सुरक्षित फ़र्नीचर, हर समय निगरानी और सफ़ाई; आकर देखें।" },
      { q: "What documents are needed?", qHi: "कौन से दस्तावेज़ चाहिए?", a: "Birth certificate, Aadhaar and photos of the child and parents; we confirm the full list.", aHi: "जन्म प्रमाणपत्र, आधार और बच्चे-अभिभावक की फ़ोटो; पूरी लिस्ट हम बता देंगे।" },
      { q: "What is the fee?", qHi: "फ़ीस कितनी है?", a: "Fees depend on the programme; message us and we will share the structure and what it includes.", aHi: "फ़ीस प्रोग्राम पर निर्भर है; मैसेज करें, पूरा स्ट्रक्चर और उसमें क्या शामिल है बताएँगे।" },
      { q: "Is there daycare after school?", qHi: "स्कूल के बाद डेकेयर है?", a: "Ask us — where we have it, the hours and meals are explained on enquiry.", aHi: "पूछ लें — जहाँ है, समय और खाने की जानकारी पूछने पर मिलती है।" },
    ],
    generic: ["connect with us", "explore options", "quality education", "bright future", "best play school"],
  },
  coaching: {
    explain: [
      "which classes, subjects and exams are taught (school subjects, board exams, competitive exams, English)",
      "how classes run — batch size, timings, tests, doubt sessions, study material",
      "who teaches and how progress is shared with parents",
      "how to join: free demo class, enquiry on WhatsApp",
    ],
    services: [
      { en: "School subject tuition", hi: "स्कूल विषयों की ट्यूशन", desc: "Maths, science, English and other subjects for school classes.", descHi: "स्कूल की कक्षाओं के लिए गणित, विज्ञान, अंग्रेज़ी और बाक़ी विषय।" },
      { en: "Board exam preparation", hi: "बोर्ड परीक्षा की तैयारी", desc: "Syllabus completion, revision and practice papers for board exams.", descHi: "बोर्ड परीक्षा के लिए सिलेबस पूरा, रिवीज़न और प्रैक्टिस पेपर।" },
      { en: "Competitive exam coaching", hi: "प्रतियोगी परीक्षा कोचिंग", desc: "Entrance and government exam preparation with regular mock tests.", descHi: "एंट्रेंस और सरकारी परीक्षाओं की तैयारी, नियमित मॉक टेस्ट के साथ।" },
      { en: "Doubt-clearing sessions", hi: "डाउट क्लास", desc: "Separate time to ask questions and clear what was not understood.", descHi: "सवाल पूछने और जो समझ न आया उसे साफ़ करने का अलग समय।" },
      { en: "Weekly tests & reports", hi: "साप्ताहिक टेस्ट और रिपोर्ट", desc: "Regular tests with marks and feedback shared with parents.", descHi: "नियमित टेस्ट, नंबर और फ़ीडबैक अभिभावकों तक।" },
      { en: "Study material & notes", hi: "स्टडी मटीरियल और नोट्स", desc: "Notes, worksheets and previous papers given with the course.", descHi: "कोर्स के साथ नोट्स, वर्कशीट और पुराने पेपर।" },
      { en: "Online & home tuition", hi: "ऑनलाइन और होम ट्यूशन", desc: "Classes online or at home for students who cannot come — ask us.", descHi: "जो आ नहीं सकते, उनके लिए ऑनलाइन या घर पर क्लास — पूछ लें।" },
    ],
    whyUs: [
      { en: "Small batches, personal attention", hi: "छोटे बैच, हर छात्र पर ध्यान" },
      { en: "Experienced, patient teachers", hi: "अनुभवी, धैर्य वाले शिक्षक" },
      { en: "Concepts first, then practice", hi: "पहले कॉन्सेप्ट, फिर प्रैक्टिस" },
      { en: "Regular tests and feedback", hi: "नियमित टेस्ट और फ़ीडबैक" },
      { en: "Doubts cleared the same day", hi: "डाउट उसी दिन साफ़" },
      { en: "Parents updated on progress", hi: "अभिभावकों को प्रगति की जानकारी" },
      { en: "Free demo class", hi: "फ़्री डेमो क्लास" },
    ],
    steps: [
      { en: "Message your need", hi: "ज़रूरत बताएँ", desc: "Class, subject or exam, and the timing that suits you.", descHi: "कक्षा, विषय या परीक्षा, और कौन सा समय ठीक रहेगा।" },
      { en: "Attend a demo class", hi: "डेमो क्लास लें", desc: "Sit in a class, meet the teacher and see how we teach.", descHi: "एक क्लास में बैठें, टीचर से मिलें और पढ़ाने का तरीक़ा देखें।" },
      { en: "Join a batch", hi: "बैच जॉइन करें", desc: "Pick the batch and timing; fees and material are explained.", descHi: "बैच और समय चुनें; फ़ीस और मटीरियल की जानकारी मिलती है।" },
      { en: "Learn, test, improve", hi: "पढ़ें, टेस्ट दें, सुधारें", desc: "Regular classes, tests and reports till the exam.", descHi: "परीक्षा तक नियमित क्लास, टेस्ट और रिपोर्ट।" },
    ],
    faq: [
      { q: "Which classes and subjects do you teach?", qHi: "कौन सी कक्षाएँ और विषय पढ़ाते हैं?", a: "See the list on this page; for a subject or exam not listed, message us on WhatsApp.", aHi: "इसी पेज पर लिस्ट देखें; कोई विषय या परीक्षा न दिखे तो WhatsApp पर पूछ लें।" },
      { q: "Is there a demo class?", qHi: "डेमो क्लास मिलती है?", a: "Yes, attend a class before you join; message us to fix a time.", aHi: "हाँ, जॉइन करने से पहले एक क्लास में बैठें; समय तय करने के लिए मैसेज करें।" },
      { q: "How many students are in a batch?", qHi: "एक बैच में कितने छात्र होते हैं?", a: "Batches are kept small so every student gets attention; ask us for the batch you want.", aHi: "बैच छोटे रखे जाते हैं ताकि हर छात्र पर ध्यान जाए; अपने बैच के लिए पूछ लें।" },
      { q: "What are the batch timings?", qHi: "बैच का समय क्या है?", a: "Morning and evening batches for school and working students; message us for the current timings.", aHi: "स्कूल और नौकरी वाले छात्रों के लिए सुबह और शाम के बैच; मौजूदा समय के लिए मैसेज करें।" },
      { q: "What is the fee?", qHi: "फ़ीस कितनी है?", a: "Fees depend on the class and subjects; message us and we will share them, with any instalment option.", aHi: "फ़ीस कक्षा और विषयों पर निर्भर है; मैसेज करें, किस्त का विकल्प भी बता देंगे।" },
      { q: "Do you give notes and test papers?", qHi: "नोट्स और टेस्ट पेपर देते हैं?", a: "Yes, notes, worksheets and practice papers are part of the course.", aHi: "हाँ, नोट्स, वर्कशीट और प्रैक्टिस पेपर कोर्स का हिस्सा हैं।" },
      { q: "How will I know my child is improving?", qHi: "बच्चे की प्रगति कैसे पता चलेगी?", a: "Regular test reports are shared with parents, and you can speak to the teacher any time.", aHi: "नियमित टेस्ट रिपोर्ट अभिभावकों को भेजी जाती है, और आप टीचर से कभी भी बात कर सकते हैं।" },
    ],
    generic: ["connect with us", "explore options", "quality education", "guaranteed success", "best coaching", "bright future"],
  },

  college: {
    explain: [
      "courses and streams offered (arts, science, commerce, professional) and the affiliating university or board",
      "the campus — classrooms, labs, library, hostel, canteen, sports",
      "admission process, eligibility and documents",
      "placements, internships and activities that help students after the course",
    ],
    services: [
      { en: "Undergraduate courses", hi: "स्नातक (UG) कोर्स", desc: "Degree courses in the streams the college offers.", descHi: "कॉलेज की स्ट्रीम में डिग्री कोर्स।" },
      { en: "Postgraduate & diploma courses", hi: "PG और डिप्लोमा कोर्स", desc: "Advanced and short courses after graduation — ask what is offered.", descHi: "ग्रेजुएशन के बाद के एडवांस और शॉर्ट कोर्स — पूछ लें क्या-क्या है।" },
      { en: "Library & labs", hi: "लाइब्रेरी और लैब", desc: "Books, journals, computer and subject labs for regular use.", descHi: "किताबें, जर्नल, कंप्यूटर और विषय की लैब, रोज़ इस्तेमाल के लिए।" },
      { en: "Hostel & canteen", hi: "हॉस्टल और कैंटीन", desc: "Stay and meals for students from outside the city — ask about seats.", descHi: "बाहर के छात्रों के लिए रहना और खाना — सीट के बारे में पूछें।" },
      { en: "Placement & internship cell", hi: "प्लेसमेंट और इंटर्नशिप सेल", desc: "Help with internships, interviews and campus drives.", descHi: "इंटर्नशिप, इंटरव्यू और कैंपस ड्राइव में मदद।" },
      { en: "Scholarship guidance", hi: "स्कॉलरशिप में मदद", desc: "Information and help with government and other scholarship forms.", descHi: "सरकारी और अन्य स्कॉलरशिप के फ़ॉर्म की जानकारी और मदद।" },
      { en: "Sports, NSS & cultural activities", hi: "खेल, NSS और सांस्कृतिक गतिविधियाँ", desc: "Clubs, fests, sports and social work along with studies.", descHi: "पढ़ाई के साथ क्लब, फ़ेस्ट, खेल और समाज सेवा।" },
    ],
    whyUs: [
      { en: "Recognised courses and degrees", hi: "मान्यता प्राप्त कोर्स और डिग्री" },
      { en: "Qualified, experienced faculty", hi: "योग्य, अनुभवी फ़ैकल्टी" },
      { en: "Library, labs and campus facilities", hi: "लाइब्रेरी, लैब और कैंपस सुविधाएँ" },
      { en: "Placement and internship support", hi: "प्लेसमेंट और इंटर्नशिप सहयोग" },
      { en: "Scholarship help for students", hi: "छात्रों को स्कॉलरशिप में मदद" },
      { en: "Activities beyond the classroom", hi: "कक्षा के बाहर भी गतिविधियाँ" },
      { en: "Transparent admission process", hi: "पारदर्शी एडमिशन प्रक्रिया" },
    ],
    steps: [
      { en: "Check the courses", hi: "कोर्स देखें", desc: "See the courses and eligibility here or message us.", descHi: "कोर्स और पात्रता यहाँ देखें या मैसेज करें।" },
      { en: "Apply for admission", hi: "एडमिशन के लिए आवेदन करें", desc: "Fill the form with your marksheets and documents.", descHi: "मार्कशीट और दस्तावेज़ों के साथ फ़ॉर्म भरें।" },
      { en: "Counselling & confirmation", hi: "काउंसलिंग और कन्फ़र्मेशन", desc: "Merit list or counselling as per the rules; pay fees to confirm the seat.", descHi: "नियमों के अनुसार मेरिट लिस्ट या काउंसलिंग; फ़ीस देकर सीट पक्की करें।" },
      { en: "Classes begin", hi: "कक्षाएँ शुरू", desc: "Orientation, timetable and ID card on joining.", descHi: "जॉइन करने पर ओरिएंटेशन, टाइमटेबल और आईडी कार्ड।" },
    ],
    faq: [
      { q: "Which courses do you offer?", qHi: "कौन से कोर्स हैं?", a: "See the courses on this page; message us for a course not listed.", aHi: "इसी पेज पर कोर्स देखें; जो न दिखे उसके लिए मैसेज करें।" },
      { q: "Is the college recognised / affiliated?", qHi: "कॉलेज मान्यता प्राप्त है?", a: "Ask us — we tell you the affiliating university or board and the recognition of each course.", aHi: "पूछ लें — हम संबद्ध यूनिवर्सिटी या बोर्ड और हर कोर्स की मान्यता बता देंगे।" },
      { q: "What is the eligibility for admission?", qHi: "एडमिशन की पात्रता क्या है?", a: "It depends on the course — usually the previous qualification with the required marks; message us the course you want.", aHi: "कोर्स पर निर्भर है — आमतौर पर पिछली योग्यता और ज़रूरी अंक; जो कोर्स चाहिए, मैसेज करें।" },
      { q: "Is there a hostel?", qHi: "हॉस्टल है?", a: "Ask us about hostel seats and nearby options for students from outside the city.", aHi: "बाहर के छात्रों के लिए हॉस्टल सीट और आसपास के विकल्पों के बारे में पूछ लें।" },
      { q: "Do you help with placements?", qHi: "प्लेसमेंट में मदद करते हैं?", a: "Yes, the placement cell helps with internships, interview preparation and campus drives; the result depends on the student too.", aHi: "हाँ, प्लेसमेंट सेल इंटर्नशिप, इंटरव्यू की तैयारी और कैंपस ड्राइव में मदद करता है; नतीजा छात्र की मेहनत पर भी निर्भर है।" },
      { q: "What are the fees?", qHi: "फ़ीस कितनी है?", a: "Fees depend on the course; message us for the structure and scholarship options.", aHi: "फ़ीस कोर्स पर निर्भर है; स्ट्रक्चर और स्कॉलरशिप के विकल्पों के लिए मैसेज करें।" },
      { q: "Can I get a scholarship?", qHi: "स्कॉलरशिप मिल सकती है?", a: "Government and other scholarships apply to eligible students; we help with the forms.", aHi: "पात्र छात्रों को सरकारी और अन्य स्कॉलरशिप मिल सकती है; फ़ॉर्म में हम मदद करते हैं।" },
    ],
    generic: ["connect with us", "explore options", "quality education", "bright future", "best college", "top placements"],
  },

  computer: {
    explain: [
      "courses taught — basic computer, Tally, DCA / PGDCA, typing, graphic design, coding, spoken English",
      "practical learning on the centre's own computers, certificate on completion",
      "who it is for — students, job seekers, shop owners, housewives; flexible batch timings",
      "how to join: demo class, enquiry on WhatsApp",
    ],
    services: [
      { en: "Basic computer course", hi: "बेसिक कंप्यूटर कोर्स", desc: "Computer basics, MS Office, internet and email for beginners.", descHi: "शुरू करने वालों के लिए कंप्यूटर की बुनियाद, MS Office, इंटरनेट और ईमेल।" },
      { en: "Tally & accounting", hi: "Tally और अकाउंटिंग", desc: "Tally with GST, billing and bookkeeping for jobs and shops.", descHi: "नौकरी और दुकान के लिए GST के साथ Tally, बिलिंग और बहीखाता।" },
      { en: "DCA / PGDCA & certificate courses", hi: "DCA / PGDCA और सर्टिफ़िकेट कोर्स", desc: "Diploma courses with a certificate on completion.", descHi: "पूरा करने पर सर्टिफ़िकेट के साथ डिप्लोमा कोर्स।" },
      { en: "Typing — Hindi & English", hi: "टाइपिंग — हिंदी और अंग्रेज़ी", desc: "Speed typing practice for government and office jobs.", descHi: "सरकारी और ऑफ़िस की नौकरी के लिए स्पीड टाइपिंग प्रैक्टिस।" },
      { en: "Graphic design & video editing", hi: "ग्राफ़िक डिज़ाइन और वीडियो एडिटिंग", desc: "Photoshop, CorelDRAW, Canva and editing for work and social media.", descHi: "काम और सोशल मीडिया के लिए Photoshop, CorelDRAW, Canva और एडिटिंग।" },
      { en: "Coding & web basics", hi: "कोडिंग और वेब की शुरुआत", desc: "Programming, HTML and website basics for students.", descHi: "छात्रों के लिए प्रोग्रामिंग, HTML और वेबसाइट की बुनियाद।" },
      { en: "Spoken English & personality", hi: "स्पोकन इंग्लिश और पर्सनैलिटी", desc: "Confidence in English for interviews and work.", descHi: "इंटरव्यू और काम के लिए अंग्रेज़ी में आत्मविश्वास।" },
    ],
    whyUs: [
      { en: "One computer per student", hi: "हर छात्र को अलग कंप्यूटर" },
      { en: "Practical, hands-on learning", hi: "प्रैक्टिकल, हाथ से सीखना" },
      { en: "Certificate on completion", hi: "कोर्स पूरा होने पर सर्टिफ़िकेट" },
      { en: "Flexible batch timings", hi: "अपनी सुविधा का बैच समय" },
      { en: "Patient trainers for beginners", hi: "नए लोगों के लिए धैर्य वाले ट्रेनर" },
      { en: "Job-oriented courses", hi: "नौकरी के काम के कोर्स" },
      { en: "Free demo class", hi: "फ़्री डेमो क्लास" },
    ],
    steps: [
      { en: "Tell us your goal", hi: "अपना लक्ष्य बताएँ", desc: "Job, business, exam or just learning — message us on WhatsApp.", descHi: "नौकरी, बिज़नेस, परीक्षा या बस सीखना — WhatsApp पर बताएँ।" },
      { en: "Take a demo class", hi: "डेमो क्लास लें", desc: "Sit at a computer, meet the trainer and see the course.", descHi: "कंप्यूटर पर बैठें, ट्रेनर से मिलें और कोर्स देखें।" },
      { en: "Join a batch", hi: "बैच जॉइन करें", desc: "Choose the course and timing; fees are explained up front.", descHi: "कोर्स और समय चुनें; फ़ीस पहले ही बता दी जाती है।" },
      { en: "Learn and get certified", hi: "सीखें और सर्टिफ़िकेट पाएँ", desc: "Daily practice, a test at the end and your certificate.", descHi: "रोज़ प्रैक्टिस, अंत में टेस्ट और आपका सर्टिफ़िकेट।" },
    ],
    faq: [
      { q: "I have never used a computer — can I join?", qHi: "कभी कंप्यूटर नहीं चलाया — जॉइन कर सकते हैं?", a: "Yes, the basic course starts from zero; many students begin that way.", aHi: "हाँ, बेसिक कोर्स शून्य से शुरू होता है; बहुत से छात्र ऐसे ही शुरू करते हैं।" },
      { q: "Do I get a certificate?", qHi: "सर्टिफ़िकेट मिलेगा?", a: "Yes, on completing the course and its test; ask us which courses carry which certificate.", aHi: "हाँ, कोर्स और उसका टेस्ट पूरा करने पर; कौन से कोर्स में कौन सा सर्टिफ़िकेट, पूछ लें।" },
      { q: "What are the batch timings?", qHi: "बैच का समय क्या है?", a: "Morning, afternoon and evening batches; message us for a timing that suits you.", aHi: "सुबह, दोपहर और शाम के बैच; अपने समय के लिए मैसेज करें।" },
      { q: "How long is the course?", qHi: "कोर्स कितने समय का है?", a: "It depends on the course; message us the course name and we will tell you the duration and fee.", aHi: "कोर्स पर निर्भर है; कोर्स का नाम भेजें, अवधि और फ़ीस बता देंगे।" },
      { q: "Do I need my own laptop?", qHi: "अपना लैपटॉप चाहिए?", a: "No, you practise on the centre's computers; a laptop at home helps but is not needed.", aHi: "नहीं, सेंटर के कंप्यूटर पर प्रैक्टिस होती है; घर पर लैपटॉप हो तो अच्छा, ज़रूरी नहीं।" },
      { q: "Does the course help in getting a job?", qHi: "कोर्स से नौकरी मिलती है?", a: "The courses teach skills offices and shops ask for; we guide on interviews, but the job depends on you.", aHi: "कोर्स वही स्किल सिखाते हैं जो ऑफ़िस और दुकानें माँगती हैं; इंटरव्यू में हम मार्गदर्शन करते हैं, नौकरी आपकी मेहनत पर निर्भर है।" },
      { q: "Can I pay in instalments?", qHi: "फ़ीस किस्तों में दे सकते हैं?", a: "Ask us — for longer courses the fee can usually be paid in instalments.", aHi: "पूछ लें — लंबे कोर्स में फ़ीस आमतौर पर किस्तों में दी जा सकती है।" },
    ],
    generic: ["connect with us", "explore options", "quality education", "job guarantee", "best institute"],
  },

  teacher: {
    explain: [
      "subjects, classes or skills taught (school subjects, a language, a competitive exam, a professional skill)",
      "how you teach — home tuition, your own classes, online; one-to-one or small groups",
      "your background — qualification, teaching experience, where you have taught",
      "how to start: a trial class, message on WhatsApp",
    ],
    services: [
      { en: "Home tuition", hi: "होम ट्यूशन", desc: "Classes at the student's home for school subjects.", descHi: "स्कूल के विषयों के लिए छात्र के घर पर क्लास।" },
      { en: "Online classes", hi: "ऑनलाइन क्लास", desc: "Live one-to-one or group classes on video call.", descHi: "वीडियो कॉल पर लाइव, अकेले या ग्रुप में क्लास।" },
      { en: "Exam preparation", hi: "परीक्षा की तैयारी", desc: "Focused revision and practice before board or entrance exams.", descHi: "बोर्ड या एंट्रेंस परीक्षा से पहले फ़ोकस्ड रिवीज़न और प्रैक्टिस।" },
      { en: "Group classes", hi: "ग्रुप क्लास", desc: "Small groups of students of the same class or level.", descHi: "एक ही कक्षा या स्तर के छात्रों के छोटे ग्रुप।" },
      { en: "Skill & language training", hi: "स्किल और भाषा प्रशिक्षण", desc: "Spoken English, a language or a professional skill, as per your need.", descHi: "स्पोकन इंग्लिश, कोई भाषा या प्रोफ़ेशनल स्किल, आपकी ज़रूरत के हिसाब से।" },
      { en: "Corporate & workshop training", hi: "कॉर्पोरेट और वर्कशॉप ट्रेनिंग", desc: "Sessions for offices, schools and institutes on request.", descHi: "ऑफ़िस, स्कूल और संस्थानों के लिए सेशन, माँग पर।" },
      { en: "Progress reports for parents", hi: "अभिभावकों को प्रगति रिपोर्ट", desc: "Regular feedback on how the student is doing.", descHi: "छात्र कैसा कर रहा है, इस पर नियमित फ़ीडबैक।" },
    ],
    whyUs: [
      { en: "Qualified, experienced teacher", hi: "योग्य, अनुभवी शिक्षक" },
      { en: "Teaches at the student's pace", hi: "छात्र की गति से पढ़ाई" },
      { en: "Concepts made simple", hi: "कॉन्सेप्ट आसान भाषा में" },
      { en: "Regular practice and tests", hi: "नियमित प्रैक्टिस और टेस्ट" },
      { en: "Patient with weak students", hi: "कमज़ोर छात्रों के साथ धैर्य" },
      { en: "Flexible timings", hi: "सुविधा के अनुसार समय" },
      { en: "Trial class before joining", hi: "जॉइन करने से पहले ट्रायल क्लास" },
    ],
    steps: [
      { en: "Message your need", hi: "ज़रूरत बताएँ", desc: "Class, subject and whether you want home, online or group.", descHi: "कक्षा, विषय और घर, ऑनलाइन या ग्रुप — क्या चाहिए।" },
      { en: "A trial class", hi: "ट्रायल क्लास", desc: "One class to see the teaching style and comfort level.", descHi: "पढ़ाने का तरीक़ा और सहजता देखने के लिए एक क्लास।" },
      { en: "Fix days and timing", hi: "दिन और समय तय करें", desc: "Agree the schedule and fees; classes begin.", descHi: "शेड्यूल और फ़ीस तय करें; क्लास शुरू।" },
      { en: "Regular classes and feedback", hi: "नियमित क्लास और फ़ीडबैक", desc: "Steady lessons, tests and updates to parents.", descHi: "लगातार पढ़ाई, टेस्ट और अभिभावकों को अपडेट।" },
    ],
    faq: [
      { q: "Which subjects and classes do you teach?", qHi: "कौन से विषय और कक्षाएँ पढ़ाते हैं?", a: "See this page for the subjects and classes; for anything else, message on WhatsApp.", aHi: "विषय और कक्षाएँ इसी पेज पर देखें; बाक़ी के लिए WhatsApp पर पूछ लें।" },
      { q: "Do you come home or teach online?", qHi: "घर आते हैं या ऑनलाइन पढ़ाते हैं?", a: "Both are possible depending on your area and timing; message us to check.", aHi: "इलाक़े और समय के हिसाब से दोनों संभव हैं; मैसेज करके पूछ लें।" },
      { q: "Is there a trial class?", qHi: "ट्रायल क्लास मिलती है?", a: "Yes, one class before you decide; message us to fix a time.", aHi: "हाँ, तय करने से पहले एक क्लास; समय के लिए मैसेज करें।" },
      { q: "One-to-one or group?", qHi: "अकेले पढ़ाते हैं या ग्रुप में?", a: "Both — one-to-one for focused help, small groups for regular study; choose what suits the student.", aHi: "दोनों — फ़ोकस्ड मदद के लिए अकेले, नियमित पढ़ाई के लिए छोटे ग्रुप; जो छात्र को ठीक लगे।" },
      { q: "What is the fee?", qHi: "फ़ीस कितनी है?", a: "It depends on the class, subject and number of days; message us and we will tell you.", aHi: "कक्षा, विषय और दिनों पर निर्भर है; मैसेज करें, बता देंगे।" },
      { q: "How do you keep parents informed?", qHi: "अभिभावकों को कैसे बताते हैं?", a: "Regular updates on WhatsApp and a word after tests; you can call any time.", aHi: "WhatsApp पर नियमित अपडेट और टेस्ट के बाद बात; आप कभी भी कॉल कर सकते हैं।" },
      { q: "Can you help a weak student catch up?", qHi: "कमज़ोर छात्र को संभाल सकते हैं?", a: "Yes, we start from where the student is and build up slowly, with extra practice.", aHi: "हाँ, छात्र जहाँ है वहीं से शुरू करके धीरे-धीरे आगे बढ़ते हैं, अतिरिक्त प्रैक्टिस के साथ।" },
    ],
    generic: ["connect with us", "explore options", "quality education", "best teacher", "guaranteed marks"],
  },

  dance: {
    explain: [
      "what is taught — dance styles, instruments, vocal music, drawing and painting; for which ages",
      "batches for kids and adults, beginners to advanced; hobby and exam / certification",
      "performances, annual shows, competitions and wedding choreography",
      "how to join: trial class, message on WhatsApp",
    ],
    services: [
      { en: "Dance classes", hi: "डांस क्लास", desc: "Classical, Bollywood, folk and western styles for kids and adults.", descHi: "बच्चों और बड़ों के लिए क्लासिकल, बॉलीवुड, लोक और वेस्टर्न डांस।" },
      { en: "Music — vocal & instruments", hi: "संगीत — गायन और वाद्य", desc: "Singing, harmonium, keyboard, guitar, tabla and more.", descHi: "गायन, हारमोनियम, कीबोर्ड, गिटार, तबला और भी।" },
      { en: "Art & craft", hi: "आर्ट और क्राफ़्ट", desc: "Drawing, painting and craft for children and hobby learners.", descHi: "बच्चों और शौक़ से सीखने वालों के लिए ड्रॉइंग, पेंटिंग और क्राफ़्ट।" },
      { en: "Kids' batches", hi: "बच्चों के बैच", desc: "Age-wise groups with fun, step-by-step learning.", descHi: "उम्र के हिसाब से ग्रुप, मज़े के साथ धीरे-धीरे सीखना।" },
      { en: "Wedding & event choreography", hi: "शादी और इवेंट कोरियोग्राफ़ी", desc: "Sangeet dances for families and couples, taught in a few sessions.", descHi: "परिवार और जोड़ों के लिए संगीत के डांस, कुछ सेशन में तैयार।" },
      { en: "Exams & certification", hi: "परीक्षा और सर्टिफ़िकेट", desc: "Preparation for recognised music and dance examinations.", descHi: "मान्यता प्राप्त संगीत और डांस परीक्षाओं की तैयारी।" },
      { en: "Stage shows & competitions", hi: "स्टेज शो और प्रतियोगिताएँ", desc: "Annual function, performances and help for competitions.", descHi: "वार्षिक कार्यक्रम, प्रस्तुतियाँ और प्रतियोगिताओं में मदद।" },
    ],
    whyUs: [
      { en: "Trained, passionate teachers", hi: "प्रशिक्षित, जुनूनी शिक्षक" },
      { en: "Batches for every age", hi: "हर उम्र के लिए बैच" },
      { en: "Beginners welcome", hi: "नए सीखने वाले भी आएँ" },
      { en: "Stage experience for students", hi: "छात्रों को स्टेज का अनुभव" },
      { en: "Safe, friendly space for kids", hi: "बच्चों के लिए सुरक्षित, दोस्ताना जगह" },
      { en: "Weekend and evening batches", hi: "वीकेंड और शाम के बैच" },
      { en: "Trial class before joining", hi: "जॉइन करने से पहले ट्रायल क्लास" },
    ],
    steps: [
      { en: "Message us", hi: "मैसेज करें", desc: "Tell us the age and what you want to learn.", descHi: "उम्र और क्या सीखना है, बताएँ।" },
      { en: "Trial class", hi: "ट्रायल क्लास", desc: "Come for one class and see if you enjoy it.", descHi: "एक क्लास में आइए और देखिए मज़ा आता है या नहीं।" },
      { en: "Join a batch", hi: "बैच जॉइन करें", desc: "Pick days and timing; fees explained up front.", descHi: "दिन और समय चुनें; फ़ीस पहले ही बता दी जाती है।" },
      { en: "Learn and perform", hi: "सीखें और स्टेज पर आएँ", desc: "Regular classes, then the stage at our shows.", descHi: "नियमित क्लास, फिर हमारे शो में स्टेज।" },
    ],
    faq: [
      { q: "From what age can a child join?", qHi: "बच्चा किस उम्र से जॉइन कर सकता है?", a: "Young children are welcome in the kids' batch; message us the child's age and we will suggest a batch.", aHi: "छोटे बच्चे किड्स बैच में आ सकते हैं; बच्चे की उम्र भेजें, हम बैच सुझाएँगे।" },
      { q: "Can adults and beginners join?", qHi: "बड़े और नए सीखने वाले जॉइन कर सकते हैं?", a: "Yes, there are separate batches for adults, and beginners start from the basics.", aHi: "हाँ, बड़ों के लिए अलग बैच हैं, और नए लोग बुनियाद से शुरू करते हैं।" },
      { q: "Is there a trial class?", qHi: "ट्रायल क्लास है?", a: "Yes, come for one class before joining; message us to fix a time.", aHi: "हाँ, जॉइन करने से पहले एक क्लास; समय के लिए मैसेज करें।" },
      { q: "What are the batch timings?", qHi: "बैच का समय?", a: "Evening and weekend batches for school and working people; message us for the current schedule.", aHi: "स्कूल और नौकरी वालों के लिए शाम और वीकेंड के बैच; मौजूदा शेड्यूल के लिए मैसेज करें।" },
      { q: "Do you do wedding choreography?", qHi: "शादी की कोरियोग्राफ़ी करते हैं?", a: "Yes, for sangeet and family performances; message us the date and the number of people.", aHi: "हाँ, संगीत और परिवार की प्रस्तुतियों के लिए; तारीख़ और लोगों की संख्या भेजें।" },
      { q: "Do you prepare for exams or certificates?", qHi: "परीक्षा या सर्टिफ़िकेट की तैयारी कराते हैं?", a: "Yes, for recognised music and dance exams; ask us which ones.", aHi: "हाँ, मान्यता प्राप्त संगीत और डांस परीक्षाओं के लिए; कौन सी, पूछ लें।" },
      { q: "What is the fee?", qHi: "फ़ीस कितनी है?", a: "Fees depend on the class and days per week; message us and we will share.", aHi: "फ़ीस क्लास और हफ़्ते के दिनों पर निर्भर है; मैसेज करें, बता देंगे।" },
    ],
    generic: ["connect with us", "explore options", "best academy", "quality training", "bright future"],
  },

  student: {
    explain: [
      "who you are — school / college, class or course, city",
      "what you like — subjects, hobbies, sports, arts",
      "what you are looking for — projects, internships, study groups, competitions",
      "how to reach you — WhatsApp, email, social",
    ],
    services: [
      { en: "Study together", hi: "साथ पढ़ाई", desc: "Group study, notes sharing and exam prep with classmates.", descHi: "सहपाठियों के साथ ग्रुप स्टडी, नोट्स शेयर और परीक्षा की तैयारी।" },
      { en: "Projects & assignments", hi: "प्रोजेक्ट और असाइनमेंट", desc: "Team up for school or college projects and presentations.", descHi: "स्कूल या कॉलेज के प्रोजेक्ट और प्रेज़ेंटेशन में साथ।" },
      { en: "Hobbies & talents", hi: "शौक़ और हुनर", desc: "Art, music, sports, coding or whatever I love doing.", descHi: "आर्ट, संगीत, खेल, कोडिंग या जो भी मुझे पसंद है।" },
      { en: "Competitions & events", hi: "प्रतियोगिताएँ और इवेंट", desc: "Quizzes, debates, sports and fests — happy to join a team.", descHi: "क्विज़, डिबेट, खेल और फ़ेस्ट — टीम में शामिल होने को तैयार।" },
      { en: "Internship & volunteering", hi: "इंटर्नशिप और वॉलंटियरिंग", desc: "Open to internships, part-time work and social work.", descHi: "इंटर्नशिप, पार्ट-टाइम काम और समाज सेवा के लिए तैयार।" },
      { en: "Helping juniors", hi: "जूनियर्स की मदद", desc: "Notes, tips and doubt help for younger students.", descHi: "छोटी कक्षा के छात्रों को नोट्स, टिप्स और डाउट में मदद।" },
    ],
    whyUs: [
      { en: "Curious and keen to learn", hi: "सीखने की ललक" },
      { en: "Reliable team member", hi: "भरोसेमंद टीम साथी" },
      { en: "Sincere about studies", hi: "पढ़ाई में गंभीर" },
      { en: "Loves to help friends", hi: "दोस्तों की मदद को तैयार" },
      { en: "Active in school activities", hi: "स्कूल की गतिविधियों में सक्रिय" },
      { en: "Easy to reach on WhatsApp", hi: "WhatsApp पर आसानी से मिलें" },
    ],
    steps: [
      { en: "Say hi on WhatsApp", hi: "WhatsApp पर hi कहें", desc: "Tell me who you are and what it is about.", descHi: "बताएँ आप कौन हैं और किस बारे में बात करनी है।" },
      { en: "Let's talk", hi: "बात करते हैं", desc: "A quick chat or call about the project, study or event.", descHi: "प्रोजेक्ट, पढ़ाई या इवेंट पर छोटी बात या कॉल।" },
      { en: "Team up", hi: "साथ काम करें", desc: "Fix a time and get started together.", descHi: "समय तय करें और साथ शुरू करें।" },
    ],
    faq: [
      { q: "Which school / college and class are you in?", qHi: "किस स्कूल / कॉलेज और कक्षा में हैं?", a: "It is on this page; message me if you want to know more.", aHi: "इसी पेज पर लिखा है; और जानना हो तो मैसेज करें।" },
      { q: "Can we study together for exams?", qHi: "परीक्षा के लिए साथ पढ़ सकते हैं?", a: "Yes, happy to do group study and share notes; message me the subject.", aHi: "हाँ, ग्रुप स्टडी और नोट्स शेयर करने में ख़ुशी होगी; विषय मैसेज करें।" },
      { q: "Are you open to internships or part-time work?", qHi: "इंटर्नशिप या पार्ट-टाइम काम के लिए तैयार हैं?", a: "Yes, as long as it fits with studies; message me the details.", aHi: "हाँ, अगर पढ़ाई के साथ चल सके; डिटेल मैसेज करें।" },
      { q: "Can you help my child with studies?", qHi: "मेरे बच्चे की पढ़ाई में मदद कर सकते हैं?", a: "Younger students can get help with notes and doubts in my subjects; message me to discuss.", aHi: "अपने विषयों में छोटे छात्रों को नोट्स और डाउट में मदद मिल जाएगी; बात करने के लिए मैसेज करें।" },
      { q: "What are your hobbies?", qHi: "आपके शौक़ क्या हैं?", a: "See the hobbies on this page — always happy to talk about them.", aHi: "शौक़ इसी पेज पर हैं — उन पर बात करने में हमेशा मज़ा आता है।" },
      { q: "How do I contact you?", qHi: "संपर्क कैसे करें?", a: "WhatsApp is the easiest way; the number and links are on this page.", aHi: "WhatsApp सबसे आसान तरीक़ा है; नंबर और लिंक इसी पेज पर हैं।" },
    ],
    generic: ["connect with us", "explore options", "best student", "bright future", "topper"],
  },
};

/** General entry for the Education group — used for any key of this group without its own entry above. */
export const EDUCATION_DEFAULT: TradeData = {
  explain: [
    "what is taught — classes, courses, subjects or skills, and for whom (age / level)",
    "how learning happens — batches, teachers, practice, tests, material",
    "facilities and support — classrooms, online option, certificates, parent updates",
    "how to join: enquiry on WhatsApp, demo or trial class, admission",
  ],
  services: [
    { en: "Classes & courses", hi: "कक्षाएँ और कोर्स", desc: "Regular classes in the subjects and courses we offer.", descHi: "हमारे विषयों और कोर्स में नियमित कक्षाएँ।" },
    { en: "Demo / trial class", hi: "डेमो / ट्रायल क्लास", desc: "Attend a class before you decide to join.", descHi: "जॉइन करने से पहले एक क्लास में बैठें।" },
    { en: "Study material", hi: "स्टडी मटीरियल", desc: "Notes, worksheets and practice papers with the course.", descHi: "कोर्स के साथ नोट्स, वर्कशीट और प्रैक्टिस पेपर।" },
    { en: "Tests & progress reports", hi: "टेस्ट और प्रगति रिपोर्ट", desc: "Regular tests with feedback shared with students and parents.", descHi: "नियमित टेस्ट, फ़ीडबैक छात्रों और अभिभावकों तक।" },
    { en: "Online classes", hi: "ऑनलाइन क्लास", desc: "Live classes for those who cannot come in person — ask us.", descHi: "जो आ नहीं सकते, उनके लिए लाइव ऑनलाइन क्लास — पूछ लें।" },
    { en: "Certificates", hi: "सर्टिफ़िकेट", desc: "A certificate on completing the course, where applicable.", descHi: "कोर्स पूरा होने पर सर्टिफ़िकेट, जहाँ लागू हो।" },
    { en: "Admission & counselling help", hi: "एडमिशन और काउंसलिंग में मदद", desc: "Guidance on the right course, forms and documents.", descHi: "सही कोर्स, फ़ॉर्म और दस्तावेज़ों पर मार्गदर्शन।" },
  ],
  whyUs: [
    { en: "Qualified, caring teachers", hi: "योग्य, स्नेही शिक्षक" },
    { en: "Attention to every learner", hi: "हर सीखने वाले पर ध्यान" },
    { en: "Concepts explained simply", hi: "कॉन्सेप्ट आसान भाषा में" },
    { en: "Regular tests and feedback", hi: "नियमित टेस्ट और फ़ीडबैक" },
    { en: "Clean, safe campus", hi: "साफ़, सुरक्षित कैंपस" },
    { en: "Flexible batch timings", hi: "सुविधा के अनुसार बैच समय" },
    { en: "Enquire on WhatsApp", hi: "WhatsApp पर पूछें" },
  ],
  steps: [
    { en: "Message your need", hi: "ज़रूरत बताएँ", desc: "Class, course or skill, and the age or level of the learner.", descHi: "कक्षा, कोर्स या स्किल, और सीखने वाले की उम्र या स्तर।" },
    { en: "Visit or take a demo", hi: "आएँ या डेमो लें", desc: "See the place, meet the teachers, attend a class.", descHi: "जगह देखें, शिक्षकों से मिलें, एक क्लास में बैठें।" },
    { en: "Admission", hi: "एडमिशन", desc: "Fill the form; fees and timings are explained up front.", descHi: "फ़ॉर्म भरें; फ़ीस और समय पहले ही बता दिया जाता है।" },
    { en: "Learn and grow", hi: "सीखें और आगे बढ़ें", desc: "Regular classes, tests and feedback till the goal.", descHi: "लक्ष्य तक नियमित क्लास, टेस्ट और फ़ीडबैक।" },
  ],
  faq: [
    { q: "What do you teach?", qHi: "क्या-क्या पढ़ाते हैं?", a: "See the classes and courses on this page; message us on WhatsApp for anything else.", aHi: "कक्षाएँ और कोर्स इसी पेज पर देखें; बाक़ी के लिए WhatsApp पर पूछ लें।" },
    { q: "Is there a demo or trial class?", qHi: "डेमो या ट्रायल क्लास है?", a: "Yes, attend a class before joining; message us to fix a time.", aHi: "हाँ, जॉइन करने से पहले एक क्लास; समय के लिए मैसेज करें।" },
    { q: "What are the timings?", qHi: "समय क्या है?", a: "Batches run at different times of the day; message us for one that suits you.", aHi: "दिन में अलग-अलग समय के बैच हैं; अपने लिए ठीक समय के लिए मैसेज करें।" },
    { q: "What is the fee?", qHi: "फ़ीस कितनी है?", a: "Fees depend on the class or course; message us and we will share the details.", aHi: "फ़ीस कक्षा या कोर्स पर निर्भर है; मैसेज करें, पूरी जानकारी देंगे।" },
    { q: "What documents are needed for admission?", qHi: "एडमिशन के लिए कौन से दस्तावेज़ चाहिए?", a: "Usually an ID, photos and the previous marksheet or certificate; we confirm the list.", aHi: "आमतौर पर आईडी, फ़ोटो और पिछली मार्कशीट या सर्टिफ़िकेट; पूरी लिस्ट हम बता देंगे।" },
    { q: "Do you teach online?", qHi: "ऑनलाइन पढ़ाते हैं?", a: "Ask us — online classes are possible for some courses and levels.", aHi: "पूछ लें — कुछ कोर्स और स्तरों में ऑनलाइन क्लास संभव है।" },
    { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, cash or bank transfer at the office; ask us about instalments.", aHi: "ऑफ़िस में UPI, नक़द या बैंक ट्रांसफ़र; किस्तों के बारे में पूछ लें।" },
  ],
  generic: ["connect with us", "explore options", "quality education", "bright future", "best institute", "guaranteed success"],
};
