// Food & hospitality trades: sweets / bakery, restaurant / dhaba, cafe / tea, tiffin / home food, catering, hotel.
// See types.ts for the rules (no numbers, no claims; true of any decent business of the trade).
import type { TradeData } from "./types";

export const FOOD: Record<string, TradeData> = {
  sweets: {
    explain: [
      "what is made and sold (sweets, namkeen, bakery items, gift hampers) and the house specialities",
      "freshness — made in small batches, pure ingredients",
      "orders for weddings, festivals, pooja and corporate gifting, and bulk orders",
      "how to order: walk in, WhatsApp, delivery",
    ],
    services: [
      { en: "Fresh sweets daily", hi: "रोज़ ताज़ी मिठाई", desc: "Traditional sweets made fresh every day, sold by weight or in boxes.", descHi: "रोज़ ताज़ी बनी पारंपरिक मिठाइयाँ, वज़न से या डिब्बों में।" },
      { en: "Namkeen & snacks", hi: "नमकीन और स्नैक्स", desc: "Crisp namkeen, bhujia and savouries for home and travel.", descHi: "घर और सफ़र के लिए कुरकुरी नमकीन, भुजिया और स्नैक्स।" },
      { en: "Festival & gift boxes", hi: "त्योहार और गिफ़्ट बॉक्स", desc: "Assorted boxes and hampers for Diwali, Holi, Rakhi and weddings.", descHi: "दिवाली, होली, राखी और शादी के लिए मिक्स बॉक्स और हैम्पर।" },
      { en: "Bulk & wedding orders", hi: "शादी और थोक ऑर्डर", desc: "Large orders for weddings, pooja and events, packed as you want.", descHi: "शादी, पूजा और आयोजनों के लिए बड़े ऑर्डर, आपकी पसंद की पैकिंग में।" },
      { en: "Corporate gifting", hi: "कॉर्पोरेट गिफ़्टिंग", desc: "Branded or plain gift packs for offices and clients, in any quantity.", descHi: "ऑफ़िस और क्लाइंट के लिए गिफ़्ट पैक, जितनी मात्रा चाहिए।" },
      { en: "Home delivery", hi: "होम डिलीवरी", desc: "Order on WhatsApp and get it delivered in the city.", descHi: "WhatsApp पर ऑर्डर करें, शहर में घर तक डिलीवरी।" },
      { en: "Custom orders", hi: "खास ऑर्डर", desc: "Sugar-free, special sweets or a particular item made on request.", descHi: "शुगर-फ़्री, खास मिठाई या कोई चीज़ ऑर्डर पर बनवाएँ।" },
    ],
    whyUs: [
      { en: "Made fresh, every day", hi: "रोज़ ताज़ा बनता है" },
      { en: "Pure ghee and clean ingredients", hi: "शुद्ध घी, साफ़ सामग्री" },
      { en: "Traditional recipes, same taste", hi: "पारंपरिक रेसिपी, वही स्वाद" },
      { en: "Hygienic kitchen and packing", hi: "साफ़-सुथरी रसोई और पैकिंग" },
      { en: "Gift packing done for you", hi: "गिफ़्ट पैकिंग हम करते हैं" },
      { en: "Bulk orders on time", hi: "बड़े ऑर्डर समय पर" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Pick your sweets", hi: "मिठाई चुनें", desc: "See the range here or at the shop and tell us what you like.", descHi: "यहाँ या दुकान पर रेंज देखें और बताएँ क्या चाहिए।" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर करें", desc: "Send the items, quantity and the date you need them.", descHi: "चीज़ें, मात्रा और तारीख़ भेज दें।" },
      { en: "Fresh and packed", hi: "ताज़ा बनकर पैक", desc: "Made fresh for your order and packed the way you asked.", descHi: "आपके ऑर्डर के लिए ताज़ा बनता है, आपकी पसंद की पैकिंग।" },
      { en: "Pick up or delivered", hi: "ले जाएँ या डिलीवरी", desc: "Collect from the shop or get it delivered at home.", descHi: "दुकान से ले जाएँ या घर पर मँगवाएँ।" },
    ],
    faq: [
      { q: "Do you take orders for weddings and functions?", qHi: "क्या शादी और फ़ंक्शन के ऑर्डर लेते हैं?", a: "Yes. Message us on WhatsApp with the items, quantity and date, and we will confirm.", aHi: "हाँ। WhatsApp पर चीज़ें, मात्रा और तारीख़ भेजें, हम कन्फ़र्म कर देंगे।" },
      { q: "Do you deliver at home?", qHi: "क्या होम डिलीवरी है?", a: "We deliver within the city for orders placed on WhatsApp; ask us for your area.", aHi: "WhatsApp पर दिए ऑर्डर शहर में डिलीवर होते हैं; अपने इलाक़े के लिए पूछ लें।" },
      { q: "How long do the sweets stay fresh?", qHi: "मिठाई कितने दिन ठीक रहती है?", a: "It depends on the sweet — milk sweets are best within a few days, dry sweets and namkeen keep longer. We tell you at the time of order.", aHi: "मिठाई पर निर्भर है — दूध वाली कुछ दिन, सूखी मिठाई और नमकीन ज़्यादा चलती है। ऑर्डर के समय बता देते हैं।" },
      { q: "Can I get gift packing?", qHi: "क्या गिफ़्ट पैकिंग मिलेगी?", a: "Yes, boxes and hampers are packed for gifting; tell us the occasion and budget.", aHi: "हाँ, गिफ़्ट के लिए डिब्बे और हैम्पर पैक करते हैं; मौक़ा और बजट बता दें।" },
      { q: "Do you make sugar-free sweets?", qHi: "क्या शुगर-फ़्री मिठाई बनती है?", a: "Some items can be made sugar-free on request; message us a day in advance.", aHi: "कुछ चीज़ें ऑर्डर पर शुगर-फ़्री बन सकती हैं; एक दिन पहले बता दें।" },
      { q: "Can I order by weight or only in boxes?", qHi: "वज़न से भी मिलता है या सिर्फ़ डिब्बे में?", a: "Both — sweets are sold by weight at the shop and in boxes for gifting.", aHi: "दोनों — दुकान पर वज़न से और गिफ़्ट के लिए डिब्बों में।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the shop; UPI for WhatsApp orders.", aHi: "दुकान पर नक़द, UPI और कार्ड; WhatsApp ऑर्डर के लिए UPI।" },
    ],
    generic: ["connect with us", "explore options", "finalise your choice", "quality products", "best quality", "customer satisfaction"],
  },

  restaurant: {
    explain: [
      "the kind of food and the signature dishes (veg / non-veg, cuisine, thali, specials)",
      "dine-in, takeaway and delivery; family seating",
      "party, bulk and event orders",
      "timings and how to order",
    ],
    services: [
      { en: "Dine-in", hi: "रेस्टोरेंट में भोजन", desc: "Comfortable seating for families and groups.", descHi: "परिवार और ग्रुप के लिए आरामदायक बैठने की जगह।" },
      { en: "Takeaway", hi: "टेकअवे / पार्सल", desc: "Order ahead on WhatsApp and pick it up hot.", descHi: "WhatsApp पर पहले ऑर्डर करें, गरम पार्सल ले जाएँ।" },
      { en: "Home delivery", hi: "होम डिलीवरी", desc: "Delivered to your door within the area we serve.", descHi: "हमारे इलाक़े में घर तक डिलीवरी।" },
      { en: "Party orders", hi: "पार्टी ऑर्डर", desc: "Food for birthdays, kitty parties and small functions.", descHi: "जन्मदिन, किटी पार्टी और छोटे फ़ंक्शन के लिए खाना।" },
      { en: "Bulk & office meals", hi: "थोक और ऑफ़िस भोजन", desc: "Packed meals and thalis for offices and events.", descHi: "ऑफ़िस और आयोजनों के लिए पैक्ड मील और थाली।" },
      { en: "Thali & combos", hi: "थाली और कॉम्बो", desc: "Full meals and value combos for everyday eating.", descHi: "रोज़ के खाने के लिए पूरी थाली और किफ़ायती कॉम्बो।" },
    ],
    whyUs: [
      { en: "Fresh, hot food", hi: "ताज़ा, गरम खाना" },
      { en: "Clean kitchen", hi: "साफ़ रसोई" },
      { en: "Home-style taste", hi: "घर जैसा स्वाद" },
      { en: "Family seating", hi: "परिवार के लिए बैठक" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
      { en: "Party orders welcome", hi: "पार्टी ऑर्डर लेते हैं" },
    ],
    steps: [
      { en: "See the menu", hi: "मेन्यू देखें", desc: "Browse the dishes here or ask us for today's specials.", descHi: "यहाँ डिश देखें या आज के स्पेशल पूछें।" },
      { en: "Order or book a table", hi: "ऑर्डर या टेबल बुक करें", desc: "Message us on WhatsApp for delivery, parcel or a table.", descHi: "डिलीवरी, पार्सल या टेबल के लिए WhatsApp करें।" },
      { en: "Enjoy your meal", hi: "खाने का आनंद लें", desc: "Fresh food, served hot — at the table or at your door.", descHi: "ताज़ा खाना, गरम — टेबल पर या आपके दरवाज़े।" },
    ],
    faq: [
      { q: "Do you deliver at home?", qHi: "क्या होम डिलीवरी है?", a: "Yes, within the area we serve. Message us your location on WhatsApp.", aHi: "हाँ, हमारे इलाक़े में। WhatsApp पर लोकेशन भेजें।" },
      { q: "Is the food veg or non-veg?", qHi: "खाना वेज है या नॉन-वेज?", a: "See the menu for what we serve; ask us for the day's specials.", aHi: "मेन्यू में देखें; दिन के स्पेशल पूछ लें।" },
      { q: "Can I book a table?", qHi: "क्या टेबल बुक हो सकती है?", a: "Yes — message us the date, time and number of people.", aHi: "हाँ — तारीख़, समय और लोगों की संख्या भेज दें।" },
      { q: "Do you take party orders?", qHi: "क्या पार्टी ऑर्डर लेते हैं?", a: "Yes, for small functions and offices. Tell us the menu and number of people a day in advance.", aHi: "हाँ, छोटे फ़ंक्शन और ऑफ़िस के लिए। मेन्यू और लोगों की संख्या एक दिन पहले बताएँ।" },
      { q: "What are your timings?", qHi: "आपका समय क्या है?", a: "See the timings on this page, or message us to check.", aHi: "इसी पेज पर समय देखें, या WhatsApp पर पूछ लें।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards.", aHi: "नक़द, UPI और कार्ड।" },
    ],
    generic: ["connect with us", "explore options", "quality food", "customer satisfaction"],
  },

  cafe: {
    explain: ["what is served (tea, coffee, snacks, bakes) and the house favourites", "the place — a spot to sit, work or meet", "takeaway and small orders for offices", "timings"],
    services: [
      { en: "Tea & coffee", hi: "चाय और कॉफ़ी", desc: "Freshly made, by the cup.", descHi: "ताज़ी बनी, कप में।" },
      { en: "Snacks & bakes", hi: "स्नैक्स और बेकरी", desc: "Light bites to go with your cup.", descHi: "चाय-कॉफ़ी के साथ हल्का नाश्ता।" },
      { en: "Takeaway", hi: "टेकअवे", desc: "Order on WhatsApp and pick up on the way.", descHi: "WhatsApp पर ऑर्डर करें, रास्ते में ले जाएँ।" },
      { en: "Office orders", hi: "ऑफ़िस ऑर्डर", desc: "Tea, coffee and snacks for meetings and teams.", descHi: "मीटिंग और टीम के लिए चाय, कॉफ़ी और स्नैक्स।" },
      { en: "A place to sit", hi: "बैठने की जगह", desc: "Meet friends, read or work for a while.", descHi: "दोस्तों से मिलें, पढ़ें या कुछ देर काम करें।" },
      { en: "Small celebrations", hi: "छोटे जश्न", desc: "A corner for birthdays and get-togethers — ask us.", descHi: "जन्मदिन और मिलने-जुलने के लिए — पूछ लें।" },
    ],
    whyUs: [
      { en: "Fresh every cup", hi: "हर कप ताज़ा" },
      { en: "Clean, calm place", hi: "साफ़, शांत जगह" },
      { en: "Friendly service", hi: "दोस्ताना सेवा" },
      { en: "Fair prices", hi: "वाजिब दाम" },
      { en: "Takeaway on WhatsApp", hi: "WhatsApp पर टेकअवे" },
      { en: "Open through the day", hi: "दिन भर खुला" },
    ],
    steps: [
      { en: "Drop in or message", hi: "आइए या मैसेज करें", desc: "Walk in any time, or order ahead on WhatsApp.", descHi: "कभी भी आइए, या WhatsApp पर पहले ऑर्डर करें।" },
      { en: "Choose from the menu", hi: "मेन्यू से चुनें", desc: "Tea, coffee, snacks — ask for today's special.", descHi: "चाय, कॉफ़ी, स्नैक्स — आज का स्पेशल पूछें।" },
      { en: "Sit back or take away", hi: "बैठिए या ले जाइए", desc: "Enjoy it here or on the go.", descHi: "यहीं बैठकर या रास्ते में।" },
    ],
    faq: [
      { q: "What are your timings?", qHi: "समय क्या है?", a: "See the timings on this page or message us.", aHi: "इसी पेज पर समय देखें या मैसेज करें।" },
      { q: "Can I order for an office?", qHi: "ऑफ़िस के लिए ऑर्डर हो सकता है?", a: "Yes — message us the items, quantity and time.", aHi: "हाँ — चीज़ें, मात्रा और समय भेजें।" },
      { q: "Is there seating?", qHi: "बैठने की जगह है?", a: "Yes, you are welcome to sit, meet or work for a while.", aHi: "हाँ, बैठिए, मिलिए या कुछ देर काम कीजिए।" },
      { q: "Do you do takeaway?", qHi: "टेकअवे है?", a: "Yes, order on WhatsApp and pick it up.", aHi: "हाँ, WhatsApp पर ऑर्डर करके ले जाएँ।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash and UPI.", aHi: "नक़द और UPI।" },
      { q: "Do you have Wi-Fi?", qHi: "Wi-Fi है?", a: "Ask us when you come — we will tell you what is available.", aHi: "आने पर पूछ लें — जो उपलब्ध है बता देंगे।" },
    ],
    generic: ["connect with us", "explore options"],
  },

  tiffin: {
    explain: ["home-style meals — what a typical tiffin has, veg / non-veg", "monthly and daily plans; lunch and dinner", "who it is for: students, working people, offices, patients", "delivery area and timings"],
    services: [
      { en: "Daily lunch tiffin", hi: "रोज़ का लंच टिफ़िन", desc: "Fresh home-style meal, packed and delivered on time.", descHi: "ताज़ा घर जैसा खाना, पैक होकर समय पर।" },
      { en: "Dinner tiffin", hi: "डिनर टिफ़िन", desc: "An evening meal for working people and students.", descHi: "नौकरीपेशा और छात्रों के लिए शाम का खाना।" },
      { en: "Monthly plans", hi: "मासिक प्लान", desc: "Pay by the month, pause when you travel.", descHi: "महीने का भुगतान, बाहर जाएँ तो रोक दें।" },
      { en: "Office & group orders", hi: "ऑफ़िस और ग्रुप ऑर्डर", desc: "Packed meals for teams and hostels.", descHi: "टीम और हॉस्टल के लिए पैक्ड खाना।" },
      { en: "Special diet meals", hi: "खास डाइट खाना", desc: "Less oil, less spice or as the doctor advised — on request.", descHi: "कम तेल, कम मसाला या डॉक्टर की सलाह अनुसार — ऑर्डर पर।" },
      { en: "Trial tiffin", hi: "ट्रायल टिफ़िन", desc: "Try one meal before you subscribe.", descHi: "सब्सक्राइब करने से पहले एक बार चखें।" },
    ],
    whyUs: [
      { en: "Cooked fresh, home style", hi: "ताज़ा, घर जैसा बना" },
      { en: "Clean kitchen", hi: "साफ़ रसोई" },
      { en: "On-time delivery", hi: "समय पर डिलीवरी" },
      { en: "Menu changes daily", hi: "रोज़ बदलता मेन्यू" },
      { en: "Pause any time", hi: "जब चाहें रोकें" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Message us", hi: "मैसेज करें", desc: "Tell us your area, meal (lunch / dinner) and veg or non-veg.", descHi: "इलाक़ा, खाना (लंच / डिनर) और वेज / नॉन-वेज बताएँ।" },
      { en: "Try a tiffin", hi: "एक टिफ़िन चखें", desc: "A trial meal, then pick a daily or monthly plan.", descHi: "एक ट्रायल खाना, फिर रोज़ या महीने का प्लान चुनें।" },
      { en: "Delivered daily", hi: "रोज़ डिलीवरी", desc: "Fresh food at your door at the same time every day.", descHi: "रोज़ उसी समय ताज़ा खाना आपके दरवाज़े।" },
    ],
    faq: [
      { q: "Which areas do you deliver to?", qHi: "किन इलाक़ों में डिलीवरी है?", a: "Message us your location on WhatsApp and we will confirm.", aHi: "WhatsApp पर लोकेशन भेजें, हम कन्फ़र्म करेंगे।" },
      { q: "What is in a typical tiffin?", qHi: "टिफ़िन में क्या-क्या होता है?", a: "A home-style meal — roti, sabzi, dal, rice; the menu changes daily.", aHi: "घर जैसा खाना — रोटी, सब्ज़ी, दाल, चावल; मेन्यू रोज़ बदलता है।" },
      { q: "Can I pause when I travel?", qHi: "बाहर जाऊँ तो रोक सकते हैं?", a: "Yes, tell us a day before and the days are adjusted.", aHi: "हाँ, एक दिन पहले बता दें, दिन एडजस्ट हो जाते हैं।" },
      { q: "Can I try before subscribing?", qHi: "सब्सक्राइब से पहले चख सकते हैं?", a: "Yes, order a trial tiffin first.", aHi: "हाँ, पहले एक ट्रायल टिफ़िन मँगवाएँ।" },
      { q: "Do you make low-oil or diet meals?", qHi: "कम तेल / डाइट खाना बनता है?", a: "Yes, on request — tell us what to avoid.", aHi: "हाँ, ऑर्डर पर — बताएँ क्या नहीं डालना।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, monthly or weekly.", aHi: "UPI, महीने या हफ़्ते का।" },
    ],
    generic: ["connect with us", "explore options"],
  },

  catering: {
    explain: ["what you cater — weddings, parties, pooja, corporate; veg / non-veg; cuisines", "menu planning with the client; live counters; staff and crockery", "how a booking works and what to share (date, venue, number of guests)"],
    services: [
      { en: "Wedding catering", hi: "शादी की कैटरिंग", desc: "Full menus for haldi, sangeet, reception and the wedding day.", descHi: "हल्दी, संगीत, रिसेप्शन और शादी के दिन के लिए पूरा मेन्यू।" },
      { en: "Party & birthday", hi: "पार्टी और जन्मदिन", desc: "Snacks, main course and desserts for home functions.", descHi: "घर के फ़ंक्शन के लिए स्नैक्स, मेन कोर्स और मीठा।" },
      { en: "Pooja & religious events", hi: "पूजा और धार्मिक आयोजन", desc: "Satvik meals and prasad, prepared with care.", descHi: "सात्विक भोजन और प्रसाद, पूरी शुद्धता से।" },
      { en: "Corporate & office", hi: "कॉर्पोरेट और ऑफ़िस", desc: "Packed lunches, conferences and office parties.", descHi: "पैक्ड लंच, कॉन्फ़्रेंस और ऑफ़िस पार्टी।" },
      { en: "Live counters", hi: "लाइव काउंटर", desc: "Chaat, dosa, pasta and more made in front of guests.", descHi: "चाट, डोसा, पास्ता और भी — मेहमानों के सामने तैयार।" },
      { en: "Staff, crockery & setup", hi: "स्टाफ़, बर्तन और सेटअप", desc: "Serving staff, crockery and counters arranged with the food.", descHi: "खाने के साथ सर्विस स्टाफ़, बर्तन और काउंटर।" },
    ],
    whyUs: [
      { en: "Menu planned with you", hi: "मेन्यू आपके साथ तय" },
      { en: "Fresh, cooked on the day", hi: "उसी दिन ताज़ा बना" },
      { en: "Hygienic kitchen and service", hi: "साफ़ रसोई और सर्विस" },
      { en: "Enough food, no shortfall", hi: "पूरा खाना, कमी नहीं" },
      { en: "On-time setup", hi: "समय पर सेटअप" },
      { en: "Veg and non-veg kept separate", hi: "वेज-नॉनवेज अलग" },
    ],
    steps: [
      { en: "Share your event", hi: "आयोजन बताएँ", desc: "Date, venue, number of guests and the kind of function.", descHi: "तारीख़, जगह, मेहमानों की संख्या और फ़ंक्शन का प्रकार।" },
      { en: "Plan the menu", hi: "मेन्यू तय करें", desc: "We suggest a menu to your taste and budget; you finalise.", descHi: "हम स्वाद और बजट के हिसाब से मेन्यू सुझाते हैं; आप तय करें।" },
      { en: "Tasting and confirmation", hi: "टेस्टिंग और कन्फ़र्मेशन", desc: "Taste if you like, confirm with an advance.", descHi: "चाहें तो चखें, एडवांस देकर कन्फ़र्म करें।" },
      { en: "We serve on the day", hi: "दिन पर हम संभालें", desc: "Food, staff and counters arrive on time; you enjoy the event.", descHi: "खाना, स्टाफ़ और काउंटर समय पर; आप आयोजन का आनंद लें।" },
    ],
    faq: [
      { q: "What is the minimum number of guests?", qHi: "कम से कम कितने मेहमान?", a: "We cater small home functions as well as large weddings — message us the number and we will tell you.", aHi: "छोटे घरेलू फ़ंक्शन से बड़ी शादी तक — संख्या भेजें, हम बताएँगे।" },
      { q: "Do you provide staff and crockery?", qHi: "स्टाफ़ और बर्तन देते हैं?", a: "Yes, serving staff, crockery and counters can be arranged with the food.", aHi: "हाँ, खाने के साथ सर्विस स्टाफ़, बर्तन और काउंटर।" },
      { q: "Can we taste the food before booking?", qHi: "बुकिंग से पहले चख सकते हैं?", a: "Yes, a tasting can be arranged for larger events.", aHi: "हाँ, बड़े आयोजनों के लिए टेस्टिंग रखते हैं।" },
      { q: "Veg and non-veg both?", qHi: "वेज और नॉन-वेज दोनों?", a: "Ask us — where both are served, they are prepared and served separately.", aHi: "पूछ लें — जहाँ दोनों हों, अलग बनते और परोसे जाते हैं।" },
      { q: "How far in advance should I book?", qHi: "कितने पहले बुक करें?", a: "The earlier the better for wedding dates; message us and we will check availability.", aHi: "शादी की तारीख़ों के लिए जितना पहले उतना अच्छा; मैसेज करें, उपलब्धता बताएँगे।" },
      { q: "How is payment done?", qHi: "भुगतान कैसे होता है?", a: "An advance at booking and the balance after the event; UPI or bank transfer.", aHi: "बुकिंग पर एडवांस, बाक़ी आयोजन के बाद; UPI या बैंक ट्रांसफ़र।" },
    ],
    generic: ["connect with us", "explore options"],
  },

  hotel: {
    explain: ["rooms and what is included (AC, breakfast, parking, family rooms)", "location — what it is near (station, market, temple, highway)", "booking and check-in; group and long stays", "restaurant / room service if any"],
    services: [
      { en: "Rooms for families", hi: "परिवार के लिए कमरे", desc: "Clean, comfortable rooms for couples and families.", descHi: "जोड़ों और परिवार के लिए साफ़, आरामदायक कमरे।" },
      { en: "Group & long stays", hi: "ग्रुप और लंबा ठहराव", desc: "Rooms for groups, tour parties and long stays at a fair rate.", descHi: "ग्रुप, टूर पार्टी और लंबे ठहराव के लिए वाजिब दर पर कमरे।" },
      { en: "Restaurant / room service", hi: "रेस्टोरेंट / रूम सर्विस", desc: "Meals and tea in the room or the dining hall.", descHi: "कमरे या डाइनिंग हॉल में भोजन और चाय।" },
      { en: "Parking", hi: "पार्किंग", desc: "Safe parking for cars and bikes.", descHi: "कार और बाइक के लिए सुरक्षित पार्किंग।" },
      { en: "Events & functions", hi: "आयोजन और फ़ंक्शन", desc: "A hall for small functions and meetings — ask us.", descHi: "छोटे फ़ंक्शन और मीटिंग के लिए हॉल — पूछ लें।" },
      { en: "Travel help", hi: "यात्रा में मदद", desc: "Local sightseeing, taxi and directions on request.", descHi: "लोकल घूमना, टैक्सी और रास्ता — ऑर्डर पर।" },
    ],
    whyUs: [
      { en: "Clean rooms, fresh linen", hi: "साफ़ कमरे, ताज़ा चादर" },
      { en: "Easy to reach", hi: "पहुँचना आसान" },
      { en: "Family-friendly", hi: "परिवार के अनुकूल" },
      { en: "Fair rates, no hidden charges", hi: "वाजिब दर, कोई छिपा शुल्क नहीं" },
      { en: "Help any time of day", hi: "दिन-रात मदद" },
      { en: "Book on WhatsApp", hi: "WhatsApp पर बुकिंग" },
    ],
    steps: [
      { en: "Message your dates", hi: "तारीख़ें भेजें", desc: "Check-in, check-out and the number of guests.", descHi: "चेक-इन, चेक-आउट और मेहमानों की संख्या।" },
      { en: "Confirm the room", hi: "कमरा कन्फ़र्म करें", desc: "We share the room type and rate; confirm with a small advance.", descHi: "हम कमरे का प्रकार और दर बताते हैं; छोटा एडवांस देकर कन्फ़र्म करें।" },
      { en: "Check in and relax", hi: "चेक-इन करें, आराम करें", desc: "Carry an ID; the room is ready when you arrive.", descHi: "आईडी साथ लाएँ; आने पर कमरा तैयार।" },
    ],
    faq: [
      { q: "What are the check-in and check-out times?", qHi: "चेक-इन और चेक-आउट का समय?", a: "Message us — we tell you the times and can adjust for early or late arrivals when possible.", aHi: "मैसेज करें — समय बताते हैं, जल्दी/देर से आने पर जहाँ संभव हो एडजस्ट करते हैं।" },
      { q: "Is breakfast included?", qHi: "नाश्ता शामिल है?", a: "Ask us for your dates — we tell you what the rate includes.", aHi: "अपनी तारीख़ों के लिए पूछें — बताएँगे दर में क्या शामिल है।" },
      { q: "Is parking available?", qHi: "पार्किंग है?", a: "Yes, for cars and bikes.", aHi: "हाँ, कार और बाइक के लिए।" },
      { q: "Do you take group bookings?", qHi: "ग्रुप बुकिंग लेते हैं?", a: "Yes — tour groups, wedding guests and long stays; message us the dates and number of rooms.", aHi: "हाँ — टूर ग्रुप, शादी के मेहमान और लंबा ठहराव; तारीख़ें और कमरों की संख्या भेजें।" },
      { q: "Which ID is needed?", qHi: "कौन सी आईडी चाहिए?", a: "A government photo ID for every adult guest.", aHi: "हर वयस्क मेहमान का सरकारी फ़ोटो आईडी।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, cards or cash at the hotel; an advance confirms the booking.", aHi: "होटल पर UPI, कार्ड या नक़द; एडवांस से बुकिंग कन्फ़र्म।" },
    ],
    generic: ["connect with us", "explore options"],
  },
};
