// Health & beauty trades: doctor / clinic, hospital, dentist, ayurveda / homeopathy, pharma, gym / yoga, salon, spa, water purifier, wellness products.
// See types.ts for the rules (no numbers, no claims, no cures or outcomes; true of any decent business of the trade).
import type { TradeData } from "./types";

export const HEALTH: Record<string, TradeData> = {
  doctor: {
    explain: [
      "what the doctor treats — speciality, the common problems seen, who comes (families, children, elderly)",
      "consultation: timings, appointment on WhatsApp or walk-in, what to bring (old reports, medicines)",
      "what the clinic has — basic tests, injections, dressing, vaccination, follow-up",
      "the doctor's way of working — listens, explains, refers to a specialist when needed",
    ],
    services: [
      { en: "Consultation", hi: "परामर्श", desc: "Examination and advice for everyday illnesses and ongoing problems.", descHi: "रोज़मर्रा की बीमारियों और पुरानी तकलीफ़ों की जाँच और सलाह।" },
      { en: "Follow-up visits", hi: "फ़ॉलो-अप", desc: "Review of your progress and medicines on the next visit.", descHi: "अगली विज़िट पर सुधार और दवाइयों की समीक्षा।" },
      { en: "Basic tests & reports", hi: "बुनियादी जाँच और रिपोर्ट", desc: "BP, sugar and routine checks; help reading your reports.", descHi: "BP, शुगर और रूटीन जाँच; रिपोर्ट समझने में मदद।" },
      { en: "Injections & dressing", hi: "इंजेक्शन और ड्रेसिंग", desc: "Injections, wound dressing and minor procedures at the clinic.", descHi: "क्लिनिक पर इंजेक्शन, घाव की ड्रेसिंग और छोटी प्रक्रियाएँ।" },
      { en: "Vaccination", hi: "टीकाकरण", desc: "Routine vaccines for children and adults, as per schedule.", descHi: "बच्चों और बड़ों के लिए रूटीन टीके, शेड्यूल के अनुसार।" },
      { en: "Health check-ups", hi: "हेल्थ चेक-अप", desc: "Routine check-ups for families, seniors and working people.", descHi: "परिवार, बुज़ुर्गों और नौकरीपेशा लोगों के लिए रूटीन चेक-अप।" },
      { en: "Referral & second opinion", hi: "रेफ़रल और दूसरी राय", desc: "Guidance on specialists and hospitals when further care is needed.", descHi: "ज़रूरत पड़ने पर स्पेशलिस्ट और हॉस्पिटल के बारे में मार्गदर्शन।" },
    ],
    whyUs: [
      { en: "Listens before prescribing", hi: "पहले सुनते हैं, फिर दवा" },
      { en: "Explains in simple words", hi: "आसान भाषा में समझाते हैं" },
      { en: "Appointment on WhatsApp", hi: "WhatsApp पर अपॉइंटमेंट" },
      { en: "Clean, hygienic clinic", hi: "साफ़-सुथरा क्लिनिक" },
      { en: "Your records kept safely", hi: "आपका रिकॉर्ड संभालकर रखते हैं" },
      { en: "Only the tests you need", hi: "सिर्फ़ ज़रूरी जाँच" },
      { en: "Refers when needed", hi: "ज़रूरत पर रेफ़र करते हैं" },
    ],
    steps: [
      { en: "Book or walk in", hi: "अपॉइंटमेंट लें या सीधे आएँ", desc: "Message us on WhatsApp for a time, or come during clinic hours.", descHi: "WhatsApp पर समय लें, या क्लिनिक के समय में आएँ।" },
      { en: "Bring your reports", hi: "रिपोर्ट साथ लाएँ", desc: "Old reports, prescriptions and current medicines help the doctor.", descHi: "पुरानी रिपोर्ट, पर्ची और चल रही दवाइयाँ साथ लाएँ।" },
      { en: "Consultation", hi: "जाँच और सलाह", desc: "The doctor examines, explains and writes the prescription.", descHi: "डॉक्टर जाँच करते हैं, समझाते हैं और पर्ची लिखते हैं।" },
      { en: "Follow-up", hi: "फ़ॉलो-अप", desc: "Come back on the date advised, or message if something changes.", descHi: "बताई तारीख़ पर आएँ, या कुछ बदले तो मैसेज करें।" },
    ],
    faq: [
      { q: "Do I need an appointment?", qHi: "क्या अपॉइंटमेंट ज़रूरी है?", a: "Walk-ins are seen during clinic hours; an appointment on WhatsApp saves waiting.", aHi: "क्लिनिक के समय में सीधे आ सकते हैं; WhatsApp पर अपॉइंटमेंट लेने से इंतज़ार कम होता है।" },
      { q: "What should I bring?", qHi: "क्या साथ लाना है?", a: "Old reports, prescriptions and the medicines you are taking; for children, the vaccination card.", aHi: "पुरानी रिपोर्ट, पर्ची और जो दवाइयाँ चल रही हैं; बच्चों के लिए टीके का कार्ड।" },
      { q: "What are the clinic timings?", qHi: "क्लिनिक का समय क्या है?", a: "See the timings on this page, or message us to check before you come.", aHi: "इसी पेज पर समय देखें, या आने से पहले मैसेज करके पूछ लें।" },
      { q: "Does the doctor see children and the elderly?", qHi: "क्या बच्चों और बुज़ुर्गों को देखते हैं?", a: "Message us the patient's age and problem; we will tell you whether to come here or see a specialist.", aHi: "मरीज़ की उम्र और तकलीफ़ WhatsApp पर बताएँ; हम बताएँगे यहाँ आएँ या स्पेशलिस्ट को दिखाएँ।" },
      { q: "Can I consult on phone or video?", qHi: "फ़ोन या वीडियो पर सलाह मिलेगी?", a: "For follow-ups and reports, ask on WhatsApp; a first visit is usually better in person.", aHi: "फ़ॉलो-अप और रिपोर्ट के लिए WhatsApp पर पूछें; पहली बार क्लिनिक आना बेहतर है।" },
      { q: "Are tests done at the clinic?", qHi: "क्या जाँच क्लिनिक पर होती है?", a: "Basic checks are done here; for other tests we guide you to a lab and read the reports.", aHi: "बुनियादी जाँच यहीं होती है; बाक़ी के लिए लैब बताते हैं और रिपोर्ट देखते हैं।" },
      { q: "How do I pay?", qHi: "फ़ीस कैसे दें?", a: "Cash and UPI at the clinic; ask us the consultation fee on WhatsApp.", aHi: "क्लिनिक पर नक़द और UPI; फ़ीस WhatsApp पर पूछ लें।" },
    ],
    generic: ["connect with us", "explore options", "best doctor", "quality treatment", "expert care", "patient satisfaction"],
  },

  hospital: {
    explain: [
      "departments and what is treated — general medicine, surgery, maternity, children, orthopaedics as applicable",
      "facilities — beds, ICU, operation theatre, pathology, X-ray, pharmacy, ambulance",
      "OPD timings, emergency round the clock, how to book",
      "insurance / cashless, government schemes if any, and how billing works",
    ],
    services: [
      { en: "OPD consultation", hi: "OPD परामर्श", desc: "Doctors of different departments see patients in the OPD.", descHi: "अलग-अलग विभागों के डॉक्टर OPD में मरीज़ देखते हैं।" },
      { en: "Emergency", hi: "इमरजेंसी", desc: "Emergency care round the clock with a doctor on duty.", descHi: "दिन-रात इमरजेंसी, डॉक्टर ड्यूटी पर।" },
      { en: "Indoor admission", hi: "भर्ती (IPD)", desc: "General and private rooms with nursing care.", descHi: "जनरल और प्राइवेट कमरे, नर्सिंग देखभाल के साथ।" },
      { en: "Operation theatre", hi: "ऑपरेशन थिएटर", desc: "Planned and emergency surgeries by the hospital's surgeons.", descHi: "हॉस्पिटल के सर्जन द्वारा नियोजित और इमरजेंसी ऑपरेशन।" },
      { en: "Lab, X-ray & scans", hi: "लैब, X-ray और स्कैन", desc: "Pathology and imaging under one roof, reports in time.", descHi: "पैथोलॉजी और इमेजिंग एक ही जगह, रिपोर्ट समय पर।" },
      { en: "Pharmacy & ambulance", hi: "फ़ार्मेसी और एम्बुलेंस", desc: "In-house medical store and ambulance for pick-up and transfer.", descHi: "हॉस्पिटल में मेडिकल स्टोर और लाने-ले जाने के लिए एम्बुलेंस।" },
      { en: "Insurance & cashless", hi: "इंश्योरेंस और कैशलेस", desc: "Help with insurance claims, TPA and government schemes.", descHi: "इंश्योरेंस क्लेम, TPA और सरकारी योजनाओं में मदद।" },
    ],
    whyUs: [
      { en: "Emergency, day and night", hi: "इमरजेंसी दिन-रात" },
      { en: "Experienced doctors and nurses", hi: "अनुभवी डॉक्टर और नर्स" },
      { en: "Clean wards and rooms", hi: "साफ़ वार्ड और कमरे" },
      { en: "Tests and pharmacy in-house", hi: "जाँच और दवा एक ही जगह" },
      { en: "Insurance help at the desk", hi: "इंश्योरेंस में मदद" },
      { en: "Clear billing, no surprises", hi: "साफ़ बिलिंग, कोई छिपा खर्च नहीं" },
      { en: "Family kept informed", hi: "परिवार को जानकारी मिलती रहती है" },
    ],
    steps: [
      { en: "Call or message", hi: "कॉल या मैसेज करें", desc: "For OPD, book on WhatsApp; in an emergency, call and come straight in.", descHi: "OPD के लिए WhatsApp पर बुक करें; इमरजेंसी में कॉल करके सीधे आएँ।" },
      { en: "Register at the desk", hi: "रिसेप्शन पर रजिस्टर करें", desc: "Carry an ID and old reports; share insurance details if any.", descHi: "आईडी और पुरानी रिपोर्ट लाएँ; इंश्योरेंस हो तो बताएँ।" },
      { en: "Consultation and tests", hi: "जाँच और परामर्श", desc: "The doctor examines and advises tests, medicines or admission.", descHi: "डॉक्टर जाँच करके टेस्ट, दवा या भर्ती की सलाह देते हैं।" },
      { en: "Treatment and discharge", hi: "इलाज और छुट्टी", desc: "Care in the ward, then a discharge summary and follow-up date.", descHi: "वार्ड में देखभाल, फिर डिस्चार्ज समरी और फ़ॉलो-अप की तारीख़।" },
    ],
    faq: [
      { q: "Is emergency open at night?", qHi: "क्या रात में इमरजेंसी खुली रहती है?", a: "Yes, emergency and ambulance run round the clock; call before you come if you can.", aHi: "हाँ, इमरजेंसी और एम्बुलेंस दिन-रात चलती है; हो सके तो आने से पहले कॉल करें।" },
      { q: "Which doctors are available?", qHi: "कौन से डॉक्टर उपलब्ध हैं?", a: "Message us the problem and we will tell you the department, doctor and OPD time.", aHi: "तकलीफ़ WhatsApp पर बताएँ; हम विभाग, डॉक्टर और OPD का समय बताएँगे।" },
      { q: "Do you accept insurance or cashless?", qHi: "इंश्योरेंस / कैशलेस चलता है?", a: "Ask us with your policy name; the desk helps with cashless, TPA and government schemes.", aHi: "अपनी पॉलिसी का नाम बताकर पूछें; रिसेप्शन कैशलेस, TPA और सरकारी योजनाओं में मदद करता है।" },
      { q: "What should I bring for admission?", qHi: "भर्ती के लिए क्या लाना है?", a: "An ID, old reports and prescriptions, insurance card if any, and an attendant.", aHi: "आईडी, पुरानी रिपोर्ट और पर्ची, इंश्योरेंस कार्ड हो तो, और साथ रहने वाला एक व्यक्ति।" },
      { q: "Are tests done in the hospital?", qHi: "क्या जाँच हॉस्पिटल में होती है?", a: "Yes, lab, X-ray and most scans are done here; for others we guide you.", aHi: "हाँ, लैब, X-ray और ज़्यादातर स्कैन यहीं होते हैं; बाक़ी के लिए बता देते हैं।" },
      { q: "Can family stay with the patient?", qHi: "क्या परिवार मरीज़ के साथ रह सकता है?", a: "One attendant can stay in most rooms; ask about visiting hours at the desk.", aHi: "ज़्यादातर कमरों में एक व्यक्ति साथ रह सकता है; मिलने का समय रिसेप्शन से पूछें।" },
      { q: "How is billing done?", qHi: "बिल कैसे बनता है?", a: "An estimate is given before admission or surgery; pay by cash, UPI or card.", aHi: "भर्ती या ऑपरेशन से पहले अनुमान बताया जाता है; नक़द, UPI या कार्ड से भुगतान।" },
    ],
    generic: ["connect with us", "explore options", "best hospital", "world class", "quality care", "patient satisfaction"],
  },

  dentist: {
    explain: [
      "what is treated — cleaning, fillings, root canal, extraction, braces, crowns, implants, dentures as applicable",
      "comfort and hygiene — local anaesthesia, sterilised instruments, disposables",
      "children and seniors; first visit, check-ups and how many sittings a treatment takes",
      "appointment on WhatsApp, timings, urgent pain cases, follow-up",
    ],
    services: [
      { en: "Check-up & cleaning", hi: "जाँच और सफ़ाई", desc: "Routine check-up and scaling to keep teeth and gums healthy.", descHi: "दाँत और मसूड़े ठीक रखने के लिए रूटीन जाँच और स्केलिंग।" },
      { en: "Fillings", hi: "फ़िलिंग", desc: "Tooth-coloured fillings for cavities and chipped teeth.", descHi: "कैविटी और टूटे दाँत के लिए दाँत के रंग की फ़िलिंग।" },
      { en: "Root canal", hi: "रूट कैनाल", desc: "Treatment to save a painful or infected tooth.", descHi: "दर्द या इन्फ़ेक्शन वाले दाँत को बचाने का इलाज।" },
      { en: "Extraction", hi: "दाँत निकालना", desc: "Removal of damaged or wisdom teeth, with care for your comfort.", descHi: "ख़राब दाँत या अक्ल दाढ़ निकालना, आराम का पूरा ध्यान।" },
      { en: "Braces & aligners", hi: "ब्रेसेस और अलाइनर", desc: "Straightening of crooked teeth for children and adults.", descHi: "बच्चों और बड़ों के टेढ़े दाँत सीधे करना।" },
      { en: "Crowns, bridges & implants", hi: "कैप, ब्रिज और इम्प्लांट", desc: "Replacing missing or broken teeth so you can eat and smile.", descHi: "टूटे या गायब दाँत की जगह नया, ताकि खाना और मुस्कुराना आसान हो।" },
      { en: "Dentures", hi: "नकली दाँत (डेंचर)", desc: "Full and partial dentures, fitted and adjusted for you.", descHi: "पूरे और आंशिक डेंचर, आपके हिसाब से फ़िट और एडजस्ट।" },
    ],
    whyUs: [
      { en: "Gentle, comfortable treatment", hi: "आराम से, दर्द का ध्यान" },
      { en: "Sterilised instruments every time", hi: "हर बार स्टरलाइज़ उपकरण" },
      { en: "Treatment explained before starting", hi: "शुरू से पहले इलाज समझाते हैं" },
      { en: "Appointment on WhatsApp", hi: "WhatsApp पर अपॉइंटमेंट" },
      { en: "Children treated patiently", hi: "बच्चों का इलाज धैर्य से" },
      { en: "Clear cost before treatment", hi: "इलाज से पहले खर्च साफ़" },
      { en: "Follow-up and after-care advice", hi: "फ़ॉलो-अप और देखभाल की सलाह" },
    ],
    steps: [
      { en: "Book an appointment", hi: "अपॉइंटमेंट लें", desc: "Message us on WhatsApp with your problem and a convenient time.", descHi: "WhatsApp पर तकलीफ़ और सुविधाजनक समय बताएँ।" },
      { en: "Check-up & plan", hi: "जाँच और प्लान", desc: "The dentist examines, takes an X-ray if needed and explains the options.", descHi: "डेंटिस्ट जाँच करते हैं, ज़रूरत हो तो X-ray, और विकल्प समझाते हैं।" },
      { en: "Treatment", hi: "इलाज", desc: "Done in one or more sittings, as the plan needs.", descHi: "प्लान के हिसाब से एक या ज़्यादा सिटिंग में।" },
      { en: "After-care & follow-up", hi: "देखभाल और फ़ॉलो-अप", desc: "Care instructions, and a review visit if advised.", descHi: "देखभाल की हिदायतें, और ज़रूरत हो तो रिव्यू विज़िट।" },
    ],
    faq: [
      { q: "Is the treatment painful?", qHi: "क्या इलाज में दर्द होता है?", a: "Most treatments are done under local anaesthesia; tell the dentist if you feel any discomfort.", aHi: "ज़्यादातर इलाज सुन्न करके होता है; कुछ तकलीफ़ हो तो डेंटिस्ट को बताएँ।" },
      { q: "How many sittings will it take?", qHi: "कितनी सिटिंग लगेंगी?", a: "It depends on the treatment; the dentist tells you after the check-up.", aHi: "इलाज पर निर्भर है; जाँच के बाद डेंटिस्ट बता देते हैं।" },
      { q: "Do you treat children?", qHi: "क्या बच्चों का इलाज करते हैं?", a: "Yes, children are seen patiently — bring them for a check-up before there is pain.", aHi: "हाँ, बच्चों को धैर्य से देखते हैं — दर्द होने से पहले जाँच के लिए लाएँ।" },
      { q: "What will the treatment cost?", qHi: "इलाज का खर्च कितना होगा?", a: "The cost is explained after the check-up, before treatment starts; message us for an idea.", aHi: "जाँच के बाद, इलाज शुरू होने से पहले खर्च बता दिया जाता है; अंदाज़े के लिए मैसेज करें।" },
      { q: "Are the instruments sterilised?", qHi: "क्या उपकरण स्टरलाइज़ होते हैं?", a: "Yes, instruments are sterilised for every patient and disposables are used where needed.", aHi: "हाँ, हर मरीज़ के लिए उपकरण स्टरलाइज़ होते हैं और जहाँ ज़रूरी हो डिस्पोज़ेबल इस्तेमाल होते हैं।" },
      { q: "I have sudden tooth pain — can I come today?", qHi: "अचानक दाँत में दर्द है — आज आ सकते हैं?", a: "Message us on WhatsApp; urgent cases are fitted in during clinic hours.", aHi: "WhatsApp पर मैसेज करें; क्लिनिक के समय में ज़रूरी केस देख लिए जाते हैं।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the clinic; for longer treatments, pay per sitting.", aHi: "क्लिनिक पर नक़द, UPI और कार्ड; लंबे इलाज में हर सिटिंग पर।" },
    ],
    generic: ["connect with us", "explore options", "best dentist", "perfect smile", "painless treatment", "quality treatment"],
  },

  ayurveda: {
    explain: [
      "the system — Ayurveda, homeopathy or both — and the problems people commonly come for (digestion, skin, joints, lifestyle)",
      "the approach — understanding the person, with diet and daily routine alongside the medicines",
      "medicines dispensed at the clinic; panchakarma / therapies if any",
      "consultation: timings, appointment on WhatsApp, follow-up for outstation patients",
    ],
    services: [
      { en: "Consultation", hi: "परामर्श", desc: "Detailed history and examination before any medicine is given.", descHi: "दवा देने से पहले पूरी बात और जाँच।" },
      { en: "Diet & lifestyle advice", hi: "आहार और दिनचर्या की सलाह", desc: "What to eat, what to avoid and a daily routine that suits you.", descHi: "क्या खाएँ, क्या नहीं, और आपके लिए सही दिनचर्या।" },
      { en: "Medicines", hi: "दवाइयाँ", desc: "Classical and prepared medicines dispensed at the clinic.", descHi: "क्लासिकल और तैयार दवाइयाँ क्लिनिक पर ही।" },
      { en: "Panchakarma & therapies", hi: "पंचकर्म और थेरेपी", desc: "Oil massage, steam and detox therapies as advised by the vaidya.", descHi: "वैद्य की सलाह पर तेल मालिश, भाप और डिटॉक्स थेरेपी।" },
      { en: "Chronic & lifestyle problems", hi: "पुरानी और लाइफ़स्टाइल समस्याएँ", desc: "Long-standing complaints managed with medicine, diet and routine together.", descHi: "पुरानी तकलीफ़ों के लिए दवा, आहार और दिनचर्या साथ-साथ।" },
      { en: "Children & elderly care", hi: "बच्चों और बुज़ुर्गों की देखभाल", desc: "Gentle treatment suited to age and constitution.", descHi: "उम्र और प्रकृति के हिसाब से सौम्य इलाज।" },
      { en: "Follow-up & online advice", hi: "फ़ॉलो-अप और ऑनलाइन सलाह", desc: "Review visits, and WhatsApp follow-up for outstation patients.", descHi: "रिव्यू विज़िट, और बाहर के मरीज़ों के लिए WhatsApp फ़ॉलो-अप।" },
    ],
    whyUs: [
      { en: "Time given to each patient", hi: "हर मरीज़ को पूरा समय" },
      { en: "Looks at the whole person", hi: "पूरे व्यक्ति को देखते हैं" },
      { en: "Diet and routine with medicine", hi: "दवा के साथ आहार-दिनचर्या" },
      { en: "Genuine, trusted medicines", hi: "असली, भरोसेमंद दवाइयाँ" },
      { en: "Gentle on children and elderly", hi: "बच्चों-बुज़ुर्गों के लिए सौम्य" },
      { en: "Honest about what will help", hi: "क्या फ़ायदा होगा, साफ़ बताते हैं" },
      { en: "Appointment on WhatsApp", hi: "WhatsApp पर अपॉइंटमेंट" },
    ],
    steps: [
      { en: "Message us", hi: "मैसेज करें", desc: "Tell us the problem briefly and take an appointment.", descHi: "तकलीफ़ संक्षेप में बताएँ और अपॉइंटमेंट लें।" },
      { en: "Detailed consultation", hi: "विस्तार से परामर्श", desc: "History, routine, diet and reports are discussed at length.", descHi: "बीमारी, दिनचर्या, खान-पान और रिपोर्ट पर पूरी बात।" },
      { en: "Medicine & routine", hi: "दवा और दिनचर्या", desc: "Medicines with clear instructions, plus diet and daily routine.", descHi: "साफ़ निर्देशों के साथ दवा, और आहार-दिनचर्या।" },
      { en: "Follow-up", hi: "फ़ॉलो-अप", desc: "Review at the clinic or on WhatsApp; medicines adjusted as you progress.", descHi: "क्लिनिक या WhatsApp पर रिव्यू; सुधार के हिसाब से दवा में बदलाव।" },
    ],
    faq: [
      { q: "Can I take these with my allopathic medicines?", qHi: "क्या ये दवाइयाँ अंग्रेज़ी दवा के साथ ले सकते हैं?", a: "Often yes, but tell the doctor everything you are taking; never stop a prescribed medicine on your own.", aHi: "अक्सर हाँ, पर जो भी दवा चल रही है डॉक्टर को बताएँ; कोई दवा अपने आप बंद न करें।" },
      { q: "How long does the treatment take?", qHi: "इलाज में कितना समय लगता है?", a: "It varies with the problem and the person; the doctor gives an idea after the first consultation.", aHi: "समस्या और व्यक्ति पर निर्भर है; पहली बार देखने के बाद डॉक्टर अंदाज़ा बताते हैं।" },
      { q: "Are there side effects?", qHi: "क्या कोई साइड इफ़ेक्ट होता है?", a: "Medicines are given as per your constitution and dose; tell the doctor if anything feels wrong.", aHi: "दवा आपकी प्रकृति और मात्रा के हिसाब से दी जाती है; कुछ ग़लत लगे तो डॉक्टर को बताएँ।" },
      { q: "Do I need to follow a diet?", qHi: "क्या परहेज़ करना पड़ेगा?", a: "Yes, diet and routine are part of the treatment; you get a simple list to follow.", aHi: "हाँ, परहेज़ और दिनचर्या इलाज का हिस्सा हैं; एक आसान लिस्ट दी जाती है।" },
      { q: "Can I consult online?", qHi: "क्या ऑनलाइन सलाह मिल सकती है?", a: "The first visit is better in person; follow-ups can be on WhatsApp or video — ask us.", aHi: "पहली बार आना बेहतर है; फ़ॉलो-अप WhatsApp या वीडियो पर हो सकता है — पूछ लें।" },
      { q: "Are medicines available at the clinic?", qHi: "दवाइयाँ क्लिनिक पर मिल जाती हैं?", a: "Most are dispensed here; a few may need to be bought from an Ayurvedic or homeopathic store.", aHi: "ज़्यादातर यहीं मिलती हैं; कुछ आयुर्वेदिक या होम्योपैथिक स्टोर से लेनी पड़ सकती हैं।" },
      { q: "How do I pay?", qHi: "फ़ीस कैसे दें?", a: "Cash and UPI at the clinic; consultation and medicines are billed separately.", aHi: "क्लिनिक पर नक़द और UPI; परामर्श और दवा का बिल अलग।" },
    ],
    generic: ["connect with us", "explore options", "natural healing", "no side effects", "guaranteed cure", "holistic wellness"],
  },

  pharma: {
    explain: [
      "who you are — pharma company, PCD franchise, stockist / distributor or medical representative — and the territory covered",
      "the product range — therapeutic segments (general, paediatric, derma, ayurvedic etc.) and the brands",
      "how doctors and chemists work with you — visits, samples, orders, supply and trade terms",
      "quality — medicines from licensed manufacturing units; proper storage and cold chain where needed",
    ],
    services: [
      { en: "Product range", hi: "प्रोडक्ट रेंज", desc: "Medicines across common therapeutic segments; product list on request.", descHi: "आम थेरेप्यूटिक सेगमेंट की दवाइयाँ; प्रोडक्ट लिस्ट माँग लें।" },
      { en: "Doctor visits & detailing", hi: "डॉक्टर विज़िट और डिटेलिंग", desc: "Regular visits to doctors with product information and literature.", descHi: "डॉक्टरों से नियमित मुलाक़ात, प्रोडक्ट की जानकारी और लिटरेचर के साथ।" },
      { en: "Samples & inputs", hi: "सैंपल और इनपुट", desc: "Physician samples and reminders for the doctors we serve.", descHi: "डॉक्टरों के लिए सैंपल और रिमाइंडर।" },
      { en: "Supply to chemists", hi: "केमिस्ट को सप्लाई", desc: "Orders delivered to medical stores through our stockists on time.", descHi: "स्टॉकिस्ट के ज़रिए मेडिकल स्टोर तक समय पर ऑर्डर।" },
      { en: "Hospital & institutional supply", hi: "हॉस्पिटल और संस्थागत सप्लाई", desc: "Bulk supply to hospitals, nursing homes and clinics.", descHi: "हॉस्पिटल, नर्सिंग होम और क्लिनिक को थोक सप्लाई।" },
      { en: "Stockist & franchise", hi: "स्टॉकिस्ट और फ़्रेंचाइज़ी", desc: "Stockist, distributor and PCD franchise openings for your area — ask us.", descHi: "अपने इलाक़े के लिए स्टॉकिस्ट, डिस्ट्रीब्यूटर और PCD फ़्रेंचाइज़ी — पूछ लें।" },
      { en: "Orders on WhatsApp", hi: "WhatsApp पर ऑर्डर", desc: "Send the order list on WhatsApp; invoice and dispatch confirmed.", descHi: "ऑर्डर लिस्ट WhatsApp पर भेजें; बिल और डिस्पैच कन्फ़र्म।" },
    ],
    whyUs: [
      { en: "Medicines from licensed units", hi: "लाइसेंस्ड यूनिट की दवाइयाँ" },
      { en: "Regular, timely supply", hi: "नियमित, समय पर सप्लाई" },
      { en: "Proper storage, cold chain", hi: "सही स्टोरेज, कोल्ड चेन" },
      { en: "Fair margins for chemists", hi: "केमिस्ट के लिए वाजिब मार्जिन" },
      { en: "Expiry and breakage handled", hi: "एक्सपायरी और ब्रेकेज की ज़िम्मेदारी" },
      { en: "Regular doctor visits", hi: "डॉक्टरों से नियमित संपर्क" },
      { en: "Orders on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Ask for the product list", hi: "प्रोडक्ट लिस्ट माँगें", desc: "Message us; we share the range and a price list.", descHi: "मैसेज करें; हम रेंज और प्राइस लिस्ट भेजते हैं।" },
      { en: "Meet or discuss", hi: "मिलें या बात करें", desc: "A visit to your clinic, store or hospital to show samples and terms.", descHi: "आपके क्लिनिक, स्टोर या हॉस्पिटल पर विज़िट — सैंपल और शर्तें।" },
      { en: "Place the order", hi: "ऑर्डर दें", desc: "Send the order on WhatsApp; the stockist dispatches it.", descHi: "WhatsApp पर ऑर्डर भेजें; स्टॉकिस्ट डिस्पैच करता है।" },
      { en: "Regular supply", hi: "नियमित सप्लाई", desc: "Repeat orders, follow-up visits and support on expiry or returns.", descHi: "रिपीट ऑर्डर, फ़ॉलो-अप विज़िट और एक्सपायरी-रिटर्न में सहयोग।" },
    ],
    faq: [
      { q: "Which products do you have?", qHi: "कौन से प्रोडक्ट हैं?", a: "Message us on WhatsApp for the product list and the segments we cover.", aHi: "प्रोडक्ट लिस्ट और सेगमेंट के लिए WhatsApp पर मैसेज करें।" },
      { q: "Are the medicines from a licensed unit?", qHi: "क्या दवाइयाँ लाइसेंस्ड यूनिट की हैं?", a: "Yes, every product is made in a licensed manufacturing unit with a proper batch and expiry.", aHi: "हाँ, हर प्रोडक्ट लाइसेंस्ड यूनिट में बनता है, बैच और एक्सपायरी के साथ।" },
      { q: "How do I order as a chemist?", qHi: "केमिस्ट कैसे ऑर्डर करें?", a: "Send the order list on WhatsApp or to our representative; it comes through your area stockist.", aHi: "WhatsApp या हमारे रिप्रेज़ेंटेटिव को ऑर्डर लिस्ट भेजें; आपके इलाक़े के स्टॉकिस्ट से आता है।" },
      { q: "What about expiry and breakage?", qHi: "एक्सपायरी और ब्रेकेज का क्या?", a: "Near-expiry and damaged stock is taken back or replaced as per company policy; ask our representative.", aHi: "एक्सपायरी के करीब और टूटा स्टॉक कंपनी नियम के अनुसार वापस या रिप्लेस होता है; रिप्रेज़ेंटेटिव से पूछें।" },
      { q: "Do you give stockist or franchise?", qHi: "स्टॉकिस्ट या फ़्रेंचाइज़ी मिलेगी?", a: "Openings depend on the area; message us your city and we will share the terms.", aHi: "इलाक़े पर निर्भर है; अपना शहर बताएँ, हम शर्तें भेज देंगे।" },
      { q: "Do you supply to hospitals?", qHi: "हॉस्पिटल को सप्लाई करते हैं?", a: "Yes, hospitals, nursing homes and clinics can order in bulk; ask for institutional rates.", aHi: "हाँ, हॉस्पिटल, नर्सिंग होम और क्लिनिक थोक में ऑर्डर कर सकते हैं; संस्थागत रेट पूछें।" },
      { q: "What are the payment terms?", qHi: "पेमेंट की शर्तें क्या हैं?", a: "Through the stockist, as per the usual trade terms; details are shared when you order.", aHi: "स्टॉकिस्ट के ज़रिए, ट्रेड की सामान्य शर्तों पर; ऑर्डर के समय बता देते हैं।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best quality", "world class", "customer satisfaction"],
  },

  gym: {
    explain: [
      "what you offer — gym, cardio, yoga, zumba, personal training, group classes",
      "who it is for — beginners, working people, women, seniors; morning and evening batches",
      "trainers, equipment, hygiene and safety on the floor",
      "plans — monthly / quarterly / yearly, trial session, timings",
    ],
    services: [
      { en: "Gym & weight training", hi: "जिम और वेट ट्रेनिंग", desc: "Free weights, machines and cardio with a trainer on the floor.", descHi: "फ़्री वेट, मशीनें और कार्डियो, फ़्लोर पर ट्रेनर के साथ।" },
      { en: "Personal training", hi: "पर्सनल ट्रेनिंग", desc: "One-to-one sessions with a plan made for your goal.", descHi: "आपके लक्ष्य के हिसाब से प्लान, एक-एक करके सेशन।" },
      { en: "Yoga classes", hi: "योग क्लास", desc: "Morning and evening batches for flexibility, breathing and calm.", descHi: "लचीलापन, साँस और शांति के लिए सुबह-शाम बैच।" },
      { en: "Group classes", hi: "ग्रुप क्लास", desc: "Zumba, aerobics and functional training in a group.", descHi: "ग्रुप में ज़ुम्बा, एरोबिक्स और फ़ंक्शनल ट्रेनिंग।" },
      { en: "Diet guidance", hi: "डाइट गाइडेंस", desc: "Simple eating advice to go with your workout.", descHi: "वर्कआउट के साथ आसान खान-पान की सलाह।" },
      { en: "Ladies' batch", hi: "महिलाओं का बैच", desc: "Separate timings or sections for women, with a lady trainer where available.", descHi: "महिलाओं के लिए अलग समय या सेक्शन, जहाँ हो लेडी ट्रेनर।" },
      { en: "Trial session", hi: "ट्रायल सेशन", desc: "Try a session before you take a plan.", descHi: "प्लान लेने से पहले एक सेशन आज़माएँ।" },
    ],
    whyUs: [
      { en: "Trainer on the floor", hi: "फ़्लोर पर हमेशा ट्रेनर" },
      { en: "Clean, well-kept equipment", hi: "साफ़, सही हालत में मशीनें" },
      { en: "Beginners made comfortable", hi: "शुरुआत करने वालों का ध्यान" },
      { en: "Morning and evening batches", hi: "सुबह और शाम के बैच" },
      { en: "Plan made for your goal", hi: "आपके लक्ष्य का प्लान" },
      { en: "Correct form taught first", hi: "पहले सही तरीक़ा सिखाते हैं" },
      { en: "Trial before you join", hi: "जॉइन से पहले ट्रायल" },
    ],
    steps: [
      { en: "Visit or message", hi: "आइए या मैसेज करें", desc: "Drop in to see the gym or ask for timings on WhatsApp.", descHi: "जिम देखने आइए या WhatsApp पर समय पूछिए।" },
      { en: "Take a trial", hi: "ट्रायल लें", desc: "A session with a trainer to see how it feels.", descHi: "ट्रेनर के साथ एक सेशन, देखिए कैसा लगता है।" },
      { en: "Pick a plan", hi: "प्लान चुनें", desc: "Monthly or longer, gym, yoga or both; join from the next day.", descHi: "महीने का या लंबा, जिम, योग या दोनों; अगले दिन से शुरू।" },
      { en: "Train regularly", hi: "नियमित ट्रेनिंग", desc: "Your plan is reviewed as you progress; keep showing up.", descHi: "सुधार के साथ प्लान बदलता है; बस आते रहिए।" },
    ],
    faq: [
      { q: "What are the timings?", qHi: "समय क्या है?", a: "Morning and evening batches; see this page or message us for today's timings.", aHi: "सुबह और शाम के बैच; इसी पेज पर देखें या WhatsApp पर पूछें।" },
      { q: "I am a complete beginner — is that okay?", qHi: "मैं बिल्कुल नया हूँ — चलेगा?", a: "Yes, most members start as beginners; the trainer starts you slowly and teaches the right form.", aHi: "हाँ, ज़्यादातर लोग नए ही आते हैं; ट्रेनर धीरे-धीरे शुरू कराते हैं और सही तरीक़ा सिखाते हैं।" },
      { q: "Is there a separate batch for women?", qHi: "महिलाओं के लिए अलग बैच है?", a: "Ask us — many gyms keep a ladies' timing or section; we will tell you ours.", aHi: "पूछ लें — महिलाओं का अलग समय या सेक्शन होता है; हम अपना बताएँगे।" },
      { q: "Can I take a trial first?", qHi: "पहले ट्रायल ले सकते हैं?", a: "Yes, message us and come for a trial session before choosing a plan.", aHi: "हाँ, मैसेज करके प्लान चुनने से पहले एक ट्रायल सेशन लें।" },
      { q: "Do you give a diet plan?", qHi: "डाइट प्लान देते हैं?", a: "Basic diet guidance comes with training; for a medical condition, consult your doctor too.", aHi: "ट्रेनिंग के साथ बुनियादी डाइट सलाह मिलती है; कोई बीमारी हो तो डॉक्टर से भी पूछें।" },
      { q: "Can I pause my membership?", qHi: "मेंबरशिप रोक सकते हैं?", a: "For travel or illness, tell us in advance and the days are adjusted where possible.", aHi: "सफ़र या बीमारी में पहले बता दें, जहाँ संभव हो दिन एडजस्ट होते हैं।" },
      { q: "How do I pay?", qHi: "फ़ीस कैसे दें?", a: "Cash or UPI, monthly or for a longer plan; ask us the current fees.", aHi: "नक़द या UPI, महीने का या लंबे प्लान का; फ़ीस WhatsApp पर पूछ लें।" },
    ],
    generic: ["connect with us", "explore options", "transform your body", "guaranteed results", "best gym", "fitness for all"],
  },

  salon: {
    explain: [
      "what is done — haircut, hair colour, facial, waxing, threading, manicure-pedicure, bridal makeup; for women / men / unisex",
      "hygiene — clean towels, fresh disposables, branded products",
      "bridal and party packages with trial; home service if any",
      "appointment on WhatsApp and timings",
    ],
    services: [
      { en: "Haircut & styling", hi: "हेयरकट और स्टाइलिंग", desc: "Cuts, blow-dry and styling for every face and occasion.", descHi: "हर चेहरे और मौक़े के लिए कट, ब्लो-ड्राई और स्टाइलिंग।" },
      { en: "Hair colour & treatments", hi: "हेयर कलर और ट्रीटमेंट", desc: "Colour, highlights, smoothening and hair spa with good products.", descHi: "अच्छे प्रोडक्ट से कलर, हाइलाइट, स्मूदनिंग और हेयर स्पा।" },
      { en: "Facial & clean-up", hi: "फ़ेशियल और क्लीन-अप", desc: "Facials and clean-ups suited to your skin.", descHi: "आपकी त्वचा के हिसाब से फ़ेशियल और क्लीन-अप।" },
      { en: "Waxing & threading", hi: "वैक्सिंग और थ्रेडिंग", desc: "Waxing, threading and eyebrows with fresh strips every time.", descHi: "वैक्सिंग, थ्रेडिंग और आइब्रो, हर बार नई स्ट्रिप।" },
      { en: "Manicure & pedicure", hi: "मैनीक्योर और पेडीक्योर", desc: "Hand and foot care, nail shaping and polish.", descHi: "हाथ-पैर की देखभाल, नाख़ून की शेप और पॉलिश।" },
      { en: "Bridal & party makeup", hi: "ब्राइडल और पार्टी मेकअप", desc: "Bridal packages, engagement and party looks, with trials.", descHi: "ब्राइडल पैकेज, सगाई और पार्टी लुक, ट्रायल के साथ।" },
      { en: "Home service", hi: "होम सर्विस", desc: "Selected services at your home for functions — ask us.", descHi: "फ़ंक्शन के लिए चुनिंदा सर्विस आपके घर पर — पूछ लें।" },
    ],
    whyUs: [
      { en: "Clean towels, fresh disposables", hi: "साफ़ तौलिये, नए डिस्पोज़ेबल" },
      { en: "Branded products only", hi: "सिर्फ़ ब्रांडेड प्रोडक्ट" },
      { en: "Trained, experienced staff", hi: "ट्रेंड, अनुभवी स्टाफ़" },
      { en: "Look suggested for your face", hi: "आपके चेहरे के हिसाब से लुक" },
      { en: "Appointment on WhatsApp", hi: "WhatsApp पर अपॉइंटमेंट" },
      { en: "Bridal packages with trial", hi: "ट्रायल के साथ ब्राइडल पैकेज" },
      { en: "Price told before service", hi: "सर्विस से पहले दाम साफ़" },
    ],
    steps: [
      { en: "Book on WhatsApp", hi: "WhatsApp पर बुक करें", desc: "Tell us the service and a time that suits you.", descHi: "सर्विस और सुविधाजनक समय बताएँ।" },
      { en: "Tell us the look", hi: "लुक बताएँ", desc: "Share a picture or the occasion; we suggest what suits you.", descHi: "फ़ोटो या मौक़ा बताएँ; हम सुझाते हैं क्या जँचेगा।" },
      { en: "Sit back", hi: "आराम से बैठिए", desc: "Service done with clean tools and good products.", descHi: "साफ़ टूल्स और अच्छे प्रोडक्ट से सर्विस।" },
      { en: "After-care tips", hi: "देखभाल के टिप्स", desc: "Simple advice to keep the hair or skin looking good.", descHi: "बाल या त्वचा ठीक रखने की आसान सलाह।" },
    ],
    faq: [
      { q: "Do I need an appointment?", qHi: "अपॉइंटमेंट ज़रूरी है?", a: "Walk-ins are welcome, but a WhatsApp appointment saves waiting, especially on weekends.", aHi: "सीधे आ सकते हैं, पर WhatsApp पर अपॉइंटमेंट लेने से इंतज़ार नहीं होता, ख़ासकर वीकेंड पर।" },
      { q: "Which products do you use?", qHi: "कौन से प्रोडक्ट इस्तेमाल करते हैं?", a: "Known branded products; tell us if your skin is sensitive or you prefer a brand.", aHi: "जाने-माने ब्रांड; त्वचा संवेदनशील हो या कोई ब्रांड पसंद हो तो बताएँ।" },
      { q: "Do you do bridal makeup?", qHi: "ब्राइडल मेकअप करते हैं?", a: "Yes, with a trial before the day; message us the date to check availability.", aHi: "हाँ, शादी से पहले ट्रायल के साथ; तारीख़ बताकर उपलब्धता पूछ लें।" },
      { q: "Is home service available?", qHi: "होम सर्विस मिलती है?", a: "For functions and bridal work, selected services can be done at home; ask us.", aHi: "फ़ंक्शन और ब्राइडल के लिए कुछ सर्विस घर पर हो सकती हैं; पूछ लें।" },
      { q: "Is it for women only?", qHi: "सिर्फ़ महिलाओं के लिए है?", a: "Ask us — we will tell you whether we serve women, men or both.", aHi: "पूछ लें — हम बताएँगे महिला, पुरुष या दोनों के लिए है।" },
      { q: "How much does a service cost?", qHi: "सर्विस का दाम कितना है?", a: "Message us the service and we will share the rate before you come.", aHi: "सर्विस बताकर मैसेज करें, आने से पहले दाम बता देंगे।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash and UPI at the parlour; an advance for bridal bookings.", aHi: "पार्लर पर नक़द और UPI; ब्राइडल बुकिंग पर एडवांस।" },
    ],
    generic: ["connect with us", "explore options", "look beautiful", "best salon", "quality service", "customer satisfaction"],
  },

  spa: {
    explain: [
      "the therapies — body massage, head massage, foot reflexology, scrub, aromatherapy, steam as applicable",
      "the setting — clean, private rooms, trained therapists, male / female therapists on request",
      "who it is for — relaxation, tiredness, stiffness after work or travel",
      "booking on WhatsApp, timings, packages, couple and group bookings",
    ],
    services: [
      { en: "Body massage", hi: "बॉडी मसाज", desc: "Full-body massage with oil to relax muscles and ease tiredness.", descHi: "तेल से पूरे शरीर की मसाज, थकान और अकड़न में आराम।" },
      { en: "Head & shoulder massage", hi: "सिर और कंधे की मसाज", desc: "A quick session for tension and tired eyes.", descHi: "तनाव और थकी आँखों के लिए छोटा सेशन।" },
      { en: "Foot reflexology", hi: "फ़ुट रिफ़्लेक्सोलॉजी", desc: "Pressure-point foot massage after long days of standing or walking.", descHi: "लंबे दिन के बाद पैरों की प्रेशर-पॉइंट मसाज।" },
      { en: "Scrub & body polish", hi: "स्क्रब और बॉडी पॉलिश", desc: "Exfoliation and moisturising for soft, fresh skin.", descHi: "मुलायम, ताज़ा त्वचा के लिए स्क्रब और मॉइस्चर।" },
      { en: "Steam & sauna", hi: "स्टीम और सॉना", desc: "Steam before or after a therapy, where available.", descHi: "थेरेपी से पहले या बाद में स्टीम, जहाँ उपलब्ध।" },
      { en: "Couple & group sessions", hi: "कपल और ग्रुप सेशन", desc: "Side-by-side sessions for couples, friends or a bridal party.", descHi: "कपल, दोस्तों या ब्राइडल पार्टी के लिए साथ-साथ सेशन।" },
      { en: "Packages & gift vouchers", hi: "पैकेज और गिफ़्ट वाउचर", desc: "Monthly packages and vouchers to gift someone a break.", descHi: "मासिक पैकेज और किसी को आराम गिफ़्ट करने के लिए वाउचर।" },
    ],
    whyUs: [
      { en: "Trained, professional therapists", hi: "ट्रेंड, प्रोफ़ेशनल थेरेपिस्ट" },
      { en: "Clean, private rooms", hi: "साफ़, प्राइवेट कमरे" },
      { en: "Fresh linen for every guest", hi: "हर मेहमान के लिए ताज़ी चादर" },
      { en: "Good oils and products", hi: "अच्छे तेल और प्रोडक्ट" },
      { en: "Lady therapist for ladies", hi: "महिलाओं के लिए लेडी थेरेपिस्ट" },
      { en: "Pressure adjusted to you", hi: "दबाव आपके हिसाब से" },
      { en: "Booking on WhatsApp", hi: "WhatsApp पर बुकिंग" },
    ],
    steps: [
      { en: "Book a slot", hi: "स्लॉट बुक करें", desc: "Message us the therapy and a time; we confirm the slot.", descHi: "थेरेपी और समय बताएँ; हम स्लॉट कन्फ़र्म करते हैं।" },
      { en: "Tell us your needs", hi: "अपनी ज़रूरत बताएँ", desc: "Stiff back, tiredness, light or firm pressure — the therapist adjusts.", descHi: "पीठ की अकड़न, थकान, हल्का या तेज़ दबाव — थेरेपिस्ट उसी हिसाब से।" },
      { en: "Relax", hi: "आराम करें", desc: "A private room, clean linen and an unhurried session.", descHi: "प्राइवेट कमरा, साफ़ चादर और बिना जल्दी का सेशन।" },
      { en: "Tea and go", hi: "चाय पीकर जाएँ", desc: "Rest a little, drink water and leave refreshed.", descHi: "थोड़ा बैठें, पानी पिएँ और तरोताज़ा निकलें।" },
    ],
    faq: [
      { q: "Do I need to book in advance?", qHi: "पहले बुक करना ज़रूरी है?", a: "Yes, please — rooms and therapists are limited; message us on WhatsApp for a slot.", aHi: "हाँ — कमरे और थेरेपिस्ट सीमित हैं; WhatsApp पर स्लॉट ले लें।" },
      { q: "Can I choose a male or female therapist?", qHi: "पुरुष या महिला थेरेपिस्ट चुन सकते हैं?", a: "Yes, tell us at the time of booking and we arrange accordingly.", aHi: "हाँ, बुकिंग के समय बता दें, उसी हिसाब से व्यवस्था होती है।" },
      { q: "Is it hygienic?", qHi: "साफ़-सफ़ाई कैसी है?", a: "Fresh linen and towels for every guest, and rooms cleaned between sessions.", aHi: "हर मेहमान के लिए ताज़ी चादर और तौलिया, हर सेशन के बाद कमरा साफ़।" },
      { q: "Which massage should I take?", qHi: "कौन सी मसाज लूँ?", a: "Tell us how you feel — tired, stiff, stressed — and we suggest a therapy.", aHi: "बताएँ कैसा महसूस हो रहा है — थकान, अकड़न, तनाव — हम थेरेपी सुझाएँगे।" },
      { q: "Is massage okay if I have a medical condition?", qHi: "कोई बीमारी हो तो मसाज ठीक है?", a: "Tell us before the session; in pregnancy, after surgery or with a health condition, ask your doctor first.", aHi: "सेशन से पहले बताएँ; गर्भावस्था, ऑपरेशन के बाद या किसी बीमारी में पहले डॉक्टर से पूछें।" },
      { q: "Do you have packages?", qHi: "पैकेज हैं?", a: "Yes, monthly packages and gift vouchers; message us for the current options.", aHi: "हाँ, मासिक पैकेज और गिफ़्ट वाउचर; मौजूदा विकल्प WhatsApp पर पूछें।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the spa; packages are paid in advance.", aHi: "स्पा पर नक़द, UPI और कार्ड; पैकेज का भुगतान पहले।" },
    ],
    generic: ["connect with us", "explore options", "ultimate relaxation", "luxury experience", "best spa", "quality service"],
  },

  water: {
    explain: [
      "what you sell — RO / UV purifiers, alkaline water ionizers, commercial plants, filters and spares — and the brands you are authorised for",
      "demo at home, installation, service and AMC, genuine filters",
      "who it is for — homes, offices, schools, shops, restaurants",
      "how to buy: demo, EMI / finance help, dealer and sub-dealer enquiries",
    ],
    services: [
      { en: "Home demo", hi: "घर पर डेमो", desc: "See the machine working on your tap water before you decide.", descHi: "फ़ैसले से पहले अपने नल के पानी पर मशीन चलाकर देखें।" },
      { en: "Water testing", hi: "पानी की जाँच", desc: "TDS and basic checks of your water to suggest the right system.", descHi: "सही सिस्टम सुझाने के लिए आपके पानी का TDS और बुनियादी जाँच।" },
      { en: "Installation", hi: "इंस्टॉलेशन", desc: "Fitted by a trained technician at your home or office.", descHi: "ट्रेंड टेक्नीशियन द्वारा घर या ऑफ़िस में फ़िटिंग।" },
      { en: "Service & AMC", hi: "सर्विस और AMC", desc: "Periodic servicing, repairs and annual maintenance plans.", descHi: "समय-समय पर सर्विस, मरम्मत और सालाना मेंटेनेंस प्लान।" },
      { en: "Genuine filters & spares", hi: "असली फ़िल्टर और स्पेयर", desc: "Filter and membrane replacement with company parts.", descHi: "कंपनी के असली पार्ट्स से फ़िल्टर और मेम्ब्रेन बदलना।" },
      { en: "Commercial & office systems", hi: "कमर्शियल और ऑफ़िस सिस्टम", desc: "Coolers, plants and dispensers for offices, schools and shops.", descHi: "ऑफ़िस, स्कूल और दुकानों के लिए कूलर, प्लांट और डिस्पेंसर।" },
      { en: "EMI & dealer enquiries", hi: "EMI और डीलर पूछताछ", desc: "Easy EMI help for buyers; dealer and sub-dealer openings — ask us.", descHi: "ख़रीदारों के लिए आसान EMI; डीलर और सब-डीलर के लिए पूछ लें।" },
    ],
    whyUs: [
      { en: "Authorised, genuine products", hi: "अधिकृत, असली प्रोडक्ट" },
      { en: "Demo before you buy", hi: "ख़रीदने से पहले डेमो" },
      { en: "Trained service technicians", hi: "ट्रेंड सर्विस टेक्नीशियन" },
      { en: "Right system for your water", hi: "आपके पानी के लिए सही सिस्टम" },
      { en: "Company warranty and bill", hi: "कंपनी वारंटी और पक्का बिल" },
      { en: "Service call on WhatsApp", hi: "WhatsApp पर सर्विस कॉल" },
      { en: "Filters changed on time", hi: "फ़िल्टर समय पर बदलते हैं" },
    ],
    steps: [
      { en: "Book a demo", hi: "डेमो बुक करें", desc: "Message us your area; we come with the machine.", descHi: "अपना इलाक़ा बताएँ; हम मशीन लेकर आते हैं।" },
      { en: "Test and choose", hi: "जाँचें और चुनें", desc: "We test your water, show the options and explain the difference.", descHi: "आपका पानी जाँचते हैं, विकल्प दिखाते हैं और फ़र्क़ समझाते हैं।" },
      { en: "Install", hi: "इंस्टॉल", desc: "Delivered and fitted at a time that suits you, with bill and warranty.", descHi: "आपके समय पर डिलीवरी और फ़िटिंग, बिल और वारंटी के साथ।" },
      { en: "Service on time", hi: "समय पर सर्विस", desc: "Reminders for filter change; one message for any service.", descHi: "फ़िल्टर बदलने का रिमाइंडर; किसी भी सर्विस के लिए एक मैसेज।" },
    ],
    faq: [
      { q: "Which purifier is right for my home?", qHi: "मेरे घर के लिए कौन सा प्यूरीफ़ायर सही है?", a: "It depends on your water source and TDS; we test it at the demo and suggest.", aHi: "आपके पानी के सोर्स और TDS पर निर्भर है; डेमो पर जाँचकर सुझाते हैं।" },
      { q: "Is there a home demo?", qHi: "घर पर डेमो मिलेगा?", a: "Yes, message us your area and a convenient time for the demo.", aHi: "हाँ, अपना इलाक़ा और सुविधाजनक समय WhatsApp पर बताएँ।" },
      { q: "What about installation and warranty?", qHi: "इंस्टॉलेशन और वारंटी का क्या?", a: "Installation is done by our technician; company warranty and a proper bill come with the product.", aHi: "इंस्टॉलेशन हमारा टेक्नीशियन करता है; प्रोडक्ट के साथ कंपनी वारंटी और पक्का बिल।" },
      { q: "How often do filters need changing?", qHi: "फ़िल्टर कितनी बार बदलने पड़ते हैं?", a: "It depends on the water and usage; we remind you when it is due.", aHi: "पानी और इस्तेमाल पर निर्भर है; समय आने पर हम याद दिला देते हैं।" },
      { q: "Do you repair other brands?", qHi: "दूसरे ब्रांड की मरम्मत करते हैं?", a: "Ask us on WhatsApp with the brand and problem; we tell you if we can help.", aHi: "ब्रांड और समस्या WhatsApp पर बताएँ; हम बता देंगे मदद हो सकती है या नहीं।" },
      { q: "Is EMI available?", qHi: "EMI मिलती है?", a: "Yes, on most systems through finance partners or cards; ask us the options.", aHi: "हाँ, ज़्यादातर सिस्टम पर फ़ाइनेंस पार्टनर या कार्ड से; विकल्प पूछ लें।" },
      { q: "Is ionized or alkaline water good for health?", qHi: "आयोनाइज़्ड / अल्कलाइन पानी सेहत के लिए अच्छा है?", a: "We can explain how the machine works and what it changes in the water; for health questions, please consult your doctor.", aHi: "मशीन कैसे काम करती है और पानी में क्या बदलता है, हम समझा सकते हैं; सेहत के सवाल के लिए डॉक्टर से पूछें।" },
    ],
    generic: ["connect with us", "explore options", "pure water", "healthy life", "best quality", "quality products"],
  },

  wellness: {
    explain: [
      "what you sell — supplements, herbal and nutrition products, personal care, health devices — and the brands",
      "genuine products with proper bill, batch and expiry; guidance on how to use them",
      "who it is for — families, fitness, seniors, daily wellness",
      "how to order: WhatsApp, delivery, and distributor / reseller enquiries",
    ],
    services: [
      { en: "Nutrition & supplements", hi: "न्यूट्रिशन और सप्लीमेंट", desc: "Protein, vitamins and daily nutrition products from known brands.", descHi: "जाने-माने ब्रांड के प्रोटीन, विटामिन और रोज़ के न्यूट्रिशन प्रोडक्ट।" },
      { en: "Herbal & ayurvedic products", hi: "हर्बल और आयुर्वेदिक प्रोडक्ट", desc: "Juices, powders and herbal products for daily use.", descHi: "रोज़ के इस्तेमाल के लिए जूस, चूर्ण और हर्बल प्रोडक्ट।" },
      { en: "Personal care", hi: "पर्सनल केयर", desc: "Skin, hair and oral care products.", descHi: "त्वचा, बाल और मुँह की देखभाल के प्रोडक्ट।" },
      { en: "Health devices", hi: "हेल्थ डिवाइस", desc: "BP monitors, glucometers, weighing scales and similar items.", descHi: "BP मशीन, ग्लूकोमीटर, वज़न मशीन और ऐसी चीज़ें।" },
      { en: "Product guidance", hi: "प्रोडक्ट गाइडेंस", desc: "Which product suits you and how to use it — ask before buying.", descHi: "कौन सा प्रोडक्ट सही है और कैसे लें — ख़रीदने से पहले पूछें।" },
      { en: "Home delivery", hi: "होम डिलीवरी", desc: "Order on WhatsApp; delivered in the city or couriered outside.", descHi: "WhatsApp पर ऑर्डर; शहर में डिलीवरी, बाहर कूरियर।" },
      { en: "Distributor & bulk orders", hi: "डिस्ट्रीब्यूटर और थोक ऑर्डर", desc: "Bulk, gifting and reseller enquiries — ask us the terms.", descHi: "थोक, गिफ़्टिंग और रीसेलर के लिए — शर्तें पूछ लें।" },
    ],
    whyUs: [
      { en: "Genuine products, proper bill", hi: "असली प्रोडक्ट, पक्का बिल" },
      { en: "Fresh stock, expiry checked", hi: "ताज़ा स्टॉक, एक्सपायरी जाँची हुई" },
      { en: "Honest guidance, no pushing", hi: "ईमानदार सलाह, ज़बरदस्ती नहीं" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
      { en: "Delivery at home", hi: "घर तक डिलीवरी" },
      { en: "Known brands only", hi: "सिर्फ़ जाने-माने ब्रांड" },
      { en: "Help after you buy", hi: "ख़रीदने के बाद भी मदद" },
    ],
    steps: [
      { en: "Tell us your need", hi: "अपनी ज़रूरत बताएँ", desc: "Message what you are looking for, or the product name.", descHi: "क्या चाहिए या प्रोडक्ट का नाम WhatsApp पर भेजें।" },
      { en: "Get the right product", hi: "सही प्रोडक्ट चुनें", desc: "We suggest options, share details and the price.", descHi: "हम विकल्प सुझाते हैं, जानकारी और दाम भेजते हैं।" },
      { en: "Order and pay", hi: "ऑर्डर करें और भुगतान", desc: "Confirm on WhatsApp; pay by UPI or on delivery.", descHi: "WhatsApp पर कन्फ़र्म करें; UPI या डिलीवरी पर भुगतान।" },
      { en: "Delivered, with support", hi: "डिलीवरी और सहयोग", desc: "Delivered or couriered; ask us any time about how to use it.", descHi: "डिलीवरी या कूरियर; इस्तेमाल के बारे में कभी भी पूछें।" },
    ],
    faq: [
      { q: "Are the products genuine?", qHi: "क्या प्रोडक्ट असली हैं?", a: "Yes, sourced from the company or authorised channels, with batch, expiry and a proper bill.", aHi: "हाँ, कंपनी या अधिकृत चैनल से, बैच, एक्सपायरी और पक्के बिल के साथ।" },
      { q: "Will this product help my condition?", qHi: "क्या यह प्रोडक्ट मेरी बीमारी में काम करेगा?", a: "These are wellness products, not medicines; for any health condition, please consult your doctor before taking them.", aHi: "ये वेलनेस प्रोडक्ट हैं, दवा नहीं; किसी बीमारी में लेने से पहले डॉक्टर से पूछें।" },
      { q: "Can I take it with my medicines?", qHi: "दवा के साथ ले सकते हैं?", a: "Ask your doctor first and read the label; we can share the ingredients on WhatsApp.", aHi: "पहले डॉक्टर से पूछें और लेबल पढ़ें; सामग्री हम WhatsApp पर भेज सकते हैं।" },
      { q: "Do you deliver?", qHi: "डिलीवरी करते हैं?", a: "Yes, within the city, and by courier outside; message us your address.", aHi: "हाँ, शहर में डिलीवरी और बाहर कूरियर; पता WhatsApp पर भेजें।" },
      { q: "Can I return or exchange?", qHi: "वापसी या बदली हो सकती है?", a: "Sealed, unused products can be exchanged soon after purchase; ask us before you come.", aHi: "सील बंद, बिना इस्तेमाल प्रोडक्ट ख़रीद के तुरंत बाद बदल सकते हैं; आने से पहले पूछ लें।" },
      { q: "Can I become a distributor?", qHi: "डिस्ट्रीब्यूटर बन सकते हैं?", a: "Message us your city and we share the current terms and the product list.", aHi: "अपना शहर बताएँ; हम मौजूदा शर्तें और प्रोडक्ट लिस्ट भेज देंगे।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, cash on delivery in the city, or bank transfer for courier orders.", aHi: "UPI, शहर में डिलीवरी पर नक़द, कूरियर ऑर्डर पर बैंक ट्रांसफ़र।" },
    ],
    generic: ["connect with us", "explore options", "healthy life", "miracle product", "guaranteed results", "quality products", "best quality"],
  },
};

/** General entry for the Health group — used for any health / beauty / wellness key that has no entry above. */
export const HEALTH_DEFAULT: TradeData = {
  explain: [
    "what the business does in health, beauty or wellness and who it serves",
    "hygiene, trained staff and genuine products",
    "timings and how to book or order — WhatsApp, walk-in",
    "what to bring or share on the first visit",
  ],
  services: [
    { en: "Consultation", hi: "परामर्श", desc: "Tell us your need; we guide you to the right service.", descHi: "अपनी ज़रूरत बताएँ; हम सही सर्विस बताते हैं।" },
    { en: "Appointments on WhatsApp", hi: "WhatsApp पर अपॉइंटमेंट", desc: "Book a time and skip the wait.", descHi: "समय बुक करें, इंतज़ार नहीं।" },
    { en: "Regular check-ups & follow-up", hi: "रूटीन जाँच और फ़ॉलो-अप", desc: "Review visits so your progress is tracked.", descHi: "रिव्यू विज़िट ताकि सुधार पर नज़र रहे।" },
    { en: "Products & supplies", hi: "प्रोडक्ट और सामान", desc: "Genuine products related to the service, with a bill.", descHi: "सर्विस से जुड़े असली प्रोडक्ट, बिल के साथ।" },
    { en: "Home service", hi: "होम सर्विस", desc: "Selected services at home where possible — ask us.", descHi: "जहाँ संभव हो चुनिंदा सर्विस घर पर — पूछ लें।" },
    { en: "Packages & plans", hi: "पैकेज और प्लान", desc: "Monthly or multi-session plans for regular care.", descHi: "नियमित देखभाल के लिए मासिक या कई-सेशन प्लान।" },
    { en: "Guidance & after-care", hi: "सलाह और देखभाल", desc: "Simple advice to follow at home between visits.", descHi: "विज़िट के बीच घर पर मानने की आसान सलाह।" },
  ],
  whyUs: [
    { en: "Clean and hygienic", hi: "साफ़-सफ़ाई का ध्यान" },
    { en: "Trained, caring staff", hi: "ट्रेंड, ध्यान रखने वाला स्टाफ़" },
    { en: "Time given to you", hi: "आपको पूरा समय" },
    { en: "Honest advice", hi: "ईमानदार सलाह" },
    { en: "Genuine products", hi: "असली प्रोडक्ट" },
    { en: "Book on WhatsApp", hi: "WhatsApp पर बुकिंग" },
  ],
  steps: [
    { en: "Message us", hi: "मैसेज करें", desc: "Tell us your need and a convenient time.", descHi: "ज़रूरत और सुविधाजनक समय बताएँ।" },
    { en: "First visit", hi: "पहली विज़िट", desc: "We understand your need and explain the options.", descHi: "हम ज़रूरत समझते हैं और विकल्प बताते हैं।" },
    { en: "Service or treatment", hi: "सर्विस या इलाज", desc: "Done with care, hygiene and clear instructions.", descHi: "ध्यान, सफ़ाई और साफ़ निर्देशों के साथ।" },
    { en: "Follow-up", hi: "फ़ॉलो-अप", desc: "Review when advised, or message if something changes.", descHi: "बताए समय पर रिव्यू, या कुछ बदले तो मैसेज।" },
  ],
  faq: [
    { q: "Do I need an appointment?", qHi: "अपॉइंटमेंट ज़रूरी है?", a: "Walk-ins are usually fine, but a WhatsApp appointment saves waiting.", aHi: "सीधे आ सकते हैं, पर WhatsApp पर अपॉइंटमेंट लेने से इंतज़ार नहीं होता।" },
    { q: "What are the timings?", qHi: "समय क्या है?", a: "See the timings on this page, or message us to check before coming.", aHi: "इसी पेज पर समय देखें, या आने से पहले मैसेज करके पूछ लें।" },
    { q: "What should I bring on the first visit?", qHi: "पहली बार क्या लाना है?", a: "Any old reports or details of what you are already using; the rest we ask on the day.", aHi: "पुरानी रिपोर्ट या जो चल रहा है उसकी जानकारी; बाक़ी उसी दिन पूछ लेते हैं।" },
    { q: "Is it okay for children and the elderly?", qHi: "बच्चों और बुज़ुर्गों के लिए ठीक है?", a: "Tell us the age and any health condition; for medical questions, please consult your doctor.", aHi: "उम्र और कोई बीमारी हो तो बताएँ; मेडिकल सवाल के लिए डॉक्टर से पूछें।" },
    { q: "Is home service available?", qHi: "होम सर्विस मिलती है?", a: "For some services, yes; message us what you need and your area.", aHi: "कुछ सर्विस के लिए हाँ; क्या चाहिए और इलाक़ा WhatsApp पर बताएँ।" },
    { q: "How much will it cost?", qHi: "खर्च कितना होगा?", a: "It depends on the service; message us and we share the rate before you come.", aHi: "सर्विस पर निर्भर है; मैसेज करें, आने से पहले दाम बता देंगे।" },
    { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash and UPI at the centre, cards where available; packages are paid in advance.", aHi: "सेंटर पर नक़द और UPI, जहाँ हो कार्ड; पैकेज का भुगतान पहले।" },
  ],
  generic: ["connect with us", "explore options", "best in town", "quality service", "customer satisfaction", "healthy life"],
};
