// Agriculture & industry trades: krishi kendra (seeds / fertiliser), dairy, manufacturer / factory, wholesale /
// trading, textile / sarees. See types.ts for the rules (no numbers, no claims; true of any decent business of the trade).
import type { TradeData } from "./types";

export const INDUSTRY: Record<string, TradeData> = {
  agri: {
    explain: [
      "what is stocked (seeds, fertiliser, pesticides, sprayers, drip and farm tools) and the crops of the area",
      "genuine, company-sealed stock with a bill for every purchase",
      "advice on what to use for which crop and season",
      "how to order: walk in, WhatsApp, delivery to the farm or village, season booking",
    ],
    services: [
      { en: "Seeds", hi: "बीज", desc: "Certified and hybrid seeds for the season's crops and vegetables.", descHi: "मौसम की फ़सलों और सब्ज़ियों के लिए प्रमाणित और हाइब्रिड बीज।" },
      { en: "Fertiliser & manure", hi: "खाद और उर्वरक", desc: "Urea, DAP, potash, micronutrients and organic manure, company-sealed.", descHi: "यूरिया, DAP, पोटाश, सूक्ष्म पोषक और जैविक खाद, कंपनी की सील में।" },
      { en: "Pesticides & crop protection", hi: "दवाई और फ़सल सुरक्षा", desc: "Insecticide, fungicide and weedicide with correct dose guidance.", descHi: "कीटनाशक, फफूंदनाशक और खरपतवारनाशक, सही मात्रा की सलाह के साथ।" },
      { en: "Sprayers & farm tools", hi: "स्प्रेयर और खेती के औज़ार", desc: "Sprayers, pipes, drip parts and hand tools, with spares.", descHi: "स्प्रेयर, पाइप, ड्रिप के पार्ट और हाथ के औज़ार, स्पेयर समेत।" },
      { en: "Crop advice", hi: "फ़सल की सलाह", desc: "Tell us the crop and problem; we suggest what to use and when.", descHi: "फ़सल और समस्या बताएँ; क्या और कब डालना है, हम बताते हैं।" },
      { en: "Delivery to the village", hi: "गाँव तक डिलीवरी", desc: "Bulk bags and season stock delivered to your farm or village.", descHi: "थोक बोरियाँ और सीज़न का माल आपके खेत या गाँव तक।" },
      { en: "Season booking", hi: "सीज़न की बुकिंग", desc: "Book seed and fertiliser ahead of sowing so stock is kept for you.", descHi: "बुवाई से पहले बीज-खाद बुक करें, आपका माल रखा रहेगा।" },
    ],
    whyUs: [
      { en: "Genuine, sealed company stock", hi: "असली, कंपनी-सील माल" },
      { en: "Bill with every purchase", hi: "हर ख़रीद पर बिल" },
      { en: "Advice for your crop", hi: "आपकी फ़सल के लिए सलाह" },
      { en: "Fresh seed, checked expiry", hi: "ताज़ा बीज, एक्सपायरी देखकर" },
      { en: "Stock ready in season", hi: "सीज़न में माल तैयार" },
      { en: "Delivery to the farm", hi: "खेत तक डिलीवरी" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Tell us the crop", hi: "फ़सल बताएँ", desc: "Crop, land size and what you need — on WhatsApp or at the shop.", descHi: "कौन सी फ़सल, कितनी ज़मीन और क्या चाहिए — WhatsApp पर या दुकान पर।" },
      { en: "We suggest and quote", hi: "हम सुझाव और दाम बताएँ", desc: "The right seed, dose and brand, with the price.", descHi: "सही बीज, मात्रा और ब्रांड, दाम के साथ।" },
      { en: "Pick up or get delivery", hi: "ले जाएँ या मँगवाएँ", desc: "Collect from the shop or we send it to the village.", descHi: "दुकान से ले जाएँ या हम गाँव तक भेज दें।" },
      { en: "Help through the season", hi: "सीज़न भर मदद", desc: "Any problem in the field, message a photo and ask.", descHi: "खेत में कोई दिक्कत हो तो फ़ोटो भेजकर पूछ लें।" },
    ],
    faq: [
      { q: "Is the seed and fertiliser genuine?", qHi: "बीज और खाद असली है?", a: "Yes, company-sealed stock bought from authorised distributors, with a bill for every purchase.", aHi: "हाँ, अधिकृत डिस्ट्रीब्यूटर से लिया कंपनी-सील माल, हर ख़रीद पर बिल।" },
      { q: "Which seed should I sow this season?", qHi: "इस सीज़न कौन सा बीज बोएँ?", a: "It depends on your soil, water and area — tell us the crop and land on WhatsApp and we will suggest.", aHi: "मिट्टी, पानी और इलाक़े पर निर्भर है — WhatsApp पर फ़सल और ज़मीन बताएँ, हम सुझाएँगे।" },
      { q: "Do you deliver to the village?", qHi: "गाँव तक डिलीवरी करते हैं?", a: "Yes, for bulk and season orders in the nearby villages; message us your location.", aHi: "हाँ, आसपास के गाँवों में थोक और सीज़न ऑर्डर पर; लोकेशन भेज दें।" },
      { q: "How much should I spray and when?", qHi: "कितना और कब छिड़काव करें?", a: "The dose is on the pack and we explain it at the time of sale; ask us if the problem is new.", aHi: "मात्रा पैक पर लिखी है और बेचते समय हम समझाते हैं; नई समस्या हो तो पूछ लें।" },
      { q: "Can I book stock before sowing?", qHi: "बुवाई से पहले माल बुक कर सकते हैं?", a: "Yes, message the items and quantity ahead of the season so your stock is kept aside.", aHi: "हाँ, सीज़न से पहले चीज़ें और मात्रा बता दें, आपका माल अलग रख देंगे।" },
      { q: "Do you keep organic options?", qHi: "जैविक विकल्प रखते हैं?", a: "Organic manure, bio-fertiliser and bio-pesticides are available; ask what suits your crop.", aHi: "जैविक खाद, बायो-फ़र्टिलाइज़र और बायो-कीटनाशक मिलते हैं; अपनी फ़सल के लिए पूछें।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash and UPI at the shop; ask us about season terms for regular farmers.", aHi: "दुकान पर नक़द और UPI; नियमित किसानों के लिए सीज़न की शर्तें पूछ लें।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best quality", "customer satisfaction"],
  },

  dairy: {
    explain: [
      "what is sold (cow / buffalo milk, dahi, paneer, ghee, khoa, chhach) and what is made in-house",
      "freshness and purity — milk from own or local cattle, nothing added",
      "daily home delivery with a monthly account; bulk supply to shops, hotels and functions",
      "morning and evening supply timings; how to start a subscription",
    ],
    services: [
      { en: "Fresh milk daily", hi: "रोज़ ताज़ा दूध", desc: "Cow and buffalo milk, morning and evening, straight from the dairy.", descHi: "गाय और भैंस का दूध, सुबह-शाम, सीधे डेयरी से।" },
      { en: "Home delivery subscription", hi: "घर पर रोज़ डिलीवरी", desc: "Milk at your door every day with a monthly account.", descHi: "रोज़ आपके दरवाज़े दूध, महीने का हिसाब।" },
      { en: "Paneer, dahi & chhach", hi: "पनीर, दही और छाछ", desc: "Made fresh at the dairy from the same milk.", descHi: "उसी दूध से डेयरी पर ताज़ा बना।" },
      { en: "Pure ghee", hi: "शुद्ध घी", desc: "Desi ghee made from cream in small batches.", descHi: "मलाई से छोटे बैच में बना देसी घी।" },
      { en: "Khoa & mawa", hi: "खोया और मावा", desc: "Khoa and cream for sweet shops and home sweets, on order.", descHi: "मिठाई की दुकानों और घर की मिठाई के लिए खोया और मलाई, ऑर्डर पर।" },
      { en: "Bulk supply", hi: "थोक सप्लाई", desc: "Regular milk, paneer and dahi for hotels, canteens, sweet shops and functions.", descHi: "होटल, कैंटीन, मिठाई की दुकान और फ़ंक्शन के लिए नियमित दूध, पनीर, दही।" },
      { en: "Wedding & function orders", hi: "शादी और फ़ंक्शन के ऑर्डर", desc: "Milk, dahi and paneer in the quantity you need, delivered on the day.", descHi: "जितना चाहिए दूध, दही, पनीर, उसी दिन डिलीवरी।" },
    ],
    whyUs: [
      { en: "Fresh, same-day milk", hi: "उसी दिन का ताज़ा दूध" },
      { en: "Pure, nothing added", hi: "शुद्ध, कोई मिलावट नहीं" },
      { en: "Clean cattle shed and cans", hi: "साफ़ बाड़ा और बर्तन" },
      { en: "Delivered at the same time daily", hi: "रोज़ उसी समय डिलीवरी" },
      { en: "Monthly account, no hassle", hi: "महीने का हिसाब, कोई झंझट नहीं" },
      { en: "Bulk orders handled", hi: "थोक ऑर्डर भी संभालते हैं" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Message us", hi: "मैसेज करें", desc: "Tell us your area, how much milk and morning or evening.", descHi: "इलाक़ा, कितना दूध और सुबह या शाम बताएँ।" },
      { en: "Try it for a day", hi: "एक दिन चखकर देखें", desc: "A trial delivery, then start daily.", descHi: "एक दिन ट्रायल, फिर रोज़ शुरू।" },
      { en: "Daily at your door", hi: "रोज़ दरवाज़े पर", desc: "Fresh milk at the same time every day; pause when you travel.", descHi: "रोज़ उसी समय ताज़ा दूध; बाहर जाएँ तो रोक दें।" },
      { en: "Settle monthly", hi: "महीने का हिसाब", desc: "Pay once a month by UPI or cash.", descHi: "महीने में एक बार UPI या नक़द।" },
    ],
    faq: [
      { q: "Is the milk pure?", qHi: "दूध शुद्ध है?", a: "Yes — from our own or local cattle, nothing added; you can check the fat at the dairy.", aHi: "हाँ — अपने या लोकल पशुओं का, कुछ नहीं मिलाया; डेयरी पर फ़ैट चेक करवा सकते हैं।" },
      { q: "Cow or buffalo milk?", qHi: "गाय का दूध या भैंस का?", a: "Both are usually available; tell us which you want and how much.", aHi: "आमतौर पर दोनों मिलते हैं; बताएँ कौन सा और कितना।" },
      { q: "Which areas do you deliver to?", qHi: "किन इलाक़ों में डिलीवरी है?", a: "Message us your location on WhatsApp and we will confirm the route and time.", aHi: "WhatsApp पर लोकेशन भेजें, रूट और समय कन्फ़र्म कर देंगे।" },
      { q: "Can I pause when I am away?", qHi: "बाहर जाऊँ तो रोक सकते हैं?", a: "Yes, tell us a day before and the days are adjusted in the monthly account.", aHi: "हाँ, एक दिन पहले बता दें, महीने के हिसाब में दिन एडजस्ट हो जाते हैं।" },
      { q: "Do you supply to shops and hotels?", qHi: "दुकानों और होटल को सप्लाई करते हैं?", a: "Yes, regular bulk supply of milk, paneer and dahi; message us the daily quantity.", aHi: "हाँ, दूध, पनीर, दही की नियमित थोक सप्लाई; रोज़ की मात्रा बताएँ।" },
      { q: "Is the ghee homemade?", qHi: "घी घर का बना है?", a: "Yes, made at the dairy from cream in small batches; ask what is available today.", aHi: "हाँ, डेयरी पर मलाई से छोटे बैच में बनता है; आज क्या है पूछ लें।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "A monthly account for daily customers, UPI or cash; bulk orders as agreed.", aHi: "रोज़ के ग्राहकों के लिए महीने का हिसाब, UPI या नक़द; थोक ऑर्डर तय के अनुसार।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best quality", "customer satisfaction"],
  },

  manufacturer: {
    explain: [
      "what is made (the product range, materials, sizes) and who it is for — dealers, industries, retailers, projects",
      "the factory — machines, quality checks, capacity for regular and large orders",
      "made-to-specification, job work, OEM and private label if offered",
      "how to enquire: send the requirement or drawing on WhatsApp, sample, quote, dispatch",
    ],
    services: [
      { en: "Standard product range", hi: "स्टैंडर्ड रेंज", desc: "Ready stock of regular sizes and grades, dispatched quickly.", descHi: "रेगुलर साइज़ और ग्रेड का तैयार माल, जल्दी डिस्पैच।" },
      { en: "Made to your specification", hi: "आपकी स्पेसिफ़िकेशन पर", desc: "Send a drawing or sample; we make it to size and material.", descHi: "ड्रॉइंग या सैंपल भेजें; साइज़ और मटीरियल के हिसाब से बनाते हैं।" },
      { en: "Bulk & repeat orders", hi: "थोक और रिपीट ऑर्डर", desc: "Regular monthly supply for dealers and industries, same quality each lot.", descHi: "डीलर और इंडस्ट्री के लिए नियमित मासिक सप्लाई, हर लॉट एक जैसी क्वालिटी।" },
      { en: "Job work", hi: "जॉब वर्क", desc: "Processing, machining or finishing on your material.", descHi: "आपके मटीरियल पर प्रोसेसिंग, मशीनिंग या फ़िनिशिंग।" },
      { en: "OEM & private label", hi: "OEM और प्राइवेट लेबल", desc: "Your brand name and packing on our product.", descHi: "हमारे प्रोडक्ट पर आपका ब्रांड और पैकिंग।" },
      { en: "Samples before order", hi: "ऑर्डर से पहले सैंपल", desc: "Approve a sample, then the full lot is made to match.", descHi: "सैंपल पास करें, फिर पूरा लॉट उसी के जैसा।" },
      { en: "Packing & dispatch", hi: "पैकिंग और डिस्पैच", desc: "Strong packing and transport to your site or godown.", descHi: "मज़बूत पैकिंग और आपकी साइट या गोदाम तक ट्रांसपोर्ट।" },
    ],
    whyUs: [
      { en: "Own factory, direct price", hi: "अपनी फ़ैक्टरी, सीधा दाम" },
      { en: "Checked before dispatch", hi: "डिस्पैच से पहले जाँच" },
      { en: "Same quality, every lot", hi: "हर लॉट एक जैसी क्वालिटी" },
      { en: "Custom sizes made", hi: "कस्टम साइज़ बनते हैं" },
      { en: "On-time delivery", hi: "समय पर डिलीवरी" },
      { en: "GST bill, proper documents", hi: "GST बिल, पूरे काग़ज़" },
      { en: "Dealer enquiries welcome", hi: "डीलर पूछताछ का स्वागत" },
    ],
    steps: [
      { en: "Send your requirement", hi: "ज़रूरत भेजें", desc: "Product, size, quantity and a drawing or sample if any — on WhatsApp.", descHi: "प्रोडक्ट, साइज़, मात्रा और हो तो ड्रॉइंग या सैंपल — WhatsApp पर।" },
      { en: "Quote and sample", hi: "कोटेशन और सैंपल", desc: "We send the price and lead time; a sample if you need one.", descHi: "हम दाम और समय बताते हैं; चाहें तो सैंपल।" },
      { en: "Confirm and production", hi: "कन्फ़र्म और प्रोडक्शन", desc: "Confirm with an advance; the lot is made and checked.", descHi: "एडवांस देकर कन्फ़र्म करें; लॉट बनता है और जाँचा जाता है।" },
      { en: "Dispatch", hi: "डिस्पैच", desc: "Packed and sent by transport with bill and documents.", descHi: "पैक होकर बिल और काग़ज़ के साथ ट्रांसपोर्ट से रवाना।" },
    ],
    faq: [
      { q: "What is the minimum order quantity?", qHi: "कम से कम कितना ऑर्डर?", a: "It depends on the product and size; message us what you need and we will tell you.", aHi: "प्रोडक्ट और साइज़ पर निर्भर है; क्या चाहिए भेजें, हम बता देंगे।" },
      { q: "Can you make it to my design?", qHi: "मेरे डिज़ाइन पर बना सकते हैं?", a: "Yes, send a drawing, sample or photo with the sizes and we will confirm.", aHi: "हाँ, साइज़ के साथ ड्रॉइंग, सैंपल या फ़ोटो भेजें, हम कन्फ़र्म करेंगे।" },
      { q: "Can I get a sample first?", qHi: "पहले सैंपल मिल सकता है?", a: "Yes, a sample can be made or sent before the full order; ask us.", aHi: "हाँ, पूरे ऑर्डर से पहले सैंपल बन या भेजा जा सकता है; पूछ लें।" },
      { q: "How long does an order take?", qHi: "ऑर्डर में कितना समय लगता है?", a: "Ready stock goes quickly; made-to-order depends on quantity. We tell you the lead time with the quote.", aHi: "तैयार माल जल्दी जाता है; ऑर्डर पर बनने वाला मात्रा पर निर्भर है। कोटेशन के साथ समय बताते हैं।" },
      { q: "Do you supply outside the city?", qHi: "शहर के बाहर सप्लाई करते हैं?", a: "Yes, by transport or courier across India; freight as per the order.", aHi: "हाँ, ट्रांसपोर्ट या कूरियर से पूरे भारत में; भाड़ा ऑर्डर के अनुसार।" },
      { q: "Do you give a GST bill?", qHi: "GST बिल मिलता है?", a: "Yes, every order comes with a GST invoice and the needed documents.", aHi: "हाँ, हर ऑर्डर के साथ GST इनवॉइस और ज़रूरी काग़ज़।" },
      { q: "Can I become a dealer?", qHi: "क्या मैं डीलर बन सकता हूँ?", a: "Message us your area and the products you want to sell; we will share the terms.", aHi: "अपना इलाक़ा और कौन से प्रोडक्ट बेचना चाहते हैं बताएँ; हम शर्तें बताएँगे।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best quality", "customer satisfaction", "trusted name"],
  },

  wholesale: {
    explain: [
      "what is traded (the product lines and brands) and who buys — retailers, shops, institutions, contractors",
      "stock depth — godown stock, many brands and sizes under one roof",
      "wholesale rates on quantity, regular supply and delivery to the shop",
      "how to order: send a list on WhatsApp, dispatch, GST billing",
    ],
    services: [
      { en: "Bulk supply to retailers", hi: "दुकानदारों को थोक सप्लाई", desc: "Wholesale rates on quantity for shops and resellers.", descHi: "दुकानों और रीसेलर के लिए मात्रा पर थोक दाम।" },
      { en: "Many brands, one place", hi: "कई ब्रांड, एक जगह", desc: "A full range of brands and sizes from godown stock.", descHi: "गोदाम स्टॉक से ब्रांड और साइज़ की पूरी रेंज।" },
      { en: "Delivery to your shop", hi: "आपकी दुकान तक डिलीवरी", desc: "Regular orders dropped at your shop on our route.", descHi: "हमारे रूट पर आपकी दुकान तक रेगुलर ऑर्डर।" },
      { en: "Institutional supply", hi: "संस्थागत सप्लाई", desc: "Supply to hotels, hostels, canteens, offices and contractors.", descHi: "होटल, हॉस्टल, कैंटीन, ऑफ़िस और ठेकेदारों को सप्लाई।" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर", desc: "Send your list; we pack and bill it.", descHi: "अपनी लिस्ट भेजें; हम पैक करके बिल बनाते हैं।" },
      { en: "Outstation dispatch", hi: "बाहर के शहर में डिस्पैच", desc: "Orders sent by transport with proper packing and bill.", descHi: "ट्रांसपोर्ट से ऑर्डर, सही पैकिंग और बिल के साथ।" },
      { en: "New-shop starter stock", hi: "नई दुकान का शुरुआती माल", desc: "Help choosing the first stock for a new shop.", descHi: "नई दुकान के पहले स्टॉक में मदद।" },
    ],
    whyUs: [
      { en: "Wholesale rates, direct", hi: "सीधे थोक दाम" },
      { en: "Deep stock, fewer shortages", hi: "भरा गोदाम, कमी कम" },
      { en: "All brands under one roof", hi: "सब ब्रांड एक छत के नीचे" },
      { en: "Fresh, checked stock", hi: "ताज़ा, जाँचा माल" },
      { en: "Delivery on route", hi: "रूट पर डिलीवरी" },
      { en: "GST bill on every order", hi: "हर ऑर्डर पर GST बिल" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Send your list", hi: "लिस्ट भेजें", desc: "Items, brands and quantity on WhatsApp or at the counter.", descHi: "चीज़ें, ब्रांड और मात्रा WhatsApp पर या काउंटर पर।" },
      { en: "Rate and availability", hi: "दाम और उपलब्धता", desc: "We confirm the rate, what is in stock and the delivery day.", descHi: "हम दाम, स्टॉक और डिलीवरी का दिन कन्फ़र्म करते हैं।" },
      { en: "Packed and billed", hi: "पैक और बिल", desc: "Order packed from the godown with a GST bill.", descHi: "गोदाम से ऑर्डर पैक, GST बिल के साथ।" },
      { en: "Pick up or delivered", hi: "ले जाएँ या डिलीवरी", desc: "Collect from the godown or get it on our delivery route.", descHi: "गोदाम से ले जाएँ या हमारे रूट पर मँगवाएँ।" },
    ],
    faq: [
      { q: "Do you sell to individuals or only shops?", qHi: "सिर्फ़ दुकानदारों को या आम ग्राहक को भी?", a: "Mainly to retailers and institutions; for a large household or function order, message us.", aHi: "मुख्य रूप से दुकानदारों और संस्थाओं को; घर या फ़ंक्शन के बड़े ऑर्डर के लिए मैसेज करें।" },
      { q: "What is the minimum order?", qHi: "कम से कम कितना ऑर्डर?", a: "Wholesale rates apply on case or carton quantity; tell us what you need and we will confirm.", aHi: "थोक दाम पेटी या कार्टन की मात्रा पर; क्या चाहिए बताएँ, हम कन्फ़र्म करेंगे।" },
      { q: "Do you deliver to my shop?", qHi: "मेरी दुकान तक डिलीवरी होगी?", a: "Yes, on our delivery route in the city; outstation by transport. Send your location.", aHi: "हाँ, शहर में हमारे रूट पर; बाहर ट्रांसपोर्ट से। लोकेशन भेजें।" },
      { q: "Which brands do you keep?", qHi: "कौन-कौन से ब्रांड रखते हैं?", a: "Most popular brands of the line; message us for a current list or a particular brand.", aHi: "लाइन के ज़्यादातर चलते ब्रांड; लिस्ट या किसी खास ब्रांड के लिए मैसेज करें।" },
      { q: "Do you give credit?", qHi: "उधार मिलता है?", a: "Terms for regular shops are discussed in person; new customers start on payment.", aHi: "नियमित दुकानों की शर्तें आमने-सामने तय होती हैं; नए ग्राहक भुगतान पर शुरू करते हैं।" },
      { q: "Can I return damaged or expired stock?", qHi: "ख़राब या एक्सपायर माल वापस होगा?", a: "Check the goods on delivery; damaged or short items are replaced when reported at once.", aHi: "डिलीवरी पर माल जाँच लें; नुकसान या कमी तुरंत बताने पर बदल देते हैं।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, bank transfer or cash against the bill; ask about terms for regular orders.", aHi: "बिल पर UPI, बैंक ट्रांसफ़र या नक़द; नियमित ऑर्डर की शर्तें पूछ लें।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best rates", "customer satisfaction"],
  },

  textile: {
    explain: [
      "what is sold (sarees, suits, dress material, lehenga, dupattas; silk, cotton, synthetic) and the fabrics / weaves",
      "wholesale to shops and retail for families; wedding and festive collections",
      "catalogue and new arrivals on WhatsApp; courier across India",
      "fall-pico, blouse and stitching help if offered",
    ],
    services: [
      { en: "Sarees", hi: "साड़ियाँ", desc: "Silk, cotton, printed and designer sarees for daily and occasion wear.", descHi: "रोज़ और मौक़े के लिए सिल्क, कॉटन, प्रिंटेड और डिज़ाइनर साड़ियाँ।" },
      { en: "Suits & dress material", hi: "सूट और ड्रेस मटीरियल", desc: "Unstitched suits, dupattas and fabric by the metre.", descHi: "बिना सिले सूट, दुपट्टे और मीटर से कपड़ा।" },
      { en: "Wedding & festive collection", hi: "शादी और त्योहार कलेक्शन", desc: "Lehenga, bridal sarees and matching for the whole family.", descHi: "लहंगा, ब्राइडल साड़ी और पूरे परिवार की मैचिंग।" },
      { en: "Wholesale to shops", hi: "दुकानों को थोक", desc: "Catalogue and bulk rates for retailers and boutiques.", descHi: "दुकानदारों और बुटीक के लिए कैटलॉग और थोक दाम।" },
      { en: "Catalogue on WhatsApp", hi: "WhatsApp पर कैटलॉग", desc: "New arrivals and designs sent to your phone; order from home.", descHi: "नए डिज़ाइन आपके फ़ोन पर; घर बैठे ऑर्डर।" },
      { en: "Fall-pico & blouse", hi: "फ़ॉल-पीको और ब्लाउज़", desc: "Fall, pico and blouse stitching arranged with your purchase.", descHi: "ख़रीद के साथ फ़ॉल, पीको और ब्लाउज़ की सिलाई।" },
      { en: "Courier across India", hi: "पूरे भारत में कूरियर", desc: "Orders packed and sent by courier to your home or shop.", descHi: "ऑर्डर पैक करके कूरियर से आपके घर या दुकान तक।" },
    ],
    whyUs: [
      { en: "Fresh designs every season", hi: "हर सीज़न नए डिज़ाइन" },
      { en: "Quality fabric, checked by hand", hi: "अच्छा कपड़ा, हाथ से जाँचा" },
      { en: "Wholesale and retail both", hi: "थोक और फुटकर दोनों" },
      { en: "Wide range, every budget", hi: "पूरी रेंज, हर बजट" },
      { en: "Catalogue on WhatsApp", hi: "WhatsApp पर कैटलॉग" },
      { en: "Family wedding shopping, one place", hi: "शादी की पूरी ख़रीदारी एक जगह" },
      { en: "Courier anywhere in India", hi: "पूरे भारत में कूरियर" },
    ],
    steps: [
      { en: "See the collection", hi: "कलेक्शन देखें", desc: "Visit the shop or ask for the catalogue on WhatsApp.", descHi: "दुकान आइए या WhatsApp पर कैटलॉग मँगवाएँ।" },
      { en: "Pick and confirm", hi: "पसंद करें और कन्फ़र्म करें", desc: "Choose the pieces, colours and quantity; we confirm the rate.", descHi: "पीस, रंग और मात्रा चुनें; हम दाम कन्फ़र्म करते हैं।" },
      { en: "Finishing if needed", hi: "ज़रूरत हो तो फ़िनिशिंग", desc: "Fall-pico or blouse stitching arranged before packing.", descHi: "पैकिंग से पहले फ़ॉल-पीको या ब्लाउज़ सिलाई।" },
      { en: "Pick up or courier", hi: "ले जाएँ या कूरियर", desc: "Collect from the shop or get it couriered home.", descHi: "दुकान से ले जाएँ या घर तक कूरियर।" },
    ],
    faq: [
      { q: "Do you sell wholesale?", qHi: "थोक में देते हैं?", a: "Yes, to shops and boutiques; message us for the catalogue and bulk rates.", aHi: "हाँ, दुकानों और बुटीक को; कैटलॉग और थोक दाम के लिए मैसेज करें।" },
      { q: "Can I buy a single saree?", qHi: "एक साड़ी भी ले सकते हैं?", a: "Yes, retail customers are welcome at the shop and on WhatsApp.", aHi: "हाँ, फुटकर ग्राहकों का दुकान और WhatsApp पर स्वागत है।" },
      { q: "Is the fabric pure silk or cotton?", qHi: "कपड़ा शुद्ध सिल्क / कॉटन है?", a: "We tell you the fabric and blend of each piece honestly; ask before you buy.", aHi: "हर पीस का कपड़ा और मिक्स साफ़ बताते हैं; ख़रीदने से पहले पूछ लें।" },
      { q: "Do you send the catalogue on WhatsApp?", qHi: "WhatsApp पर कैटलॉग भेजते हैं?", a: "Yes, message us what you are looking for and we send photos and rates.", aHi: "हाँ, क्या चाहिए बताएँ, हम फ़ोटो और दाम भेजते हैं।" },
      { q: "Do you courier outside the city?", qHi: "शहर के बाहर कूरियर करते हैं?", a: "Yes, across India; payment before dispatch, courier charge as applicable.", aHi: "हाँ, पूरे भारत में; डिस्पैच से पहले भुगतान, कूरियर चार्ज लागू।" },
      { q: "Can I exchange if the colour is different?", qHi: "रंग अलग निकले तो बदलेगा?", a: "Unused pieces with tags can be exchanged within a few days; message us a photo first.", aHi: "टैग समेत बिना इस्तेमाल पीस कुछ दिन में बदल सकते हैं; पहले फ़ोटो भेजें।" },
      { q: "Do you do blouse stitching?", qHi: "ब्लाउज़ सिलाई करते हैं?", a: "Fall-pico and blouse stitching can be arranged with your purchase; ask at the counter.", aHi: "ख़रीद के साथ फ़ॉल-पीको और ब्लाउज़ सिलाई करवा सकते हैं; काउंटर पर पूछें।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best quality", "latest collection", "customer satisfaction"],
  },
};

export const INDUSTRY_DEFAULT: TradeData = {
  explain: [
    "what the business makes, grows or supplies, and who buys from it (shops, industries, farmers, families)",
    "stock, capacity and the quality check before goods go out",
    "bulk, regular and custom orders; delivery and dispatch",
    "how to enquire: send the requirement on WhatsApp, get a rate, confirm",
  ],
  services: [
    { en: "Bulk supply", hi: "थोक सप्लाई", desc: "Regular quantity for shops, industries and institutions at wholesale rates.", descHi: "दुकानों, इंडस्ट्री और संस्थाओं के लिए थोक दाम पर नियमित मात्रा।" },
    { en: "Regular monthly orders", hi: "नियमित मासिक ऑर्डर", desc: "Fixed supply every month so you never run short.", descHi: "हर महीने तय सप्लाई, ताकि कमी न पड़े।" },
    { en: "Custom orders", hi: "कस्टम ऑर्डर", desc: "Size, grade or packing as you need, on request.", descHi: "साइज़, ग्रेड या पैकिंग आपकी ज़रूरत के हिसाब से।" },
    { en: "Samples before order", hi: "ऑर्डर से पहले सैंपल", desc: "See or test a sample before the full lot.", descHi: "पूरे लॉट से पहले सैंपल देखें या जाँचें।" },
    { en: "Delivery & dispatch", hi: "डिलीवरी और डिस्पैच", desc: "Local delivery and outstation dispatch by transport.", descHi: "लोकल डिलीवरी और ट्रांसपोर्ट से बाहर के शहर में।" },
    { en: "GST billing", hi: "GST बिलिंग", desc: "Proper invoice and documents with every order.", descHi: "हर ऑर्डर के साथ सही इनवॉइस और काग़ज़।" },
    { en: "Dealer & reseller enquiries", hi: "डीलर और रीसेलर पूछताछ", desc: "Terms for shops and dealers who want to sell our products.", descHi: "हमारा माल बेचने वाली दुकानों और डीलरों के लिए शर्तें।" },
  ],
  whyUs: [
    { en: "Direct from source", hi: "सीधे स्रोत से" },
    { en: "Checked before it leaves", hi: "निकलने से पहले जाँच" },
    { en: "Same quality, every order", hi: "हर ऑर्डर एक जैसी क्वालिटी" },
    { en: "Stock ready, less waiting", hi: "माल तैयार, कम इंतज़ार" },
    { en: "On-time dispatch", hi: "समय पर डिस्पैच" },
    { en: "GST bill, clear dealing", hi: "GST बिल, साफ़ लेन-देन" },
    { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
  ],
  steps: [
    { en: "Send your requirement", hi: "ज़रूरत भेजें", desc: "Product, quantity and where it has to reach — on WhatsApp.", descHi: "प्रोडक्ट, मात्रा और कहाँ पहुँचाना है — WhatsApp पर।" },
    { en: "Rate and sample", hi: "दाम और सैंपल", desc: "We confirm the rate and availability; a sample if you want.", descHi: "हम दाम और उपलब्धता बताते हैं; चाहें तो सैंपल।" },
    { en: "Confirm the order", hi: "ऑर्डर कन्फ़र्म करें", desc: "Confirm with an advance; the goods are prepared and checked.", descHi: "एडवांस देकर कन्फ़र्म करें; माल तैयार और जाँचा जाता है।" },
    { en: "Delivered with bill", hi: "बिल के साथ डिलीवरी", desc: "Packed and sent with the invoice; collect or get it delivered.", descHi: "इनवॉइस के साथ पैक होकर; ले जाएँ या मँगवाएँ।" },
  ],
  faq: [
    { q: "What is the minimum order?", qHi: "कम से कम कितना ऑर्डर?", a: "It depends on the product; message us what you need and we will tell you.", aHi: "प्रोडक्ट पर निर्भर है; क्या चाहिए भेजें, हम बता देंगे।" },
    { q: "Can I see a sample first?", qHi: "पहले सैंपल देख सकते हैं?", a: "Yes, a sample can be shown or sent before you confirm the full order.", aHi: "हाँ, पूरा ऑर्डर कन्फ़र्म करने से पहले सैंपल दिखा या भेज सकते हैं।" },
    { q: "Do you deliver outside the city?", qHi: "शहर के बाहर डिलीवरी होती है?", a: "Yes, by transport or courier; freight is added as per the order.", aHi: "हाँ, ट्रांसपोर्ट या कूरियर से; भाड़ा ऑर्डर के अनुसार जुड़ता है।" },
    { q: "How long does supply take?", qHi: "सप्लाई में कितना समय लगता है?", a: "Ready stock goes quickly; larger or custom orders take longer. We tell you with the rate.", aHi: "तैयार माल जल्दी जाता है; बड़े या कस्टम ऑर्डर में ज़्यादा समय। दाम के साथ बता देते हैं।" },
    { q: "Do you give a GST bill?", qHi: "GST बिल मिलता है?", a: "Yes, every order is billed with a proper GST invoice.", aHi: "हाँ, हर ऑर्डर का GST इनवॉइस बनता है।" },
    { q: "Do you sell to individuals too?", qHi: "आम ग्राहक को भी बेचते हैं?", a: "Mainly to businesses; for a one-time large need, message us and we will see.", aHi: "मुख्य रूप से व्यापारियों को; एक बार की बड़ी ज़रूरत हो तो मैसेज करें, देख लेंगे।" },
    { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, bank transfer or cash against the bill; an advance on larger orders.", aHi: "बिल पर UPI, बैंक ट्रांसफ़र या नक़द; बड़े ऑर्डर पर एडवांस।" },
  ],
  generic: ["connect with us", "explore options", "quality products", "best quality", "customer satisfaction", "trusted name"],
};
