// Personal group: personal / family, employee, government officer, army / police / retired, influencer / creator, other.
// See types.ts for the rules (no numbers, no claims; true of any decent person or role of the kind).
import type { TradeData } from "./types";

export const PERSONAL: Record<string, TradeData> = {
  personal: {
    explain: [
      "who you are — name, family and where you are from / live now",
      "what you do and what you care about (work, interests, community)",
      "family occasions — invitations, greetings and photos you want to share",
      "how to reach you: WhatsApp, call, address",
    ],
    services: [
      { en: "Save my contact", hi: "मेरा नंबर सेव करें", desc: "Phone, WhatsApp and address in one tap, always up to date.", descHi: "फ़ोन, WhatsApp और पता एक टैप में, हमेशा अपडेट।" },
      { en: "Family invitations", hi: "परिवार के निमंत्रण", desc: "Wedding, birthday and pooja invitations shared with the full family.", descHi: "शादी, जन्मदिन और पूजा के न्योते पूरे परिवार तक।" },
      { en: "Festival greetings", hi: "त्योहार की शुभकामनाएँ", desc: "Diwali, Holi, Eid and new year wishes to everyone I know.", descHi: "दिवाली, होली, ईद और नए साल की शुभकामनाएँ सबको।" },
      { en: "Photos & family updates", hi: "फ़ोटो और परिवार की ख़बरें", desc: "Moments from home, trips and functions, shared with family and friends.", descHi: "घर, सफ़र और फ़ंक्शन की यादें, परिवार और दोस्तों के साथ।" },
      { en: "Stay in touch", hi: "संपर्क में रहें", desc: "A hello on WhatsApp any time — old friends and relatives welcome.", descHi: "WhatsApp पर कभी भी हेलो कहें — पुराने दोस्त, रिश्तेदार, सब।" },
      { en: "Address & directions", hi: "पता और रास्ता", desc: "Find my home easily with the map link on this card.", descHi: "इस कार्ड के मैप लिंक से घर आसानी से ढूँढें।" },
      { en: "Help & references", hi: "मदद और संपर्क", desc: "Need a contact, a reference or a local tip? Just ask.", descHi: "कोई संपर्क, रेफ़रेंस या लोकल जानकारी चाहिए? बस पूछ लें।" },
    ],
    whyUs: [
      { en: "All my details, one card", hi: "सारी जानकारी, एक कार्ड" },
      { en: "Always reachable on WhatsApp", hi: "WhatsApp पर हमेशा उपलब्ध" },
      { en: "Easy to save and share", hi: "सेव और शेयर करना आसान" },
      { en: "Number never gets lost", hi: "नंबर कभी गुम नहीं" },
      { en: "Family and friends together", hi: "परिवार और दोस्त एक साथ" },
      { en: "Simple, personal, no fuss", hi: "सीधा, अपना, बिना झंझट" },
    ],
    steps: [
      { en: "Open the card", hi: "कार्ड खोलें", desc: "See my details, photos and the map on this page.", descHi: "इसी पेज पर मेरी जानकारी, फ़ोटो और मैप देखें।" },
      { en: "Save the number", hi: "नंबर सेव करें", desc: "One tap adds my contact to your phone.", descHi: "एक टैप में मेरा नंबर आपके फ़ोन में।" },
      { en: "Say hello", hi: "हेलो कहें", desc: "Message me on WhatsApp — a reply comes when I am free.", descHi: "WhatsApp पर मैसेज करें — फ़्री होते ही जवाब मिलेगा।" },
    ],
    faq: [
      { q: "How do I save your contact?", qHi: "आपका नंबर कैसे सेव करूँ?", a: "Tap the save button on this card and the number, WhatsApp and address go straight into your phone.", aHi: "कार्ड पर सेव बटन दबाएँ — नंबर, WhatsApp और पता सीधे आपके फ़ोन में आ जाएगा।" },
      { q: "Can I share this card with others?", qHi: "यह कार्ड दूसरों को भेज सकते हैं?", a: "Yes, send the link to family and friends on WhatsApp; it always shows my latest details.", aHi: "हाँ, लिंक परिवार और दोस्तों को WhatsApp पर भेजें; इसमें हमेशा मेरी ताज़ा जानकारी रहती है।" },
      { q: "Is this your current number?", qHi: "क्या यह आपका चालू नंबर है?", a: "Yes, this card is kept updated; if a number changes, the card changes with it.", aHi: "हाँ, यह कार्ड अपडेट रहता है; नंबर बदले तो कार्ड भी बदल जाता है।" },
      { q: "Where do you live now?", qHi: "आप अभी कहाँ रहते हैं?", a: "The address and map link are on this card; message me before you come.", aHi: "पता और मैप लिंक कार्ड पर है; आने से पहले मैसेज कर दें।" },
      { q: "How do I send an invitation or wishes?", qHi: "निमंत्रण या शुभकामनाएँ कैसे भेजें?", a: "Message me on WhatsApp — invitations, cards and wishes are all welcome there.", aHi: "WhatsApp पर भेज दें — न्योता, कार्ड और शुभकामनाएँ, सब वहीं।" },
      { q: "Can I see family photos?", qHi: "परिवार की फ़ोटो देख सकते हैं?", a: "Some photos are on this card; for more, ask me on WhatsApp.", aHi: "कुछ फ़ोटो इसी कार्ड पर हैं; और चाहिए तो WhatsApp पर पूछ लें।" },
      { q: "When is a good time to call?", qHi: "कॉल करने का सही समय?", a: "Message first on WhatsApp and I will call back when free.", aHi: "पहले WhatsApp पर मैसेज करें, फ़्री होते ही कॉल बैक मिलेगा।" },
    ],
    generic: ["connect with us", "explore options", "get in touch", "know more", "contact me"],
  },

  employee: {
    explain: [
      "your role, company and what the work involves",
      "experience, skills and the kind of problems you handle",
      "how colleagues, clients and recruiters can reach you — office and WhatsApp",
      "professional links — LinkedIn, portfolio, resume",
    ],
    services: [
      { en: "My role & work", hi: "मेरा पद और काम", desc: "What I handle at the company — department, responsibilities and projects.", descHi: "कंपनी में मेरा काम — विभाग, ज़िम्मेदारियाँ और प्रोजेक्ट।" },
      { en: "Office contact", hi: "ऑफ़िस संपर्क", desc: "Official email, desk number and office address for work matters.", descHi: "काम के लिए ऑफ़िशियल ईमेल, डेस्क नंबर और ऑफ़िस का पता।" },
      { en: "Work enquiries", hi: "काम से जुड़े सवाल", desc: "Clients, vendors and colleagues can message me directly.", descHi: "क्लाइंट, वेंडर और सहकर्मी सीधे मैसेज कर सकते हैं।" },
      { en: "Meetings & appointments", hi: "मीटिंग और अपॉइंटमेंट", desc: "Fix a time on WhatsApp for a call or an office visit.", descHi: "कॉल या ऑफ़िस में मिलने का समय WhatsApp पर तय करें।" },
      { en: "Profile & experience", hi: "प्रोफ़ाइल और अनुभव", desc: "Qualifications, past companies and skills, in one place.", descHi: "पढ़ाई, पिछली कंपनियाँ और स्किल्स, एक जगह।" },
      { en: "LinkedIn & resume", hi: "LinkedIn और रिज़्यूमे", desc: "Connect on LinkedIn or ask for the latest resume.", descHi: "LinkedIn पर जुड़ें या ताज़ा रिज़्यूमे माँग लें।" },
      { en: "References & networking", hi: "रेफ़रेंस और नेटवर्किंग", desc: "Happy to refer good people and connect within the industry.", descHi: "अच्छे लोगों को रेफ़र करना और इंडस्ट्री में जोड़ना — ख़ुशी से।" },
    ],
    whyUs: [
      { en: "Clear role, clear contact", hi: "साफ़ पद, साफ़ संपर्क" },
      { en: "Reply within office hours", hi: "ऑफ़िस समय में जवाब" },
      { en: "Experience you can check", hi: "अनुभव, जो आप देख सकते हैं" },
      { en: "Professional on every channel", hi: "हर जगह प्रोफ़ेशनल" },
      { en: "A card, not a paper", hi: "काग़ज़ नहीं, कार्ड" },
      { en: "One link for all profiles", hi: "सभी प्रोफ़ाइल का एक लिंक" },
      { en: "Easy to share with teams", hi: "टीम से शेयर करना आसान" },
    ],
    steps: [
      { en: "See my profile", hi: "प्रोफ़ाइल देखें", desc: "Role, company and experience are on this page.", descHi: "पद, कंपनी और अनुभव इसी पेज पर।" },
      { en: "Save the contact", hi: "नंबर सेव करें", desc: "Office and WhatsApp numbers in one tap.", descHi: "ऑफ़िस और WhatsApp नंबर एक टैप में।" },
      { en: "Message for work", hi: "काम के लिए मैसेज करें", desc: "Tell me what it is about and a good time to talk.", descHi: "बताएँ किस बारे में है और बात करने का सही समय।" },
      { en: "Call or meet", hi: "कॉल या मुलाक़ात", desc: "We fix a call or an office meeting that suits both.", descHi: "दोनों की सुविधा से कॉल या ऑफ़िस में मीटिंग तय।" },
    ],
    faq: [
      { q: "What is your role and company?", qHi: "आपका पद और कंपनी क्या है?", a: "Both are on this card, with what my work involves; message me for anything specific.", aHi: "दोनों कार्ड पर हैं, साथ में मेरे काम की जानकारी; कुछ ख़ास पूछना हो तो मैसेज करें।" },
      { q: "How do I reach you for office matters?", qHi: "ऑफ़िस के काम के लिए कैसे संपर्क करूँ?", a: "Use the official email or desk number on the card; WhatsApp works for quick questions.", aHi: "कार्ड पर दिया ऑफ़िशियल ईमेल या डेस्क नंबर; छोटे सवाल WhatsApp पर भी।" },
      { q: "What are your office timings?", qHi: "ऑफ़िस का समय क्या है?", a: "Regular office hours on working days; message on WhatsApp and a reply comes when free.", aHi: "काम के दिनों में ऑफ़िस समय; WhatsApp पर मैसेज करें, फ़्री होते ही जवाब मिलेगा।" },
      { q: "Can you share your resume?", qHi: "रिज़्यूमे भेज सकते हैं?", a: "Yes, message me on WhatsApp and the latest copy will be sent.", aHi: "हाँ, WhatsApp पर मैसेज करें, ताज़ा कॉपी भेज दी जाएगी।" },
      { q: "Can we connect on LinkedIn?", qHi: "LinkedIn पर जुड़ सकते हैं?", a: "Of course — the LinkedIn link is on this card; send a request with a short note.", aHi: "ज़रूर — LinkedIn लिंक कार्ड पर है; एक छोटे नोट के साथ रिक्वेस्ट भेजें।" },
      { q: "Do you take up freelance or side projects?", qHi: "फ़्रीलांस या साइड प्रोजेक्ट लेते हैं?", a: "It depends on the work and company policy; message me on WhatsApp with the details.", aHi: "काम और कंपनी की पॉलिसी पर निर्भर है; WhatsApp पर डिटेल भेजें।" },
      { q: "Can you refer me for a job at your company?", qHi: "अपनी कंपनी में रेफ़र कर सकते हैं?", a: "Send your resume and the role on WhatsApp; if there is a fit, a referral follows.", aHi: "रिज़्यूमे और रोल WhatsApp पर भेजें; सही लगा तो रेफ़र ज़रूर करेंगे।" },
    ],
    generic: ["connect with us", "explore options", "get in touch", "know more", "contact me", "professional services"],
  },

  govt: {
    explain: [
      "post, department and office — what the office handles",
      "public dealing: meeting hours, where to submit applications and complaints",
      "schemes and services the department offers and the documents people need",
      "how to reach the office: address, phone, WhatsApp",
    ],
    services: [
      { en: "Public dealing", hi: "जनसुनवाई", desc: "Meet citizens at the office during public hours for their matters.", descHi: "जनता के काम के लिए ऑफ़िस में तय समय पर मुलाक़ात।" },
      { en: "Applications & forms", hi: "आवेदन और फ़ॉर्म", desc: "Guidance on which form to fill and where to submit it.", descHi: "कौन सा फ़ॉर्म भरें और कहाँ जमा करें — मार्गदर्शन।" },
      { en: "Complaints & grievances", hi: "शिकायत और समस्या", desc: "Register a complaint related to the department and follow it up.", descHi: "विभाग से जुड़ी शिकायत दर्ज करें और उसका फ़ॉलो-अप।" },
      { en: "Scheme information", hi: "योजनाओं की जानकारी", desc: "Who is eligible for government schemes and how to apply.", descHi: "सरकारी योजनाओं में कौन पात्र है और आवेदन कैसे करें।" },
      { en: "Document checklist", hi: "दस्तावेज़ों की सूची", desc: "Know the papers needed before you visit, to save a trip.", descHi: "आने से पहले ज़रूरी काग़ज़ जान लें, चक्कर बचेगा।" },
      { en: "Appointment for meeting", hi: "मिलने का समय", desc: "Message to fix a time for matters that need a sit-down.", descHi: "जिन कामों में बैठकर बात ज़रूरी हो, मैसेज करके समय लें।" },
      { en: "Field visits & inspections", hi: "फ़ील्ड विज़िट और निरीक्षण", desc: "Site visits as the department's work requires.", descHi: "विभाग के काम के अनुसार मौक़े पर जाकर निरीक्षण।" },
    ],
    whyUs: [
      { en: "Clear process, no confusion", hi: "साफ़ प्रक्रिया, कोई भ्रम नहीं" },
      { en: "Office hours on the card", hi: "ऑफ़िस समय कार्ड पर" },
      { en: "Know the documents beforehand", hi: "काग़ज़ पहले से पता" },
      { en: "Right desk, first time", hi: "पहली बार में सही टेबल" },
      { en: "Schemes explained in plain words", hi: "योजनाएँ आसान भाषा में" },
      { en: "Reach the office on WhatsApp", hi: "ऑफ़िस से WhatsApp पर संपर्क" },
      { en: "Service to the public", hi: "जनता की सेवा" },
    ],
    steps: [
      { en: "Check the office details", hi: "ऑफ़िस की जानकारी देखें", desc: "Department, address and public hours are on this card.", descHi: "विभाग, पता और जनसुनवाई का समय कार्ड पर है।" },
      { en: "Message your matter", hi: "अपना काम बताएँ", desc: "Write in short what the work is; we tell you the documents.", descHi: "काम क्या है संक्षेप में लिखें; ज़रूरी काग़ज़ बता दिए जाएँगे।" },
      { en: "Visit with documents", hi: "काग़ज़ लेकर आएँ", desc: "Come in office hours with the papers and the application.", descHi: "ऑफ़िस समय में काग़ज़ और आवेदन लेकर आएँ।" },
      { en: "Follow the process", hi: "प्रक्रिया पूरी करें", desc: "The matter moves as per the rules; check status with the reference.", descHi: "काम नियमों के अनुसार आगे बढ़ता है; रेफ़रेंस से स्थिति पूछें।" },
    ],
    faq: [
      { q: "Which department and post are you in?", qHi: "आप किस विभाग में, किस पद पर हैं?", a: "Both are on this card along with the office address; message for anything else.", aHi: "दोनों कार्ड पर हैं, साथ में ऑफ़िस का पता; और कुछ पूछना हो तो मैसेज करें।" },
      { q: "When can I meet you at the office?", qHi: "ऑफ़िस में कब मिल सकते हैं?", a: "During the public hours shown on the card; message beforehand for longer matters.", aHi: "कार्ड पर दिए जनसुनवाई समय में; लंबी बात हो तो पहले मैसेज कर दें।" },
      { q: "Where do I submit my application?", qHi: "आवेदन कहाँ जमा करें?", a: "At the office counter or the online portal for that service; message us and we point you to the right one.", aHi: "ऑफ़िस काउंटर पर या उस सेवा के ऑनलाइन पोर्टल पर; मैसेज करें, सही जगह बता देंगे।" },
      { q: "Which documents should I bring?", qHi: "कौन से दस्तावेज़ लाऊँ?", a: "It depends on the work — usually ID, address proof and the related papers; message to confirm.", aHi: "काम पर निर्भर है — आमतौर पर पहचान पत्र, पते का प्रमाण और संबंधित काग़ज़; मैसेज करके पक्का कर लें।" },
      { q: "How do I file a complaint?", qHi: "शिकायत कैसे दर्ज करें?", a: "Write it with your details and submit at the office or the department's helpline; keep the receipt number.", aHi: "अपनी जानकारी के साथ लिखकर ऑफ़िस या विभाग की हेल्पलाइन पर दें; रसीद नंबर संभालकर रखें।" },
      { q: "How do I find out about a scheme?", qHi: "किसी योजना की जानकारी कैसे मिलेगी?", a: "Message the scheme name on WhatsApp; eligibility and the application steps will be explained.", aHi: "योजना का नाम WhatsApp पर भेजें; पात्रता और आवेदन के चरण बता दिए जाएँगे।" },
      { q: "Can I check the status of my work?", qHi: "अपने काम की स्थिति पता कर सकते हैं?", a: "Yes, share the application or reference number on WhatsApp or at the office.", aHi: "हाँ, आवेदन या रेफ़रेंस नंबर WhatsApp पर या ऑफ़िस में बताएँ।" },
    ],
    generic: ["connect with us", "explore options", "contact us", "know more", "public service", "get in touch"],
  },

  army: {
    explain: [
      "service — serving or retired, force, rank and unit / posting",
      "what you do now — ex-servicemen help, security work, community or social work",
      "guidance for young people who want to join the forces",
      "how to reach you and when",
    ],
    services: [
      { en: "Ex-servicemen guidance", hi: "पूर्व सैनिकों के लिए मार्गदर्शन", desc: "Help with pension, canteen, ECHS and welfare paperwork.", descHi: "पेंशन, कैंटीन, ECHS और कल्याण के काग़ज़ों में मदद।" },
      { en: "Joining the forces", hi: "फ़ौज / पुलिस में भर्ती", desc: "Guidance for youth on recruitment, fitness and preparation.", descHi: "भर्ती, फ़िटनेस और तैयारी पर युवाओं को मार्गदर्शन।" },
      { en: "Veteran network", hi: "पूर्व सैनिक नेटवर्क", desc: "Keep in touch with unit mates, reunions and welfare groups.", descHi: "यूनिट के साथियों, रीयूनियन और कल्याण समूहों से जुड़े रहें।" },
      { en: "Security advice", hi: "सुरक्षा सलाह", desc: "Practical advice on home, society and event security.", descHi: "घर, सोसाइटी और आयोजन की सुरक्षा पर व्यावहारिक सलाह।" },
      { en: "Community & social work", hi: "समाज सेवा", desc: "Blood camps, cleanliness drives and help in local emergencies.", descHi: "रक्तदान शिविर, स्वच्छता अभियान और स्थानीय आपदा में मदद।" },
      { en: "Motivation & talks", hi: "प्रेरणा और वार्ता", desc: "Talks at schools, colleges and events on discipline and service.", descHi: "स्कूल, कॉलेज और आयोजनों में अनुशासन और सेवा पर बातचीत।" },
      { en: "Soldiers' families", hi: "सैनिक परिवारों की मदद", desc: "Guidance for families of serving and departed personnel on entitlements.", descHi: "सेवारत और दिवंगत सैनिकों के परिवारों को हक़ों की जानकारी।" },
    ],
    whyUs: [
      { en: "Discipline and honesty", hi: "अनुशासन और ईमानदारी" },
      { en: "Service before self", hi: "सेवा परमो धर्म" },
      { en: "Know the system from inside", hi: "सिस्टम अंदर से जानते हैं" },
      { en: "Straight talk, no runaround", hi: "सीधी बात, कोई चक्कर नहीं" },
      { en: "Always there for veterans", hi: "पूर्व सैनिकों के साथ हमेशा" },
      { en: "Reach on WhatsApp", hi: "WhatsApp पर संपर्क" },
    ],
    steps: [
      { en: "See my service", hi: "मेरी सेवा देखें", desc: "Force, rank and posting are on this card.", descHi: "फ़ोर्स, रैंक और पोस्टिंग कार्ड पर है।" },
      { en: "Message your need", hi: "अपनी ज़रूरत बताएँ", desc: "Pension help, recruitment guidance or anything else — write in short.", descHi: "पेंशन, भर्ती मार्गदर्शन या कुछ और — संक्षेप में लिखें।" },
      { en: "Talk or meet", hi: "बात या मुलाक़ात", desc: "A call or a meeting at a time that suits.", descHi: "सुविधा के समय कॉल या मुलाक़ात।" },
      { en: "Get it done right", hi: "सही रास्ते से काम", desc: "The right form, the right office, the right way.", descHi: "सही फ़ॉर्म, सही दफ़्तर, सही तरीक़ा।" },
    ],
    faq: [
      { q: "Are you serving or retired?", qHi: "आप सेवारत हैं या रिटायर्ड?", a: "The card shows my status, force and rank; message for anything more.", aHi: "कार्ड पर स्थिति, फ़ोर्स और रैंक दी है; और कुछ पूछना हो तो मैसेज करें।" },
      { q: "Can you guide my son or daughter to join the army or police?", qHi: "बेटे-बेटी को फ़ौज / पुलिस में भर्ती का मार्गदर्शन मिल सकता है?", a: "Yes — message on WhatsApp; guidance on eligibility, fitness and preparation is given gladly.", aHi: "हाँ — WhatsApp पर मैसेज करें; पात्रता, फ़िटनेस और तैयारी पर ख़ुशी से बताया जाएगा।" },
      { q: "Can you help with pension or canteen matters?", qHi: "पेंशन या कैंटीन के काम में मदद मिलेगी?", a: "Yes, for ex-servicemen and their families; bring your service papers and we find the right office.", aHi: "हाँ, पूर्व सैनिकों और उनके परिवार के लिए; सेवा के काग़ज़ लाएँ, सही दफ़्तर बताया जाएगा।" },
      { q: "Do you take security assignments?", qHi: "सिक्योरिटी का काम लेते हैं?", a: "Message the details on WhatsApp; advice is always given, assignments depend on availability.", aHi: "WhatsApp पर डिटेल भेजें; सलाह हमेशा, असाइनमेंट उपलब्धता पर निर्भर।" },
      { q: "Can you speak at our school or event?", qHi: "हमारे स्कूल या आयोजन में बोलने आ सकते हैं?", a: "Happy to, when free — send the date, place and audience on WhatsApp.", aHi: "फ़्री होने पर ख़ुशी से — तारीख़, जगह और श्रोता WhatsApp पर भेजें।" },
      { q: "How do I reach you?", qHi: "आपसे संपर्क कैसे करें?", a: "WhatsApp first; a call back comes when free. For official matters use the unit or office channel.", aHi: "पहले WhatsApp; फ़्री होते ही कॉल बैक। सरकारी काम के लिए यूनिट या ऑफ़िस के ज़रिए।" },
    ],
    generic: ["connect with us", "explore options", "get in touch", "know more", "contact me", "proud to serve"],
  },

  influencer: {
    explain: [
      "the niche and platforms — food, fashion, travel, tech, local city; Instagram, YouTube, Facebook",
      "the audience — who follows, which city or language",
      "what brands can book: reels, posts, reviews, event coverage, giveaways",
      "how to collaborate: message with the brief, timeline and budget",
    ],
    services: [
      { en: "Brand collaborations", hi: "ब्रांड कोलैबोरेशन", desc: "Sponsored reels, posts and stories for your product or shop.", descHi: "आपके प्रोडक्ट या दुकान के लिए स्पॉन्सर्ड रील, पोस्ट और स्टोरी।" },
      { en: "Product reviews", hi: "प्रोडक्ट रिव्यू", desc: "Honest reviews and unboxing shared with the audience.", descHi: "ईमानदार रिव्यू और अनबॉक्सिंग, ऑडियंस के साथ।" },
      { en: "Event coverage", hi: "इवेंट कवरेज", desc: "Launches, store openings and events covered live and after.", descHi: "लॉन्च, दुकान का उद्घाटन और इवेंट — लाइव और बाद में।" },
      { en: "Content for your business", hi: "आपके बिज़नेस के लिए कंटेंट", desc: "Reels and photos you can use on your own pages.", descHi: "रील और फ़ोटो जो आप अपने पेज पर भी चला सकें।" },
      { en: "Giveaways & campaigns", hi: "गिवअवे और कैंपेन", desc: "Contests and campaigns planned and run with the brand.", descHi: "ब्रांड के साथ मिलकर कॉन्टेस्ट और कैंपेन की योजना और संचालन।" },
      { en: "Appearances & hosting", hi: "मौजूदगी और होस्टिंग", desc: "Meet-and-greets, store visits and hosting at events.", descHi: "मीट-एंड-ग्रीट, स्टोर विज़िट और इवेंट होस्टिंग।" },
      { en: "Follow & connect", hi: "फ़ॉलो करें और जुड़ें", desc: "All my social links in one place — follow where you like.", descHi: "सारे सोशल लिंक एक जगह — जहाँ चाहें फ़ॉलो करें।" },
    ],
    whyUs: [
      { en: "Real audience, real engagement", hi: "असली ऑडियंस, असली जुड़ाव" },
      { en: "Content in the local language", hi: "लोकल भाषा में कंटेंट" },
      { en: "Creative ideas, on time", hi: "क्रिएटिव आइडिया, समय पर" },
      { en: "Clear deliverables, no surprises", hi: "साफ़ डिलीवरेबल, कोई सरप्राइज़ नहीं" },
      { en: "Honest about what I promote", hi: "जो प्रमोट करें, ईमानदारी से" },
      { en: "Brief to post, all handled", hi: "ब्रीफ़ से पोस्ट तक, सब संभालते हैं" },
      { en: "Reach me on WhatsApp", hi: "WhatsApp पर संपर्क" },
    ],
    steps: [
      { en: "See my work", hi: "मेरा काम देखें", desc: "Profiles, past collaborations and sample content on this card.", descHi: "प्रोफ़ाइल, पिछले कोलैब और सैंपल कंटेंट कार्ड पर।" },
      { en: "Send the brief", hi: "ब्रीफ़ भेजें", desc: "Product, goal, platforms and timeline on WhatsApp.", descHi: "प्रोडक्ट, मक़सद, प्लेटफ़ॉर्म और टाइमलाइन WhatsApp पर।" },
      { en: "Agree the plan", hi: "प्लान तय करें", desc: "Deliverables, dates and charges confirmed before the shoot.", descHi: "शूट से पहले डिलीवरेबल, तारीख़ें और चार्ज तय।" },
      { en: "Content goes live", hi: "कंटेंट लाइव", desc: "Posted as agreed, with a report of how it did.", descHi: "तय समय पर पोस्ट, साथ में परफ़ॉर्मेंस की रिपोर्ट।" },
    ],
    faq: [
      { q: "How do I collaborate with you?", qHi: "आपके साथ कोलैब कैसे करें?", a: "Message the product, goal and timeline on WhatsApp; a plan and quote follow.", aHi: "प्रोडक्ट, मक़सद और टाइमलाइन WhatsApp पर भेजें; प्लान और quote मिल जाएगा।" },
      { q: "What are your charges?", qHi: "चार्ज क्या है?", a: "It depends on the platform, format and the work involved — message the brief for a quote.", aHi: "प्लेटफ़ॉर्म, फ़ॉर्मेट और काम पर निर्भर है — ब्रीफ़ भेजें, quote मिल जाएगा।" },
      { q: "Which platforms are you on?", qHi: "आप किन प्लेटफ़ॉर्म पर हैं?", a: "All the links are on this card; the main platform and the audience are mentioned there too.", aHi: "सारे लिंक कार्ड पर हैं; मुख्य प्लेटफ़ॉर्म और ऑडियंस भी वहीं लिखी है।" },
      { q: "Do you do barter collaborations?", qHi: "बार्टर कोलैब करते हैं?", a: "Sometimes, for products that fit the content; message and ask.", aHi: "कभी-कभी, जब प्रोडक्ट कंटेंट से मेल खाए; मैसेज करके पूछ लें।" },
      { q: "Can I see your past work?", qHi: "पिछला काम देख सकते हैं?", a: "Yes, samples are on the profiles linked here; ask for more on WhatsApp.", aHi: "हाँ, सैंपल लिंक की गई प्रोफ़ाइल पर हैं; और चाहिए तो WhatsApp पर माँगें।" },
      { q: "Do you travel for shoots?", qHi: "शूट के लिए बाहर आते हैं?", a: "Within the city usually; for outstation, share the details and we work it out.", aHi: "आमतौर पर शहर के अंदर; बाहर के लिए डिटेल भेजें, तय कर लेंगे।" },
      { q: "Will I get the content to use on my pages?", qHi: "क्या कंटेंट अपने पेज पर चला सकते हैं?", a: "Yes, when usage rights are part of the agreement — mention it in the brief.", aHi: "हाँ, जब इस्तेमाल के अधिकार डील में शामिल हों — ब्रीफ़ में बता दें।" },
    ],
    generic: ["connect with us", "explore options", "follow me", "know more", "get in touch", "let's collaborate"],
  },

  other: {
    explain: [
      "who you are and what you do — the work, trade or role in plain words",
      "who you help and what they come to you for",
      "where you are and when you are available",
      "how to reach you: WhatsApp, call, visit",
    ],
    // Neutral service names any trade may have (owner's call, 5 Oct 2026): the card's own features ("Save & share
    // my card") were seeding an "other" business's website as its services.
    services: [
      { en: "Consultation", hi: "परामर्श", desc: "Talk through what you need and get clear advice before any work.", descHi: "काम से पहले अपनी ज़रूरत बताएँ और साफ़ सलाह लें।" },
      { en: "Home visit", hi: "घर पर विज़िट", desc: "Service at your place when the work needs it.", descHi: "जब काम को ज़रूरत हो, आपकी जगह पर सेवा।" },
      { en: "Repair & maintenance", hi: "रिपेयर और मेंटेनेंस", desc: "Fixing what is broken and keeping things in good order.", descHi: "जो ख़राब है उसे ठीक करना और सब सही हालत में रखना।" },
      { en: "Custom orders", hi: "ऑर्डर पर काम", desc: "Work made to your requirement, size or design.", descHi: "आपकी ज़रूरत, साइज़ या डिज़ाइन के मुताबिक़ काम।" },
      { en: "Delivery", hi: "डिलीवरी", desc: "Finished work or goods brought to you.", descHi: "तैयार काम या सामान आप तक पहुँचाया जाता है।" },
      { en: "Support", hi: "सपोर्ट", desc: "Help after the work is done — questions, follow-ups and small fixes.", descHi: "काम के बाद भी मदद — सवाल, फ़ॉलो-अप और छोटे सुधार।" },
    ],
    whyUs: [
      { en: "Honest work, plain words", hi: "ईमानदार काम, सीधी बात" },
      { en: "Easy to reach", hi: "संपर्क आसान" },
      { en: "Reply on WhatsApp", hi: "WhatsApp पर जवाब" },
      { en: "Timings and address clear", hi: "समय और पता साफ़" },
      { en: "Work you can ask about", hi: "काम, जिसके बारे में पूछ सकें" },
      { en: "One card, everything in it", hi: "एक कार्ड में सब कुछ" },
    ],
    steps: [
      { en: "Read the card", hi: "कार्ड देखें", desc: "What I do, where and when — on this page.", descHi: "क्या करते हैं, कहाँ और कब — इसी पेज पर।" },
      { en: "Message your need", hi: "अपनी ज़रूरत बताएँ", desc: "Write in short what you are looking for.", descHi: "संक्षेप में लिखें क्या चाहिए।" },
      { en: "Talk it through", hi: "बात करें", desc: "A call or a meeting to settle the details.", descHi: "डिटेल तय करने के लिए कॉल या मुलाक़ात।" },
      { en: "Work begins", hi: "काम शुरू", desc: "Once agreed, the work starts as discussed.", descHi: "तय होते ही काम बातचीत के मुताबिक़ शुरू।" },
    ],
    faq: [
      { q: "What exactly do you do?", qHi: "आप असल में क्या करते हैं?", a: "The about section on this card explains the work; message on WhatsApp for your specific need.", aHi: "कार्ड का परिचय हिस्सा काम बताता है; अपनी ज़रूरत के लिए WhatsApp पर मैसेज करें।" },
      { q: "How do I contact you?", qHi: "संपर्क कैसे करें?", a: "WhatsApp is quickest; call or visit in the timings given on the card.", aHi: "WhatsApp सबसे तेज़; कार्ड पर दिए समय में कॉल या मुलाक़ात।" },
      { q: "Where are you located?", qHi: "आप कहाँ हैं?", a: "The address and map link are on the card; message before you come.", aHi: "पता और मैप लिंक कार्ड पर है; आने से पहले मैसेज कर दें।" },
      { q: "What are your timings?", qHi: "समय क्या है?", a: "See the timings on this page, or message to check for a particular day.", aHi: "इसी पेज पर समय देखें, या किसी ख़ास दिन के लिए मैसेज करके पूछ लें।" },
      { q: "What does it cost?", qHi: "ख़र्च कितना आएगा?", a: "It depends on the work; share the details on WhatsApp for a clear estimate.", aHi: "काम पर निर्भर है; WhatsApp पर डिटेल भेजें, साफ़ अनुमान मिल जाएगा।" },
      { q: "Can I get a reference?", qHi: "कोई रेफ़रेंस मिल सकता है?", a: "Yes, ask and we connect you with people who have worked with us.", aHi: "हाँ, पूछें — जिनके साथ काम किया है, उनसे जोड़ देंगे।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, bank transfer or cash, whichever is agreed before the work starts.", aHi: "UPI, बैंक ट्रांसफ़र या नक़द, जैसा काम से पहले तय हो।" },
    ],
    generic: ["connect with us", "explore options", "contact us", "know more", "get in touch", "our services"],
  },
};

export const PERSONAL_DEFAULT: TradeData = {
  explain: [
    "who you are — name, what you do and where you are based",
    "what people come to you for and what you are known for",
    "a little about your family, interests or community work, if you like",
    "how to reach you: WhatsApp, call, address",
  ],
  services: [
    { en: "About me", hi: "मेरे बारे में", desc: "Who I am, what I do and where I am based.", descHi: "मैं कौन, क्या काम और कहाँ से।" },
    { en: "Save my contact", hi: "मेरा नंबर सेव करें", desc: "Phone, WhatsApp, email and address in one tap.", descHi: "फ़ोन, WhatsApp, ईमेल और पता एक टैप में।" },
    { en: "Work & enquiries", hi: "काम और पूछताछ", desc: "Message for anything related to my work.", descHi: "मेरे काम से जुड़ी किसी भी बात के लिए मैसेज करें।" },
    { en: "Meet or call", hi: "मिलें या कॉल करें", desc: "Fix a time on WhatsApp that suits us both.", descHi: "WhatsApp पर दोनों की सुविधा का समय तय करें।" },
    { en: "Social links", hi: "सोशल लिंक", desc: "Instagram, Facebook, LinkedIn — all in one place.", descHi: "Instagram, Facebook, LinkedIn — सब एक जगह।" },
    { en: "Invitations & greetings", hi: "निमंत्रण और शुभकामनाएँ", desc: "Family functions and festival wishes shared from here.", descHi: "परिवार के फ़ंक्शन और त्योहार की शुभकामनाएँ यहीं से।" },
    { en: "Share my card", hi: "कार्ड शेयर करें", desc: "Forward the link; it always shows my latest details.", descHi: "लिंक आगे भेजें; इसमें हमेशा मेरी ताज़ा जानकारी रहती है।" },
  ],
  whyUs: [
    { en: "All my details, one link", hi: "सारी जानकारी, एक लिंक" },
    { en: "Always up to date", hi: "हमेशा अपडेट" },
    { en: "Easy to save and share", hi: "सेव और शेयर करना आसान" },
    { en: "Reply on WhatsApp", hi: "WhatsApp पर जवाब" },
    { en: "No paper card to lose", hi: "काग़ज़ का कार्ड खोने का डर नहीं" },
    { en: "Simple and personal", hi: "सीधा और अपना" },
  ],
  steps: [
    { en: "Open the card", hi: "कार्ड खोलें", desc: "See who I am and what I do.", descHi: "देखें मैं कौन और क्या काम।" },
    { en: "Save the contact", hi: "नंबर सेव करें", desc: "One tap adds me to your phone.", descHi: "एक टैप में नंबर आपके फ़ोन में।" },
    { en: "Message me", hi: "मैसेज करें", desc: "Say hello or tell me what you need on WhatsApp.", descHi: "WhatsApp पर हेलो कहें या ज़रूरत बताएँ।" },
  ],
  faq: [
    { q: "How do I save your contact?", qHi: "आपका नंबर कैसे सेव करूँ?", a: "Tap the save button on this card; the number, email and address go into your phone.", aHi: "कार्ड पर सेव बटन दबाएँ; नंबर, ईमेल और पता आपके फ़ोन में आ जाएगा।" },
    { q: "Is this number on WhatsApp?", qHi: "क्या यह नंबर WhatsApp पर है?", a: "Yes — tap the WhatsApp button on the card to message directly.", aHi: "हाँ — कार्ड पर WhatsApp बटन दबाएँ और सीधे मैसेज करें।" },
    { q: "What do you do?", qHi: "आप क्या करते हैं?", a: "It is on the card under about; message for anything specific.", aHi: "कार्ड के परिचय में लिखा है; कुछ ख़ास पूछना हो तो मैसेज करें।" },
    { q: "Where are you based?", qHi: "आप कहाँ रहते हैं?", a: "City and address are on the card with a map link.", aHi: "शहर और पता कार्ड पर है, मैप लिंक के साथ।" },
    { q: "Can I share this card?", qHi: "यह कार्ड शेयर कर सकते हैं?", a: "Yes, forward the link on WhatsApp; it always opens with my latest details.", aHi: "हाँ, लिंक WhatsApp पर आगे भेजें; इसमें हमेशा मेरी ताज़ा जानकारी खुलती है।" },
    { q: "When is a good time to call?", qHi: "कॉल करने का सही समय?", a: "Message first on WhatsApp and a call back comes when free.", aHi: "पहले WhatsApp पर मैसेज करें, फ़्री होते ही कॉल बैक मिलेगा।" },
    { q: "Can we connect on social media?", qHi: "सोशल मीडिया पर जुड़ सकते हैं?", a: "Yes, the links are on the card; follow or send a request.", aHi: "हाँ, लिंक कार्ड पर हैं; फ़ॉलो करें या रिक्वेस्ट भेजें।" },
  ],
  generic: ["connect with us", "explore options", "get in touch", "know more", "contact me"],
};
