// Retail trades: kirana, garments, jewellery, mobile / electronics, furniture, hardware / paint / sanitary, medical store,
// online store, gift / stationery, optical, footwear. See types.ts for the rules (no numbers, no claims; true of any decent shop of the trade).
import type { TradeData } from "./types";

export const RETAIL: Record<string, TradeData> = {
  kirana: {
    explain: [
      "what the store stocks (groceries, staples, dairy, household items, personal care) and the brands people ask for",
      "daily needs delivered home — order on WhatsApp or by phone",
      "monthly ration lists, bulk and shop-to-shop supply",
      "timings, location and how to order",
    ],
    services: [
      { en: "Daily groceries & staples", hi: "रोज़ का राशन और किराना", desc: "Atta, rice, dal, oil, spices and everyday groceries under one roof.", descHi: "आटा, चावल, दाल, तेल, मसाले और रोज़ का सामान एक ही जगह।" },
      { en: "Home delivery", hi: "होम डिलीवरी", desc: "Send your list on WhatsApp and we deliver in the neighbourhood.", descHi: "WhatsApp पर लिस्ट भेजें, आस-पास के इलाक़े में घर तक डिलीवरी।" },
      { en: "Monthly ration order", hi: "महीने का राशन", desc: "Your full monthly list packed and delivered together.", descHi: "पूरे महीने की लिस्ट एक साथ पैक होकर घर पहुँचती है।" },
      { en: "Dairy, bread & eggs", hi: "दूध, ब्रेड और अंडे", desc: "Fresh daily items stocked every morning.", descHi: "रोज़ सुबह ताज़ा दूध, ब्रेड और अंडे।" },
      { en: "Household & personal care", hi: "घरेलू और पर्सनल केयर", desc: "Soaps, detergents, cleaning and toiletries from trusted brands.", descHi: "साबुन, डिटर्जेंट, सफ़ाई का सामान और टॉयलेट्रीज़ — जाने-पहचाने ब्रांड।" },
      { en: "Bulk & shop supply", hi: "थोक और दुकान सप्लाई", desc: "Supply for hostels, canteens, offices and smaller shops.", descHi: "हॉस्टल, कैंटीन, ऑफ़िस और छोटी दुकानों के लिए सप्लाई।" },
      { en: "Recharge & bill payments", hi: "रिचार्ज और बिल पेमेंट", desc: "Mobile recharge, DTH and small bill payments at the counter.", descHi: "काउंटर पर मोबाइल रिचार्ज, DTH और छोटे बिल।" },
    ],
    whyUs: [
      { en: "Trusted brands only", hi: "सिर्फ़ भरोसेमंद ब्रांड" },
      { en: "Fresh stock, dates checked", hi: "ताज़ा स्टॉक, तारीख़ देखकर" },
      { en: "Fair prices, printed MRP", hi: "वाजिब दाम, छपी MRP" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
      { en: "Delivered to your door", hi: "घर तक डिलीवरी" },
      { en: "Damaged item replaced", hi: "ख़राब सामान बदल देते हैं" },
      { en: "Your neighbourhood shop", hi: "आपके मोहल्ले की दुकान" },
    ],
    steps: [
      { en: "Send your list", hi: "लिस्ट भेजें", desc: "WhatsApp the items and quantities, or call the shop.", descHi: "WhatsApp पर चीज़ें और मात्रा भेजें, या फ़ोन करें।" },
      { en: "We pack it", hi: "हम पैक करते हैं", desc: "Everything is picked fresh and packed; we tell you the bill.", descHi: "सब ताज़ा निकालकर पैक; बिल बता देते हैं।" },
      { en: "Pick up or get it delivered", hi: "ले जाएँ या मँगवाएँ", desc: "Collect from the shop or we deliver at home; pay by UPI or cash.", descHi: "दुकान से लें या घर पर मँगवाएँ; UPI या नक़द।" },
    ],
    faq: [
      { q: "Do you deliver at home?", qHi: "क्या होम डिलीवरी करते हैं?", a: "Yes, in the nearby area. Send your list and location on WhatsApp and we will confirm.", aHi: "हाँ, आस-पास के इलाक़े में। WhatsApp पर लिस्ट और लोकेशन भेजें, हम कन्फ़र्म कर देंगे।" },
      { q: "Can I order my whole month's ration?", qHi: "पूरे महीने का राशन ऑर्डर हो सकता है?", a: "Yes. Send the full list once; we pack it together and can repeat it every month.", aHi: "हाँ। पूरी लिस्ट एक बार भेज दें; हम साथ पैक करते हैं और हर महीने दोहरा सकते हैं।" },
      { q: "Is there a minimum order for delivery?", qHi: "डिलीवरी के लिए कम से कम कितना ऑर्डर?", a: "Small orders are also fine nearby; for farther areas message us and we will tell you.", aHi: "आस-पास छोटे ऑर्डर भी ठीक हैं; दूर के इलाक़े के लिए मैसेज करें, बता देंगे।" },
      { q: "What if an item is damaged or expired?", qHi: "सामान ख़राब या एक्सपायर्ड निकले तो?", a: "Bring it back with the bill and we replace it; we check dates before packing.", aHi: "बिल के साथ वापस लाएँ, बदल देंगे; पैक करने से पहले तारीख़ देखते हैं।" },
      { q: "Do you keep specific brands?", qHi: "कोई खास ब्रांड रखते हैं?", a: "We stock the brands people ask for; message us the item and we will check or arrange it.", aHi: "जो ब्रांड लोग माँगते हैं वो रखते हैं; चीज़ का नाम भेजें, देखकर या मँगवाकर बताएँगे।" },
      { q: "Do you do recharge and bill payments?", qHi: "रिचार्ज और बिल पेमेंट होता है?", a: "Yes, mobile recharge, DTH and some bill payments are done at the counter.", aHi: "हाँ, काउंटर पर मोबाइल रिचार्ज, DTH और कुछ बिल भरे जाते हैं।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the shop; UPI for WhatsApp orders and delivery.", aHi: "दुकान पर नक़द, UPI और कार्ड; WhatsApp ऑर्डर और डिलीवरी के लिए UPI।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best quality", "all items available", "customer satisfaction"],
  },

  garments: {
    explain: [
      "what you sell (men's / women's / kids' wear, ethnic, western, sarees, suits, school uniforms) and the brands or own label",
      "fitting, alteration and trial; sizes for everyone",
      "festival and wedding collection; bulk and uniform orders",
      "exchange policy and how to shop: walk in or WhatsApp",
    ],
    services: [
      { en: "Men's, women's & kids' wear", hi: "पुरुष, महिला और बच्चों के कपड़े", desc: "Everyday wear, office wear and party wear for the whole family.", descHi: "पूरे परिवार के लिए रोज़ के, ऑफ़िस और पार्टी के कपड़े।" },
      { en: "Ethnic & wedding wear", hi: "एथनिक और शादी के कपड़े", desc: "Sarees, lehengas, kurtas and sherwanis for functions and festivals.", descHi: "फ़ंक्शन और त्योहार के लिए साड़ी, लहंगा, कुर्ता और शेरवानी।" },
      { en: "Alteration & fitting", hi: "ऑल्टरेशन और फ़िटिंग", desc: "Length, waist and sleeve adjusted so it fits you right.", descHi: "लंबाई, कमर और बाँह ठीक करके सही फ़िटिंग।" },
      { en: "School & office uniforms", hi: "स्कूल और ऑफ़िस यूनिफ़ॉर्म", desc: "Uniforms in all sizes, with bulk orders for schools and staff.", descHi: "हर साइज़ में यूनिफ़ॉर्म, स्कूल और स्टाफ़ के लिए थोक ऑर्डर।" },
      { en: "Easy exchange", hi: "आसान एक्सचेंज", desc: "Wrong size or colour? Exchange with the bill and tags intact.", descHi: "साइज़ या रंग ग़लत? बिल और टैग के साथ बदल लें।" },
      { en: "Festival collection", hi: "त्योहार कलेक्शन", desc: "New stock for Diwali, Eid, Rakhi and the wedding season.", descHi: "दिवाली, ईद, राखी और शादी के सीज़न के लिए नया स्टॉक।" },
      { en: "WhatsApp shopping", hi: "WhatsApp पर खरीदारी", desc: "Ask for photos of new arrivals and reserve your piece.", descHi: "नए माल की फ़ोटो मँगवाएँ और अपना पीस रखवा लें।" },
    ],
    whyUs: [
      { en: "Latest designs, every season", hi: "हर सीज़न नए डिज़ाइन" },
      { en: "Sizes for everyone", hi: "हर साइज़ उपलब्ध" },
      { en: "Trial room and honest advice", hi: "ट्रायल रूम, सच्ची सलाह" },
      { en: "Alteration done in-house", hi: "ऑल्टरेशन यहीं होता है" },
      { en: "Easy exchange with bill", hi: "बिल पर आसान एक्सचेंज" },
      { en: "Fair, fixed prices", hi: "वाजिब, तय दाम" },
      { en: "New arrivals on WhatsApp", hi: "WhatsApp पर नया माल" },
    ],
    steps: [
      { en: "Browse or ask", hi: "देखें या पूछें", desc: "Visit the showroom or ask for photos on WhatsApp.", descHi: "शोरूम आएँ या WhatsApp पर फ़ोटो माँगें।" },
      { en: "Try it on", hi: "पहनकर देखें", desc: "Trial room for the right size; we suggest what suits you.", descHi: "सही साइज़ के लिए ट्रायल रूम; क्या जँचेगा हम बताते हैं।" },
      { en: "Fitting if needed", hi: "ज़रूरत हो तो फ़िटिंग", desc: "Alteration done here; collect when ready.", descHi: "ऑल्टरेशन यहीं; तैयार होने पर ले जाएँ।" },
      { en: "Wear it happily", hi: "खुशी से पहनें", desc: "Keep the bill — exchange is easy if something is not right.", descHi: "बिल संभालकर रखें — कुछ ठीक न लगे तो एक्सचेंज आसान है।" },
    ],
    faq: [
      { q: "Do you have a trial room?", qHi: "ट्रायल रूम है?", a: "Yes, try before you buy; our staff helps you find the right size.", aHi: "हाँ, खरीदने से पहले पहनकर देखें; स्टाफ़ सही साइज़ ढूँढने में मदद करता है।" },
      { q: "Can I exchange if the size is wrong?", qHi: "साइज़ ग़लत हो तो बदल सकते हैं?", a: "Yes, with the bill and tags intact, within the exchange period we tell you at billing.", aHi: "हाँ, बिल और टैग सही हों तो, बिलिंग पर बताई गई अवधि में।" },
      { q: "Do you do alteration?", qHi: "ऑल्टरेशन करते हैं?", a: "Yes, length and fitting are adjusted here; ask at billing when it will be ready.", aHi: "हाँ, लंबाई और फ़िटिंग यहीं ठीक होती है; बिलिंग पर पूछ लें कब तैयार होगा।" },
      { q: "Do you take bulk or uniform orders?", qHi: "थोक या यूनिफ़ॉर्म ऑर्डर लेते हैं?", a: "Yes, for schools, offices and events. Message us the sizes and quantity for a quote.", aHi: "हाँ, स्कूल, ऑफ़िस और इवेंट के लिए। साइज़ और मात्रा भेजें, कोटेशन देंगे।" },
      { q: "Can I see new arrivals on WhatsApp?", qHi: "नया माल WhatsApp पर देख सकते हैं?", a: "Yes, message us what you are looking for and we send photos and sizes.", aHi: "हाँ, बताएँ क्या चाहिए, हम फ़ोटो और साइज़ भेज देंगे।" },
      { q: "Do you have plus sizes?", qHi: "बड़े साइज़ मिलते हैं?", a: "We keep a wide range of sizes; message us the size and item to check.", aHi: "साइज़ की अच्छी रेंज रखते हैं; साइज़ और चीज़ बताएँ, देखकर बताएँगे।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the showroom; UPI for reserved pieces on WhatsApp.", aHi: "शोरूम पर नक़द, UPI और कार्ड; WhatsApp पर रखवाए पीस के लिए UPI।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "latest fashion", "best collection", "customer satisfaction"],
  },

  jewellery: {
    explain: [
      "what you make and sell (gold, silver, diamond, bridal sets, daily wear, coins) and your speciality",
      "hallmarked gold and transparent billing with the weight and making charges shown",
      "custom design, old gold exchange, repair and polish",
      "wedding and festival buying; how to start — visit or WhatsApp",
    ],
    services: [
      { en: "Gold & silver jewellery", hi: "सोने-चाँदी के गहने", desc: "Hallmarked gold and silver — rings, chains, bangles, earrings and sets.", descHi: "हॉलमार्क सोना और चाँदी — अँगूठी, चेन, चूड़ी, झुमके और सेट।" },
      { en: "Bridal & wedding sets", hi: "ब्राइडल और शादी के सेट", desc: "Complete bridal sets and family jewellery for weddings.", descHi: "शादी के लिए पूरे ब्राइडल सेट और परिवार के गहने।" },
      { en: "Custom design", hi: "कस्टम डिज़ाइन", desc: "Bring a photo or an idea; we make it to your taste.", descHi: "फ़ोटो या आइडिया लाएँ; आपकी पसंद से बनवाते हैं।" },
      { en: "Old gold exchange", hi: "पुराना सोना एक्सचेंज", desc: "Exchange old jewellery for new at the day's rate, weighed in front of you.", descHi: "पुराने गहने दिन के भाव पर नए से बदलें, आपके सामने तोलकर।" },
      { en: "Repair & polish", hi: "रिपेयर और पॉलिश", desc: "Broken chains, loose stones, resizing and polishing done here.", descHi: "टूटी चेन, ढीला नग, साइज़ बदलना और पॉलिश यहीं।" },
      { en: "Coins & gifting", hi: "सिक्के और गिफ़्टिंग", desc: "Gold and silver coins and small pieces for pooja, birth and gifting.", descHi: "पूजा, जन्म और गिफ़्ट के लिए सोने-चाँदी के सिक्के और छोटे पीस।" },
      { en: "Easy payment options", hi: "आसान भुगतान विकल्प", desc: "Advance booking, savings schemes or card EMI — ask at the counter.", descHi: "एडवांस बुकिंग, बचत योजना या कार्ड EMI — काउंटर पर पूछें।" },
    ],
    whyUs: [
      { en: "Hallmarked gold, always", hi: "हमेशा हॉलमार्क सोना" },
      { en: "Weight and rate shown clearly", hi: "वज़न और भाव साफ़ दिखता है" },
      { en: "Old gold exchanged fairly", hi: "पुराना सोना सही भाव पर" },
      { en: "Custom designs made here", hi: "कस्टम डिज़ाइन यहीं बनते हैं" },
      { en: "Repair and polish after sale", hi: "बिक्री के बाद रिपेयर-पॉलिश" },
      { en: "Honest advice on buying", hi: "खरीद पर सच्ची सलाह" },
      { en: "Proper bill for every piece", hi: "हर पीस का पक्का बिल" },
    ],
    steps: [
      { en: "Tell us what you want", hi: "बताएँ क्या चाहिए", desc: "Visit the showroom or send a photo or design on WhatsApp.", descHi: "शोरूम आएँ या WhatsApp पर फ़ोटो या डिज़ाइन भेजें।" },
      { en: "See the rate and weight", hi: "भाव और वज़न देखें", desc: "We show the day's rate, weight and making charges before you decide.", descHi: "तय करने से पहले दिन का भाव, वज़न और मेकिंग चार्ज दिखाते हैं।" },
      { en: "Made or ready", hi: "बनकर या तैयार", desc: "Pick from stock, or a custom piece is made for your date.", descHi: "स्टॉक से चुनें, या आपकी तारीख़ के लिए कस्टम पीस बनता है।" },
      { en: "Collect with bill", hi: "बिल के साथ ले जाएँ", desc: "Hallmark checked, proper bill given; come back for polish any time.", descHi: "हॉलमार्क जाँचकर, पक्का बिल; पॉलिश के लिए कभी भी आएँ।" },
    ],
    faq: [
      { q: "Is the gold hallmarked?", qHi: "सोना हॉलमार्क है?", a: "Yes, our gold jewellery is hallmarked and the purity is shown on the bill.", aHi: "हाँ, हमारे सोने के गहने हॉलमार्क हैं और शुद्धता बिल पर लिखी होती है।" },
      { q: "Do you exchange old gold?", qHi: "पुराना सोना बदलते हैं?", a: "Yes. It is weighed and checked in front of you and adjusted against the new piece at the day's rate.", aHi: "हाँ। आपके सामने तोलकर जाँचते हैं और दिन के भाव पर नए पीस में एडजस्ट करते हैं।" },
      { q: "Can you make a design from a photo?", qHi: "फ़ोटो से डिज़ाइन बन सकता है?", a: "Yes, send the photo on WhatsApp; we tell you the weight, cost and when it will be ready.", aHi: "हाँ, WhatsApp पर फ़ोटो भेजें; वज़न, ख़र्च और तैयार होने का समय बता देंगे।" },
      { q: "Do you repair and polish old jewellery?", qHi: "पुराने गहनों की रिपेयर और पॉलिश होती है?", a: "Yes, chains, clasps, stones and resizing; polishing is done for pieces bought here and others too.", aHi: "हाँ, चेन, हुक, नग और साइज़; पॉलिश यहाँ के और बाहर के गहनों की भी।" },
      { q: "How is the price decided?", qHi: "दाम कैसे तय होता है?", a: "By weight at the day's rate plus making charges; everything is shown on the bill.", aHi: "वज़न और दिन के भाव से, साथ में मेकिंग चार्ज; सब बिल पर लिखा होता है।" },
      { q: "Can I book for a wedding date?", qHi: "शादी की तारीख़ के लिए बुक कर सकते हैं?", a: "Yes, book with an advance and the pieces are kept or made ready for your date.", aHi: "हाँ, एडवांस देकर बुक करें, पीस आपकी तारीख़ के लिए रख या बनाकर तैयार होते हैं।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, cards, bank transfer and cash as the rules allow; ask about EMI.", aHi: "UPI, कार्ड, बैंक ट्रांसफ़र और नियम अनुसार नक़द; EMI के बारे में पूछ लें।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best designs", "pure gold", "customer satisfaction"],
  },

  mobile: {
    explain: [
      "what you sell (smartphones, feature phones, accessories, TV, speakers, small appliances) and the brands",
      "repair and service: screen, battery, software, data transfer",
      "exchange of old phones, EMI and finance help, bill and warranty",
      "how to buy: walk in or ask on WhatsApp",
    ],
    services: [
      { en: "Smartphones & feature phones", hi: "स्मार्टफ़ोन और कीपैड फ़ोन", desc: "All popular brands with company bill and warranty.", descHi: "सभी लोकप्रिय ब्रांड, कंपनी बिल और वारंटी के साथ।" },
      { en: "Accessories", hi: "एक्सेसरीज़", desc: "Covers, screen guards, chargers, earphones and power banks.", descHi: "कवर, स्क्रीन गार्ड, चार्जर, ईयरफ़ोन और पावर बैंक।" },
      { en: "Repair & service", hi: "रिपेयर और सर्विस", desc: "Screen, battery, charging port and software issues fixed here.", descHi: "स्क्रीन, बैटरी, चार्जिंग पोर्ट और सॉफ़्टवेयर की समस्या यहीं ठीक।" },
      { en: "Old phone exchange", hi: "पुराना फ़ोन एक्सचेंज", desc: "Exchange your old phone and pay the difference on a new one.", descHi: "पुराना फ़ोन देकर नए पर सिर्फ़ फ़र्क़ चुकाएँ।" },
      { en: "EMI & finance help", hi: "EMI और फ़ाइनेंस में मदद", desc: "Buy on easy EMI with a card or finance company; we do the paperwork.", descHi: "कार्ड या फ़ाइनेंस कंपनी से आसान EMI; काग़ज़ी काम हम करते हैं।" },
      { en: "Setup & data transfer", hi: "सेटअप और डेटा ट्रांसफ़र", desc: "New phone set up, contacts and photos moved, screen guard fitted.", descHi: "नया फ़ोन सेट, कॉन्टैक्ट और फ़ोटो ट्रांसफ़र, स्क्रीन गार्ड लगाकर।" },
      { en: "Electronics & appliances", hi: "इलेक्ट्रॉनिक्स और अप्लायंसेज़", desc: "TV, speakers, smartwatches and small appliances — ask us.", descHi: "TV, स्पीकर, स्मार्टवॉच और छोटे अप्लायंसेज़ — पूछ लें।" },
    ],
    whyUs: [
      { en: "Genuine products, company bill", hi: "असली माल, कंपनी बिल" },
      { en: "Repair done in front of you", hi: "रिपेयर आपके सामने" },
      { en: "Fair exchange value", hi: "पुराने फ़ोन का सही दाम" },
      { en: "EMI paperwork handled here", hi: "EMI का काम यहीं" },
      { en: "Honest advice, no pushing", hi: "सच्ची सलाह, कोई दबाव नहीं" },
      { en: "Setup and data transfer help", hi: "सेटअप और डेटा में मदद" },
      { en: "Ask on WhatsApp", hi: "WhatsApp पर पूछें" },
    ],
    steps: [
      { en: "Tell us your budget and need", hi: "बजट और ज़रूरत बताएँ", desc: "Camera, battery, gaming or simple use — we suggest the right phone.", descHi: "कैमरा, बैटरी, गेमिंग या सादा इस्तेमाल — सही फ़ोन सुझाते हैं।" },
      { en: "Check exchange or EMI", hi: "एक्सचेंज या EMI देखें", desc: "Bring your old phone for a value; ask about EMI options.", descHi: "पुराना फ़ोन लाएँ, दाम बताते हैं; EMI के विकल्प पूछें।" },
      { en: "Buy with bill", hi: "बिल के साथ खरीदें", desc: "Sealed box opened in front of you, bill and warranty card given.", descHi: "सील बॉक्स आपके सामने खुलता है, बिल और वारंटी कार्ड मिलता है।" },
      { en: "Setup and go", hi: "सेटअप करके ले जाएँ", desc: "Data transferred, guard and cover fitted; service support later.", descHi: "डेटा ट्रांसफ़र, गार्ड और कवर लगाकर; बाद में सर्विस में मदद।" },
    ],
    faq: [
      { q: "Do you give a company bill and warranty?", qHi: "कंपनी बिल और वारंटी देते हैं?", a: "Yes, every phone comes with a proper bill and the brand's warranty.", aHi: "हाँ, हर फ़ोन के साथ पक्का बिल और ब्रांड की वारंटी मिलती है।" },
      { q: "Can I buy on EMI?", qHi: "EMI पर ले सकते हैं?", a: "Yes, with a credit or debit card or through a finance company; bring your ID and we help with the process.", aHi: "हाँ, क्रेडिट/डेबिट कार्ड या फ़ाइनेंस कंपनी से; आईडी लाएँ, प्रक्रिया में हम मदद करते हैं।" },
      { q: "Do you take old phones in exchange?", qHi: "पुराना फ़ोन एक्सचेंज में लेते हैं?", a: "Yes, bring it to the shop; the value depends on the model and condition.", aHi: "हाँ, दुकान पर लाएँ; दाम मॉडल और हालत पर निर्भर करता है।" },
      { q: "Do you repair phones?", qHi: "फ़ोन रिपेयर करते हैं?", a: "Yes — screen, battery, charging and software. Message the model and problem for an estimate.", aHi: "हाँ — स्क्रीन, बैटरी, चार्जिंग और सॉफ़्टवेयर। मॉडल और समस्या भेजें, अंदाज़ा बता देंगे।" },
      { q: "Will you transfer my data to the new phone?", qHi: "नए फ़ोन में डेटा ट्रांसफ़र करेंगे?", a: "Yes, contacts, photos and apps are moved and the phone is set up before you leave.", aHi: "हाँ, कॉन्टैक्ट, फ़ोटो और ऐप ट्रांसफ़र करके फ़ोन सेट करके देते हैं।" },
      { q: "Is a model in stock?", qHi: "कोई मॉडल स्टॉक में है?", a: "Message us the model and colour on WhatsApp; we confirm or arrange it for you.", aHi: "WhatsApp पर मॉडल और रंग भेजें; कन्फ़र्म करेंगे या मँगवा देंगे।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI, cards and EMI at the shop; UPI advance to reserve a phone.", aHi: "दुकान पर नक़द, UPI, कार्ड और EMI; फ़ोन रखवाने के लिए UPI एडवांस।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "latest technology", "best deals", "customer satisfaction"],
  },

  furniture: {
    explain: [
      "what you make and sell (sofas, beds, dining, wardrobes, office furniture, mattresses, decor) and the materials (teak, sheesham, engineered wood, steel)",
      "custom sizes and designs, made to order; modular kitchen and wardrobes if any",
      "home delivery, installation and after-sale repair or polish",
      "how to start: visit the showroom or share room photos on WhatsApp",
    ],
    services: [
      { en: "Home furniture", hi: "घर का फ़र्नीचर", desc: "Sofas, beds, dining sets, wardrobes and tables for every room.", descHi: "हर कमरे के लिए सोफ़ा, बेड, डाइनिंग, अलमारी और टेबल।" },
      { en: "Custom & made to order", hi: "कस्टम और ऑर्डर पर", desc: "Your size, wood and finish — made for your room.", descHi: "आपका साइज़, लकड़ी और फ़िनिश — आपके कमरे के हिसाब से।" },
      { en: "Office furniture", hi: "ऑफ़िस फ़र्नीचर", desc: "Desks, chairs, storage and reception furniture for offices and shops.", descHi: "ऑफ़िस और दुकान के लिए डेस्क, कुर्सी, स्टोरेज और रिसेप्शन।" },
      { en: "Delivery & installation", hi: "डिलीवरी और इंस्टॉलेशन", desc: "Delivered to your home and assembled in place by our team.", descHi: "घर तक डिलीवरी और हमारी टीम जगह पर फ़िट करती है।" },
      { en: "Mattresses & decor", hi: "गद्दे और डेकोर", desc: "Mattresses, curtains, lamps and decor pieces to complete the room.", descHi: "कमरा पूरा करने के लिए गद्दे, पर्दे, लैंप और डेकोर।" },
      { en: "Repair & polish", hi: "रिपेयर और पॉलिश", desc: "Old furniture repaired, re-polished or re-upholstered.", descHi: "पुराना फ़र्नीचर रिपेयर, दोबारा पॉलिश या नया कपड़ा।" },
      { en: "EMI & easy payment", hi: "EMI और आसान भुगतान", desc: "Card EMI and advance booking for bigger purchases — ask us.", descHi: "बड़ी खरीद के लिए कार्ड EMI और एडवांस बुकिंग — पूछ लें।" },
    ],
    whyUs: [
      { en: "Solid build, honest materials", hi: "मज़बूत बनावट, सही सामग्री" },
      { en: "Custom sizes for your room", hi: "आपके कमरे के हिसाब से साइज़" },
      { en: "Delivered and fitted at home", hi: "घर पर डिलीवरी और फ़िटिंग" },
      { en: "Showroom to see and sit", hi: "देखकर, बैठकर परखें" },
      { en: "Repair and polish after sale", hi: "बिक्री के बाद रिपेयर-पॉलिश" },
      { en: "Clear price, no surprises", hi: "साफ़ दाम, कोई छिपा ख़र्च नहीं" },
      { en: "Advice on what fits where", hi: "क्या कहाँ जँचेगा, सलाह" },
    ],
    steps: [
      { en: "Share your room", hi: "कमरा दिखाएँ", desc: "Visit the showroom or send photos and measurements on WhatsApp.", descHi: "शोरूम आएँ या WhatsApp पर फ़ोटो और नाप भेजें।" },
      { en: "Choose design and material", hi: "डिज़ाइन और सामग्री चुनें", desc: "We suggest sizes, wood and fabric to your budget; you finalise.", descHi: "बजट के हिसाब से साइज़, लकड़ी और कपड़ा सुझाते हैं; आप तय करें।" },
      { en: "Made or ready", hi: "बनकर या तैयार", desc: "Pick from stock, or your piece is made to order with an advance.", descHi: "स्टॉक से लें, या एडवांस देकर आपका पीस ऑर्डर पर बनता है।" },
      { en: "Delivered and fitted", hi: "डिलीवरी और फ़िटिंग", desc: "Our team delivers, assembles and sets it in place.", descHi: "हमारी टीम लाकर जोड़ती है और जगह पर रखती है।" },
    ],
    faq: [
      { q: "Can you make furniture in a custom size?", qHi: "कस्टम साइज़ में बन सकता है?", a: "Yes, most pieces are made to your measurement and finish; share the size on WhatsApp.", aHi: "हाँ, ज़्यादातर चीज़ें आपके नाप और फ़िनिश में बनती हैं; WhatsApp पर नाप भेजें।" },
      { q: "Do you deliver and assemble at home?", qHi: "घर पर डिलीवरी और फ़िटिंग करते हैं?", a: "Yes, our team delivers and assembles it in your room; ask about charges for your area.", aHi: "हाँ, हमारी टीम लाकर आपके कमरे में फ़िट करती है; अपने इलाक़े के चार्ज पूछ लें।" },
      { q: "Which wood or material do you use?", qHi: "कौन सी लकड़ी या सामग्री?", a: "Teak, sheesham, engineered wood, metal — depends on the piece and budget; we explain the difference.", aHi: "सागौन, शीशम, इंजीनियर्ड वुड, मेटल — पीस और बजट पर निर्भर; हम फ़र्क़ समझाते हैं।" },
      { q: "How long does a made-to-order piece take?", qHi: "ऑर्डर का पीस कितने दिन में?", a: "It depends on the design and material; we tell you the date at the time of order.", aHi: "डिज़ाइन और सामग्री पर निर्भर है; ऑर्डर के समय तारीख़ बता देते हैं।" },
      { q: "Do you repair or polish old furniture?", qHi: "पुराना फ़र्नीचर रिपेयर या पॉलिश करते हैं?", a: "Yes, send photos of the piece on WhatsApp and we quote for repair, polish or new fabric.", aHi: "हाँ, WhatsApp पर पीस की फ़ोटो भेजें, रिपेयर, पॉलिश या नए कपड़े का कोटेशन देंगे।" },
      { q: "Is EMI available?", qHi: "EMI मिलती है?", a: "Card EMI is available on bigger purchases; ask at the showroom for the options.", aHi: "बड़ी खरीद पर कार्ड EMI है; विकल्प शोरूम पर पूछ लें।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "An advance at order, balance on delivery; cash, UPI, cards or bank transfer.", aHi: "ऑर्डर पर एडवांस, बाक़ी डिलीवरी पर; नक़द, UPI, कार्ड या बैंक ट्रांसफ़र।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best furniture", "modern designs", "customer satisfaction"],
  },

  hardware: {
    explain: [
      "what you stock (paints, sanitary ware, pipes and fittings, tools, electricals, cement and building material) and the brands",
      "help for builders, contractors, plumbers and painters; site delivery and bulk rates",
      "colour matching and paint mixing; advice on what to buy for a job",
      "how to order: list on WhatsApp, delivery to site",
    ],
    services: [
      { en: "Paints & colour mixing", hi: "पेंट और रंग मिक्सिंग", desc: "Interior, exterior and wood paints; shades mixed on the machine.", descHi: "अंदर, बाहर और लकड़ी के पेंट; मशीन पर शेड मिक्स।" },
      { en: "Sanitary & bathroom fittings", hi: "सैनिटरी और बाथरूम फ़िटिंग", desc: "Taps, showers, basins, commodes and pipes from known brands.", descHi: "जाने-माने ब्रांड के नल, शावर, बेसिन, कमोड और पाइप।" },
      { en: "Hardware & tools", hi: "हार्डवेयर और औज़ार", desc: "Locks, hinges, screws, hand and power tools for every job.", descHi: "हर काम के लिए ताले, कब्ज़े, स्क्रू, हाथ और पावर टूल।" },
      { en: "Electrical fittings", hi: "इलेक्ट्रिकल फ़िटिंग", desc: "Wires, switches, lights, fans and MCBs.", descHi: "तार, स्विच, लाइट, पंखे और MCB।" },
      { en: "Site delivery", hi: "साइट डिलीवरी", desc: "Bulk material delivered to your site or building.", descHi: "थोक सामान आपकी साइट या बिल्डिंग तक।" },
      { en: "Contractor & builder supply", hi: "ठेकेदार और बिल्डर सप्लाई", desc: "Regular supply and bulk rates for contractors and plumbers.", descHi: "ठेकेदार और प्लंबर के लिए नियमित सप्लाई और थोक दर।" },
      { en: "Advice & estimates", hi: "सलाह और अंदाज़ा", desc: "Tell us the job; we help you list what you need.", descHi: "काम बताएँ; क्या-क्या लगेगा, लिस्ट बनाने में मदद।" },
    ],
    whyUs: [
      { en: "Genuine brands, proper bill", hi: "असली ब्रांड, पक्का बिल" },
      { en: "Right advice for the job", hi: "काम के लिए सही सलाह" },
      { en: "Shade mixed while you wait", hi: "शेड आपके सामने मिक्स" },
      { en: "Delivery to your site", hi: "आपकी साइट तक डिलीवरी" },
      { en: "Bulk rates for contractors", hi: "ठेकेदारों के लिए थोक दर" },
      { en: "Everything for the job, one shop", hi: "काम का सारा सामान, एक दुकान" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Tell us the job", hi: "काम बताएँ", desc: "Painting, bathroom, wiring or a repair — we list what you need.", descHi: "पेंट, बाथरूम, वायरिंग या मरम्मत — ज़रूरत की लिस्ट हम बनाते हैं।" },
      { en: "Pick brands and quantity", hi: "ब्रांड और मात्रा चुनें", desc: "We show options in your budget and give an estimate.", descHi: "बजट में विकल्प दिखाते हैं और अंदाज़ा देते हैं।" },
      { en: "Delivered to site", hi: "साइट पर डिलीवरी", desc: "Collect from the shop or we deliver to the site.", descHi: "दुकान से लें या हम साइट पर पहुँचाते हैं।" },
    ],
    faq: [
      { q: "Can you mix a paint shade for me?", qHi: "पेंट का शेड मिक्स कर देंगे?", a: "Yes, pick a shade from the card or bring a sample; it is mixed on the machine here.", aHi: "हाँ, शेड कार्ड से चुनें या सैंपल लाएँ; यहीं मशीन पर मिक्स होता है।" },
      { q: "Do you deliver to construction sites?", qHi: "कंस्ट्रक्शन साइट पर डिलीवरी करते हैं?", a: "Yes, bulk and heavy material is delivered to the site; message us the list and address.", aHi: "हाँ, थोक और भारी सामान साइट पर पहुँचता है; लिस्ट और पता WhatsApp करें।" },
      { q: "Do you give contractor rates?", qHi: "ठेकेदार रेट मिलता है?", a: "Yes, regular contractors, plumbers and painters get bulk rates; talk to us once.", aHi: "हाँ, नियमित ठेकेदार, प्लंबर और पेंटर को थोक दर; एक बार बात कर लें।" },
      { q: "Can you suggest a plumber or painter?", qHi: "प्लंबर या पेंटर बता सकते हैं?", a: "We can connect you to workers who buy from us regularly; ask at the counter.", aHi: "जो कारीगर हमसे नियमित सामान लेते हैं, उनसे मिला सकते हैं; काउंटर पर पूछें।" },
      { q: "Can I return unused material?", qHi: "बचा हुआ सामान वापस हो सकता है?", a: "Sealed, unused items can be exchanged with the bill; mixed paint and cut pipes cannot.", aHi: "सील, बिना इस्तेमाल सामान बिल के साथ बदल सकते हैं; मिक्स पेंट और कटे पाइप नहीं।" },
      { q: "Do you keep a specific brand?", qHi: "कोई खास ब्रांड रखते हैं?", a: "We stock the common brands; message the product and brand and we check or arrange it.", aHi: "आम ब्रांड रखते हैं; प्रोडक्ट और ब्रांड भेजें, देखकर या मँगवाकर बताएँगे।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the shop; bank transfer for bigger site orders.", aHi: "दुकान पर नक़द, UPI और कार्ड; बड़े साइट ऑर्डर के लिए बैंक ट्रांसफ़र।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "all brands", "best quality", "customer satisfaction"],
  },

  medical: {
    explain: [
      "what the store stocks (medicines, generics, surgical items, baby care, nutrition, health devices) and the brands",
      "prescription medicines on a valid prescription; the pharmacist checks the dose and substitutes only on the doctor's advice",
      "home delivery of medicines and monthly refills for regular patients",
      "timings and how to order: send the prescription on WhatsApp",
    ],
    services: [
      { en: "Prescription medicines", hi: "डॉक्टर की पर्ची की दवाइयाँ", desc: "Medicines dispensed against a valid prescription, checked by the pharmacist.", descHi: "सही पर्ची पर दवाइयाँ, फ़ार्मासिस्ट की जाँच के साथ।" },
      { en: "Generic medicines", hi: "जेनेरिक दवाइयाँ", desc: "Generic options where available — ask your doctor or us.", descHi: "जहाँ उपलब्ध हो जेनेरिक विकल्प — डॉक्टर या हमसे पूछें।" },
      { en: "Home delivery", hi: "होम डिलीवरी", desc: "Send the prescription on WhatsApp; medicines delivered nearby.", descHi: "WhatsApp पर पर्ची भेजें; आस-पास घर तक दवाइयाँ।" },
      { en: "Monthly refills", hi: "महीने की दवाइयाँ", desc: "Regular medicines packed every month for BP, sugar and long-term patients.", descHi: "BP, शुगर और लंबे इलाज के मरीज़ों की दवाइयाँ हर महीने पैक।" },
      { en: "Surgical & first-aid", hi: "सर्जिकल और फ़र्स्ट-एड", desc: "Bandages, masks, gloves, syringes and basic first-aid supplies.", descHi: "पट्टी, मास्क, दस्ताने, सिरिंज और फ़र्स्ट-एड का सामान।" },
      { en: "Health devices", hi: "हेल्थ डिवाइस", desc: "BP monitors, glucometers, thermometers and nebulisers — with guidance to use them.", descHi: "BP मशीन, ग्लूकोमीटर, थर्मामीटर और नेबुलाइज़र — इस्तेमाल समझाकर।" },
      { en: "Baby, nutrition & wellness", hi: "बेबी, न्यूट्रिशन और वेलनेस", desc: "Baby food, diapers, supplements and personal care items.", descHi: "बेबी फ़ूड, डायपर, सप्लीमेंट और पर्सनल केयर का सामान।" },
    ],
    whyUs: [
      { en: "Genuine medicines, proper bill", hi: "असली दवाइयाँ, पक्का बिल" },
      { en: "Qualified pharmacist at counter", hi: "काउंटर पर योग्य फ़ार्मासिस्ट" },
      { en: "Expiry checked before billing", hi: "बिल से पहले एक्सपायरी जाँच" },
      { en: "Delivered home on WhatsApp", hi: "WhatsApp पर घर तक" },
      { en: "Generic options explained", hi: "जेनेरिक विकल्प समझाते हैं" },
      { en: "Monthly medicines remembered", hi: "महीने की दवाइयाँ याद रखते हैं" },
      { en: "Cold-chain items stored right", hi: "फ़्रिज वाली दवाइयाँ सही रखी" },
    ],
    steps: [
      { en: "Send the prescription", hi: "पर्ची भेजें", desc: "Bring it to the counter or send a clear photo on WhatsApp.", descHi: "काउंटर पर लाएँ या WhatsApp पर साफ़ फ़ोटो भेजें।" },
      { en: "We check and pack", hi: "जाँच और पैकिंग", desc: "The pharmacist reads the dose; we confirm what is in stock and the bill.", descHi: "फ़ार्मासिस्ट खुराक पढ़ता है; स्टॉक और बिल कन्फ़र्म करते हैं।" },
      { en: "Pick up or delivered", hi: "ले जाएँ या डिलीवरी", desc: "Collect from the store or get it delivered at home.", descHi: "स्टोर से लें या घर पर मँगवाएँ।" },
      { en: "Refill reminders", hi: "रिफ़िल की याद", desc: "For regular medicines, message us each month and we keep it ready.", descHi: "नियमित दवाइयों के लिए हर महीने मैसेज करें, हम तैयार रखते हैं।" },
    ],
    faq: [
      { q: "Do you deliver medicines at home?", qHi: "दवाइयाँ घर पर पहुँचाते हैं?", a: "Yes, nearby. Send the prescription and address on WhatsApp and we confirm.", aHi: "हाँ, आस-पास। WhatsApp पर पर्ची और पता भेजें, हम कन्फ़र्म करेंगे।" },
      { q: "Do I need a prescription?", qHi: "पर्ची ज़रूरी है?", a: "For scheduled medicines, yes — a doctor's prescription is required by law. Over-the-counter items do not need one.", aHi: "शेड्यूल दवाइयों के लिए हाँ — क़ानूनन डॉक्टर की पर्ची ज़रूरी है। ओवर-द-काउंटर चीज़ों के लिए नहीं।" },
      { q: "Can you give a generic instead of the brand?", qHi: "ब्रांड की जगह जेनेरिक दे सकते हैं?", a: "Where a generic exists we can tell you, but please confirm with your doctor before changing.", aHi: "जहाँ जेनेरिक है, बता सकते हैं, पर बदलने से पहले डॉक्टर से पूछ लें।" },
      { q: "What if a medicine is not in stock?", qHi: "दवाई स्टॉक में न हो तो?", a: "We arrange it from the distributor and message you as soon as it arrives.", aHi: "डिस्ट्रीब्यूटर से मँगवाते हैं और आने पर मैसेज कर देते हैं।" },
      { q: "Can I return medicines?", qHi: "दवाइयाँ वापस हो सकती हैं?", a: "Unopened strips with the bill can usually be exchanged; cold-chain and cut strips cannot.", aHi: "बिल के साथ बिना खुली स्ट्रिप आमतौर पर बदल सकते हैं; फ़्रिज वाली और कटी स्ट्रिप नहीं।" },
      { q: "Can you tell me which medicine to take?", qHi: "कौन सी दवाई लूँ, बता सकते हैं?", a: "We dispense what the doctor has prescribed; for any symptom please consult a doctor first.", aHi: "हम डॉक्टर की लिखी दवाई देते हैं; किसी भी तकलीफ़ के लिए पहले डॉक्टर से मिलें।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the store; UPI for WhatsApp orders and delivery.", aHi: "स्टोर पर नक़द, UPI और कार्ड; WhatsApp ऑर्डर और डिलीवरी के लिए UPI।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "all medicines available", "best care", "customer satisfaction"],
  },

  "grocery-online": {
    explain: [
      "what you sell online (the categories) and who it is for",
      "how to order: website, app or WhatsApp; delivery area and shipping",
      "payment options, cash on delivery, returns and exchange",
      "order tracking and support",
    ],
    services: [
      { en: "Order online", hi: "ऑनलाइन ऑर्डर", desc: "Browse the catalogue and order from your phone, any time.", descHi: "कैटलॉग देखें और फ़ोन से कभी भी ऑर्डर करें।" },
      { en: "WhatsApp ordering", hi: "WhatsApp पर ऑर्डर", desc: "Not sure how to order? Send a message and we place it for you.", descHi: "ऑर्डर करना न आए? मैसेज करें, हम लगा देते हैं।" },
      { en: "Doorstep delivery", hi: "घर तक डिलीवरी", desc: "Shipped by courier or our rider, tracked till it reaches you.", descHi: "कूरियर या हमारे राइडर से, पहुँचने तक ट्रैकिंग।" },
      { en: "Cash on delivery", hi: "कैश ऑन डिलीवरी", desc: "Pay when the parcel arrives, where the service is available.", descHi: "जहाँ सुविधा हो, पार्सल आने पर भुगतान।" },
      { en: "Easy returns & exchange", hi: "आसान रिटर्न और एक्सचेंज", desc: "Wrong or damaged item? Message us with a photo and we sort it.", descHi: "ग़लत या टूटा सामान? फ़ोटो के साथ मैसेज करें, हम ठीक करते हैं।" },
      { en: "Bulk & gift orders", hi: "थोक और गिफ़्ट ऑर्डर", desc: "Bulk quantities for offices and events; gift wrapping on request.", descHi: "ऑफ़िस और इवेंट के लिए थोक; माँगने पर गिफ़्ट पैकिंग।" },
      { en: "Order support", hi: "ऑर्डर सपोर्ट", desc: "Questions about an order, size or delivery — answered on WhatsApp.", descHi: "ऑर्डर, साइज़ या डिलीवरी का सवाल — WhatsApp पर जवाब।" },
    ],
    whyUs: [
      { en: "Genuine products, packed carefully", hi: "असली माल, संभालकर पैक" },
      { en: "Order on WhatsApp too", hi: "WhatsApp पर भी ऑर्डर" },
      { en: "Tracked delivery", hi: "ट्रैकिंग के साथ डिलीवरी" },
      { en: "Cash on delivery available", hi: "कैश ऑन डिलीवरी" },
      { en: "Returns handled, no run-around", hi: "रिटर्न आसान, कोई चक्कर नहीं" },
      { en: "A real person replies", hi: "जवाब असली इंसान देता है" },
      { en: "Clear price, shipping shown", hi: "साफ़ दाम, शिपिंग दिखता है" },
    ],
    steps: [
      { en: "Browse and pick", hi: "देखें और चुनें", desc: "See the products here or on our page; ask us if unsure.", descHi: "यहाँ या हमारे पेज पर प्रोडक्ट देखें; संशय हो तो पूछें।" },
      { en: "Place the order", hi: "ऑर्डर करें", desc: "Order online, or send items and address on WhatsApp.", descHi: "ऑनलाइन ऑर्डर करें, या WhatsApp पर चीज़ें और पता भेजें।" },
      { en: "Pay or choose COD", hi: "भुगतान या COD चुनें", desc: "UPI, card or cash on delivery where available.", descHi: "UPI, कार्ड या जहाँ हो वहाँ कैश ऑन डिलीवरी।" },
      { en: "Track and receive", hi: "ट्रैक करें और पाएँ", desc: "We send the tracking; the parcel reaches your door.", descHi: "हम ट्रैकिंग भेजते हैं; पार्सल आपके दरवाज़े।" },
    ],
    faq: [
      { q: "Where do you deliver?", qHi: "कहाँ-कहाँ डिलीवरी है?", a: "Across the areas our courier covers; send your pincode on WhatsApp and we confirm.", aHi: "जहाँ तक हमारा कूरियर जाता है; WhatsApp पर पिनकोड भेजें, कन्फ़र्म करेंगे।" },
      { q: "How long does delivery take?", qHi: "डिलीवरी में कितना समय लगता है?", a: "It depends on your location; we tell you the expected date when you order.", aHi: "आपकी जगह पर निर्भर; ऑर्डर पर अनुमानित तारीख़ बता देते हैं।" },
      { q: "Is cash on delivery available?", qHi: "कैश ऑन डिलीवरी है?", a: "Yes, for most areas and order sizes; we confirm when you place the order.", aHi: "हाँ, ज़्यादातर इलाक़ों और ऑर्डर के लिए; ऑर्डर करते समय कन्फ़र्म करते हैं।" },
      { q: "What if the item is damaged or wrong?", qHi: "सामान टूटा या ग़लत आए तो?", a: "Message us a photo soon after delivery; we replace it or refund.", aHi: "डिलीवरी के तुरंत बाद फ़ोटो भेजें; हम बदलते हैं या पैसे लौटाते हैं।" },
      { q: "Can I track my order?", qHi: "ऑर्डर ट्रैक कर सकते हैं?", a: "Yes, we send the tracking details on WhatsApp once it is shipped.", aHi: "हाँ, शिप होते ही WhatsApp पर ट्रैकिंग भेज देते हैं।" },
      { q: "Can I order on WhatsApp instead of the website?", qHi: "वेबसाइट की जगह WhatsApp पर ऑर्डर हो सकता है?", a: "Yes, send the product name, quantity and address and we place it for you.", aHi: "हाँ, प्रोडक्ट, मात्रा और पता भेजें, हम ऑर्डर लगा देते हैं।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, cards and net banking online; cash on delivery where available.", aHi: "ऑनलाइन UPI, कार्ड और नेट बैंकिंग; जहाँ हो वहाँ कैश ऑन डिलीवरी।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "shop now", "best deals", "customer satisfaction"],
  },

  gift: {
    explain: [
      "what you sell (gifts, toys, greeting cards, stationery, school and office supplies, party items)",
      "gift wrapping, hampers and personalised gifts (mugs, frames, printed names)",
      "bulk orders for schools, offices, return gifts and corporate gifting",
      "festival and season stock; how to order on WhatsApp",
    ],
    services: [
      { en: "Gifts for every occasion", hi: "हर मौक़े के गिफ़्ट", desc: "Birthdays, anniversaries, Rakhi, Diwali — gifts for all budgets.", descHi: "जन्मदिन, सालगिरह, राखी, दिवाली — हर बजट के गिफ़्ट।" },
      { en: "School & office stationery", hi: "स्कूल और ऑफ़िस स्टेशनरी", desc: "Notebooks, pens, art supplies, files and office essentials.", descHi: "कॉपी, पेन, आर्ट का सामान, फ़ाइल और ऑफ़िस की चीज़ें।" },
      { en: "Gift wrapping & hampers", hi: "गिफ़्ट पैकिंग और हैम्पर", desc: "Wrapped and ready to give; hampers put together as you like.", descHi: "पैक करके देने को तैयार; हैम्पर आपकी पसंद से।" },
      { en: "Personalised gifts", hi: "पर्सनलाइज़्ड गिफ़्ट", desc: "Mugs, frames, cushions and keychains with a name or photo.", descHi: "नाम या फ़ोटो के साथ मग, फ़्रेम, कुशन और कीचेन।" },
      { en: "Return gifts & bulk", hi: "रिटर्न गिफ़्ट और थोक", desc: "Return gifts for parties, bulk stationery for schools and offices.", descHi: "पार्टी के रिटर्न गिफ़्ट, स्कूल और ऑफ़िस के लिए थोक स्टेशनरी।" },
      { en: "Party supplies", hi: "पार्टी का सामान", desc: "Balloons, candles, decorations and cards for celebrations.", descHi: "गुब्बारे, मोमबत्ती, सजावट और कार्ड।" },
      { en: "Toys & games", hi: "खिलौने और गेम", desc: "Toys, puzzles and board games for kids of all ages.", descHi: "हर उम्र के बच्चों के लिए खिलौने, पज़ल और बोर्ड गेम।" },
    ],
    whyUs: [
      { en: "Something for every budget", hi: "हर बजट में कुछ न कुछ" },
      { en: "Wrapping done for you", hi: "पैकिंग हम करते हैं" },
      { en: "Personalised gifts made here", hi: "पर्सनलाइज़्ड गिफ़्ट यहीं बनते हैं" },
      { en: "Fresh stock every season", hi: "हर सीज़न नया स्टॉक" },
      { en: "Bulk and return gift orders", hi: "थोक और रिटर्न गिफ़्ट ऑर्डर" },
      { en: "Help choosing the right gift", hi: "सही गिफ़्ट चुनने में मदद" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Tell us the occasion", hi: "मौक़ा बताएँ", desc: "Who it is for, the occasion and your budget.", descHi: "किसके लिए, कौन सा मौक़ा और बजट।" },
      { en: "Pick or personalise", hi: "चुनें या पर्सनलाइज़ करें", desc: "Choose from the shop or send a photo for a custom gift.", descHi: "दुकान से चुनें या कस्टम गिफ़्ट के लिए फ़ोटो भेजें।" },
      { en: "Wrapped and ready", hi: "पैक होकर तैयार", desc: "Gift-wrapped with a card; collect or get it delivered.", descHi: "कार्ड के साथ गिफ़्ट पैक; ले जाएँ या मँगवाएँ।" },
    ],
    faq: [
      { q: "Do you do gift wrapping?", qHi: "गिफ़्ट पैकिंग करते हैं?", a: "Yes, every gift can be wrapped with a card; hampers are packed to your choice.", aHi: "हाँ, हर गिफ़्ट कार्ड के साथ पैक होता है; हैम्पर आपकी पसंद से।" },
      { q: "Can I get a photo or name printed on a gift?", qHi: "गिफ़्ट पर फ़ोटो या नाम छप सकता है?", a: "Yes, send the photo or text on WhatsApp; we tell you when it will be ready.", aHi: "हाँ, WhatsApp पर फ़ोटो या टेक्स्ट भेजें; तैयार होने का समय बता देंगे।" },
      { q: "Do you take return gift orders?", qHi: "रिटर्न गिफ़्ट के ऑर्डर लेते हैं?", a: "Yes, for birthdays and functions; tell us the number of guests, budget and date.", aHi: "हाँ, जन्मदिन और फ़ंक्शन के लिए; मेहमानों की संख्या, बजट और तारीख़ बताएँ।" },
      { q: "Do you supply stationery to schools or offices?", qHi: "स्कूल या ऑफ़िस को स्टेशनरी देते हैं?", a: "Yes, bulk orders with a bill; send the list on WhatsApp for a quote.", aHi: "हाँ, बिल के साथ थोक ऑर्डर; WhatsApp पर लिस्ट भेजें, कोटेशन देंगे।" },
      { q: "Can you deliver a gift to someone's address?", qHi: "किसी के पते पर गिफ़्ट पहुँचा सकते हैं?", a: "Yes, within the city; share the address and the date it should reach.", aHi: "हाँ, शहर में; पता और पहुँचने की तारीख़ भेजें।" },
      { q: "Can I exchange a gift?", qHi: "गिफ़्ट बदल सकते हैं?", a: "Unused items with the bill can be exchanged; personalised items cannot be.", aHi: "बिना इस्तेमाल सामान बिल के साथ बदल सकते हैं; पर्सनलाइज़्ड चीज़ें नहीं।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the shop; UPI advance for custom and bulk orders.", aHi: "दुकान पर नक़द, UPI और कार्ड; कस्टम और थोक ऑर्डर के लिए UPI एडवांस।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "unique gifts", "best collection", "customer satisfaction"],
  },

  optical: {
    explain: [
      "what you offer (frames, sunglasses, lenses, contact lenses, kids' frames) and the brands",
      "eye testing by the optometrist and prescription lenses made to your power",
      "repair, adjustment and lens replacement for old frames",
      "how to start: walk in for a test, or send your prescription on WhatsApp",
    ],
    services: [
      { en: "Eye test", hi: "आँखों की जाँच", desc: "Power checked by our optometrist; bring an old prescription if you have one.", descHi: "ऑप्टोमेट्रिस्ट से नंबर की जाँच; पुरानी पर्ची हो तो लाएँ।" },
      { en: "Frames & sunglasses", hi: "फ़्रेम और धूप के चश्मे", desc: "Frames for men, women and kids; branded and budget sunglasses.", descHi: "पुरुष, महिला और बच्चों के फ़्रेम; ब्रांडेड और किफ़ायती धूप के चश्मे।" },
      { en: "Prescription lenses", hi: "नंबर के लेंस", desc: "Single vision, bifocal, progressive, blue-cut and anti-glare lenses to your power.", descHi: "आपके नंबर के सिंगल, बाइफ़ोकल, प्रोग्रेसिव, ब्लू-कट और एंटी-ग्लेयर लेंस।" },
      { en: "Contact lenses", hi: "कॉन्टैक्ट लेंस", desc: "Daily and monthly contact lenses, with guidance on wearing and care.", descHi: "डेली और मंथली कॉन्टैक्ट लेंस, पहनने और देखभाल की समझ के साथ।" },
      { en: "Repair & adjustment", hi: "रिपेयर और एडजस्टमेंट", desc: "Loose screws, nose pads, bent frames and lens replacement.", descHi: "ढीला स्क्रू, नोज़ पैड, मुड़ा फ़्रेम और लेंस बदलना।" },
      { en: "Kids' eyewear", hi: "बच्चों के चश्मे", desc: "Light, sturdy frames for children, fitted properly.", descHi: "बच्चों के लिए हल्के, मज़बूत फ़्रेम, सही फ़िटिंग के साथ।" },
      { en: "Computer & reading glasses", hi: "कंप्यूटर और पढ़ने के चश्मे", desc: "Glasses for screen work and reading, with the right coating.", descHi: "स्क्रीन और पढ़ाई के लिए चश्मे, सही कोटिंग के साथ।" },
    ],
    whyUs: [
      { en: "Eye test by an optometrist", hi: "ऑप्टोमेट्रिस्ट से जाँच" },
      { en: "Lenses made to your power", hi: "आपके नंबर के लेंस" },
      { en: "Frames fitted properly", hi: "फ़्रेम की सही फ़िटिंग" },
      { en: "Adjustment and cleaning after purchase", hi: "खरीद के बाद एडजस्टमेंट और सफ़ाई" },
      { en: "Genuine lenses, proper bill", hi: "असली लेंस, पक्का बिल" },
      { en: "Styles for every budget", hi: "हर बजट के स्टाइल" },
      { en: "Send your prescription on WhatsApp", hi: "WhatsApp पर पर्ची भेजें" },
    ],
    steps: [
      { en: "Get your eyes tested", hi: "आँखें जँचवाएँ", desc: "Walk in for a test, or send your doctor's prescription on WhatsApp.", descHi: "जाँच के लिए आएँ, या डॉक्टर की पर्ची WhatsApp पर भेजें।" },
      { en: "Choose frame and lens", hi: "फ़्रेम और लेंस चुनें", desc: "Try frames on; we suggest the lens type for your power and use.", descHi: "फ़्रेम पहनकर देखें; नंबर और इस्तेमाल के हिसाब से लेंस सुझाते हैं।" },
      { en: "Lenses fitted", hi: "लेंस फ़िट", desc: "Lenses are made to your power and fitted; we message when ready.", descHi: "आपके नंबर के लेंस बनकर फ़िट; तैयार होने पर मैसेज।" },
      { en: "Collect and adjust", hi: "लें और एडजस्ट करवाएँ", desc: "Frame adjusted to your face; come back any time for a tweak.", descHi: "फ़्रेम चेहरे के हिसाब से सेट; कभी भी एडजस्ट करवाने आएँ।" },
    ],
    faq: [
      { q: "Do you test eyes here?", qHi: "यहाँ आँखों की जाँच होती है?", a: "Yes, our optometrist checks your power; for any eye problem please consult an eye doctor.", aHi: "हाँ, ऑप्टोमेट्रिस्ट नंबर जाँचता है; आँख की किसी तकलीफ़ के लिए आँखों के डॉक्टर से मिलें।" },
      { q: "Can I bring my doctor's prescription?", qHi: "डॉक्टर की पर्ची ला सकते हैं?", a: "Yes, bring it or send a photo on WhatsApp; lenses are made exactly to it.", aHi: "हाँ, लाएँ या WhatsApp पर फ़ोटो भेजें; लेंस उसी के हिसाब से बनते हैं।" },
      { q: "How long do the glasses take?", qHi: "चश्मा कितने समय में बनता है?", a: "Depends on the lens type; common powers are quicker, special lenses take longer. We tell you at order.", aHi: "लेंस के प्रकार पर निर्भर; आम नंबर जल्दी, खास लेंस में ज़्यादा समय। ऑर्डर पर बता देते हैं।" },
      { q: "Can I put new lenses in my old frame?", qHi: "पुराने फ़्रेम में नए लेंस लग सकते हैं?", a: "Yes, if the frame is in good condition; bring it and we check it for you.", aHi: "हाँ, फ़्रेम ठीक हो तो; लाएँ, हम देख लेते हैं।" },
      { q: "Do you sell contact lenses?", qHi: "कॉन्टैक्ट लेंस मिलते हैं?", a: "Yes, daily and monthly; we guide first-time users on wearing and cleaning.", aHi: "हाँ, डेली और मंथली; पहली बार वालों को पहनना और साफ़ करना समझाते हैं।" },
      { q: "Do you repair frames?", qHi: "फ़्रेम रिपेयर करते हैं?", a: "Yes, screws, nose pads and bends are fixed; some repairs are done while you wait.", aHi: "हाँ, स्क्रू, नोज़ पैड और मुड़ाव ठीक करते हैं; कुछ काम आपके सामने ही।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards; an advance at order and the balance when you collect.", aHi: "नक़द, UPI और कार्ड; ऑर्डर पर एडवांस, बाक़ी लेते समय।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "clear vision", "best frames", "customer satisfaction"],
  },

  footwear: {
    explain: [
      "what you sell (men's, women's, kids', school shoes, sports, formal, ethnic, slippers) and the brands",
      "sizes and fitting help; wide fits and larger sizes",
      "exchange policy, school and bulk orders",
      "new stock each season; how to shop or ask on WhatsApp",
    ],
    services: [
      { en: "Men's, women's & kids' footwear", hi: "पुरुष, महिला और बच्चों के जूते", desc: "Casual, formal, sports and ethnic footwear for the whole family.", descHi: "पूरे परिवार के लिए कैज़ुअल, फ़ॉर्मल, स्पोर्ट्स और एथनिक जूते-चप्पल।" },
      { en: "School shoes", hi: "स्कूल के जूते", desc: "Black and white school shoes in all sizes, stocked before the session.", descHi: "हर साइज़ में काले और सफ़ेद स्कूल शूज़, सेशन से पहले स्टॉक।" },
      { en: "Sports & running shoes", hi: "स्पोर्ट्स और रनिंग शूज़", desc: "Shoes for walking, running, gym and sports from known brands.", descHi: "वॉक, रनिंग, जिम और खेल के लिए जाने-माने ब्रांड के जूते।" },
      { en: "Size & fitting help", hi: "साइज़ और फ़िटिंग में मदद", desc: "Try both pairs on; we help with wide fits and larger sizes.", descHi: "दोनों पैर पहनकर देखें; चौड़े और बड़े साइज़ में मदद।" },
      { en: "Easy exchange", hi: "आसान एक्सचेंज", desc: "Wrong size? Exchange unworn pairs with the box and bill.", descHi: "साइज़ ग़लत? बिना पहने जोड़े डिब्बे और बिल के साथ बदलें।" },
      { en: "Bulk & uniform orders", hi: "थोक और यूनिफ़ॉर्म ऑर्डर", desc: "School, factory and staff shoes in bulk with a bill.", descHi: "स्कूल, फ़ैक्टरी और स्टाफ़ के जूते बिल के साथ थोक में।" },
      { en: "Shoe care & accessories", hi: "शू केयर और एक्सेसरीज़", desc: "Socks, insoles, laces, polish and shoe care.", descHi: "मोज़े, इनसोल, फ़ीते, पॉलिश और शू केयर।" },
    ],
    whyUs: [
      { en: "Genuine brands, proper bill", hi: "असली ब्रांड, पक्का बिल" },
      { en: "All sizes, tried on", hi: "हर साइज़, पहनकर देखें" },
      { en: "Comfort first, honest advice", hi: "आराम पहले, सच्ची सलाह" },
      { en: "Easy exchange with bill", hi: "बिल पर आसान एक्सचेंज" },
      { en: "New stock every season", hi: "हर सीज़न नया स्टॉक" },
      { en: "School shoes always in stock", hi: "स्कूल शूज़ हमेशा स्टॉक में" },
      { en: "Ask on WhatsApp", hi: "WhatsApp पर पूछें" },
    ],
    steps: [
      { en: "Tell us what you need", hi: "बताएँ क्या चाहिए", desc: "Daily wear, office, sports or school; visit or ask on WhatsApp.", descHi: "रोज़ के, ऑफ़िस, खेल या स्कूल; आएँ या WhatsApp पर पूछें।" },
      { en: "Try the size", hi: "साइज़ पहनकर देखें", desc: "Walk a few steps in both; we check the fit.", descHi: "दोनों पहनकर कुछ क़दम चलें; फ़िटिंग हम देखते हैं।" },
      { en: "Buy with bill", hi: "बिल के साथ खरीदें", desc: "Keep the box and bill for easy exchange.", descHi: "आसान एक्सचेंज के लिए डिब्बा और बिल रखें।" },
    ],
    faq: [
      { q: "Can I exchange if the size doesn't fit?", qHi: "साइज़ न आए तो बदल सकते हैं?", a: "Yes, unworn pairs with the box and bill can be exchanged within the period told at billing.", aHi: "हाँ, बिना पहने जोड़े डिब्बे और बिल के साथ, बिलिंग पर बताई अवधि में।" },
      { q: "Do you keep large or wide sizes?", qHi: "बड़े या चौड़े साइज़ रखते हैं?", a: "We keep a good range; message us the size and type and we check or arrange it.", aHi: "अच्छी रेंज रखते हैं; साइज़ और प्रकार भेजें, देखकर या मँगवाकर बताएँगे।" },
      { q: "Are the branded shoes genuine?", qHi: "ब्रांडेड जूते असली हैं?", a: "Yes, bought from authorised distributors and sold with a proper bill.", aHi: "हाँ, अधिकृत डिस्ट्रीब्यूटर से लिए और पक्के बिल के साथ बेचे जाते हैं।" },
      { q: "Do you have school shoes?", qHi: "स्कूल के जूते मिलते हैं?", a: "Yes, black and white school shoes in all sizes, especially before the new session.", aHi: "हाँ, हर साइज़ में काले और सफ़ेद स्कूल शूज़, खासकर नए सेशन से पहले।" },
      { q: "Do you take bulk orders?", qHi: "थोक ऑर्डर लेते हैं?", a: "Yes, for schools, factories and staff; send the sizes and quantity on WhatsApp.", aHi: "हाँ, स्कूल, फ़ैक्टरी और स्टाफ़ के लिए; WhatsApp पर साइज़ और मात्रा भेजें।" },
      { q: "Can I see new arrivals on WhatsApp?", qHi: "नया माल WhatsApp पर देख सकते हैं?", a: "Yes, tell us the type and size you want and we send photos.", aHi: "हाँ, प्रकार और साइज़ बताएँ, हम फ़ोटो भेज देंगे।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the shop; UPI for pairs reserved on WhatsApp.", aHi: "दुकान पर नक़द, UPI और कार्ड; WhatsApp पर रखवाए जोड़े के लिए UPI।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best collection", "comfortable shoes", "customer satisfaction"],
  },
};

/** General retail entry — used for any key of the Retail group that has no entry above. */
export const RETAIL_DEFAULT: TradeData = {
  explain: [
    "what the shop sells and the kinds of customers it serves",
    "the brands or range, and what makes the stock reliable",
    "services beyond selling: delivery, bulk orders, exchange, help choosing",
    "how to shop: walk in or ask on WhatsApp; timings",
  ],
  services: [
    { en: "Wide range in stock", hi: "पूरी रेंज स्टॉक में", desc: "The everyday items and brands customers ask for, under one roof.", descHi: "रोज़ की चीज़ें और ब्रांड जो ग्राहक माँगते हैं, एक ही जगह।" },
    { en: "Ask on WhatsApp", hi: "WhatsApp पर पूछें", desc: "Message us for availability, photos or a price before you come.", descHi: "आने से पहले उपलब्धता, फ़ोटो या दाम WhatsApp पर पूछ लें।" },
    { en: "Home delivery", hi: "होम डिलीवरी", desc: "Order on WhatsApp and get it delivered nearby.", descHi: "WhatsApp पर ऑर्डर करें, आस-पास घर तक डिलीवरी।" },
    { en: "Bulk orders", hi: "थोक ऑर्डर", desc: "Larger quantities for offices, events and other shops.", descHi: "ऑफ़िस, आयोजन और दूसरी दुकानों के लिए बड़ी मात्रा।" },
    { en: "Easy exchange", hi: "आसान एक्सचेंज", desc: "Unused items exchanged with the bill.", descHi: "बिना इस्तेमाल सामान बिल के साथ बदल लें।" },
    { en: "Help choosing", hi: "चुनने में मदद", desc: "Tell us your need and budget; we suggest what fits.", descHi: "ज़रूरत और बजट बताएँ; हम सही चीज़ सुझाते हैं।" },
    { en: "Gift packing", hi: "गिफ़्ट पैकिंग", desc: "Packed for gifting on request.", descHi: "माँगने पर गिफ़्ट के लिए पैक।" },
  ],
  whyUs: [
    { en: "Genuine products, proper bill", hi: "असली माल, पक्का बिल" },
    { en: "Fair, fixed prices", hi: "वाजिब, तय दाम" },
    { en: "Honest advice on what to buy", hi: "क्या लें, सच्ची सलाह" },
    { en: "Easy exchange with bill", hi: "बिल पर आसान एक्सचेंज" },
    { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    { en: "Your neighbourhood shop", hi: "आपके मोहल्ले की दुकान" },
  ],
  steps: [
    { en: "Ask or visit", hi: "पूछें या आएँ", desc: "Message us what you need, or walk into the shop.", descHi: "क्या चाहिए मैसेज करें, या दुकान आ जाएँ।" },
    { en: "Pick what suits you", hi: "जो जँचे चुनें", desc: "See the options in your budget; we help you decide.", descHi: "बजट में विकल्प देखें; तय करने में हम मदद करते हैं।" },
    { en: "Pay and take it home", hi: "भुगतान करें, घर ले जाएँ", desc: "Cash, UPI or card; collect or get it delivered.", descHi: "नक़द, UPI या कार्ड; ले जाएँ या मँगवाएँ।" },
  ],
  faq: [
    { q: "Do you deliver at home?", qHi: "क्या होम डिलीवरी है?", a: "Yes, nearby. Message us the items and your location on WhatsApp and we confirm.", aHi: "हाँ, आस-पास। WhatsApp पर चीज़ें और लोकेशन भेजें, हम कन्फ़र्म करेंगे।" },
    { q: "Is an item in stock?", qHi: "कोई चीज़ स्टॉक में है?", a: "Message us the item or a photo on WhatsApp; we check and reply.", aHi: "WhatsApp पर चीज़ का नाम या फ़ोटो भेजें; देखकर जवाब देते हैं।" },
    { q: "Can I exchange something I bought?", qHi: "खरीदी चीज़ बदल सकते हैं?", a: "Unused items with the bill can be exchanged within the period told at billing.", aHi: "बिना इस्तेमाल सामान बिल के साथ, बिलिंग पर बताई अवधि में बदल सकते हैं।" },
    { q: "Do you take bulk orders?", qHi: "थोक ऑर्डर लेते हैं?", a: "Yes, for offices, events and shops; send the list and quantity for a quote.", aHi: "हाँ, ऑफ़िस, आयोजन और दुकानों के लिए; लिस्ट और मात्रा भेजें, कोटेशन देंगे।" },
    { q: "What are your timings?", qHi: "आपका समय क्या है?", a: "See the timings on this page, or message us to check before coming.", aHi: "इसी पेज पर समय देखें, या आने से पहले मैसेज करके पूछ लें।" },
    { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Cash, UPI and cards at the shop; UPI for WhatsApp orders.", aHi: "दुकान पर नक़द, UPI और कार्ड; WhatsApp ऑर्डर के लिए UPI।" },
  ],
  generic: ["connect with us", "explore options", "quality products", "best quality", "customer satisfaction"],
};
