// Network & sales trades: network marketing / direct selling, distributor / dealer / agency, sales executive, agent.
// See types.ts for the rules (no numbers, no prices, no income claims; true of any decent business of the trade).
import type { TradeData } from "./types";

export const SALES: Record<string, TradeData> = {
  mlm: {
    explain: [
      "which company's products you represent and the range (wellness, home care, personal care, nutrition)",
      "how a customer buys — direct from you, a demo at home, delivery or in person",
      "that joining is optional and explained honestly: the plan, the work, the training — with no promises made",
      "how to reach you: WhatsApp for orders, product questions and a meeting",
    ],
    services: [
      { en: "Product orders", hi: "प्रोडक्ट ऑर्डर", desc: "Order on WhatsApp, delivered at home or handed over in person.", descHi: "WhatsApp पर ऑर्डर करें, घर पर डिलीवरी या हाथों-हाथ।" },
      { en: "Demo & samples", hi: "डेमो और सैंपल", desc: "See and try the products before you buy, at home or at a meeting.", descHi: "ख़रीदने से पहले घर पर या मीटिंग में प्रोडक्ट देखें और आज़माएँ।" },
      { en: "Usage guidance", hi: "इस्तेमाल की जानकारी", desc: "How to use each product properly and which one suits your need.", descHi: "हर प्रोडक्ट कैसे इस्तेमाल करें और आपके लिए कौन सा सही है।" },
      { en: "Repeat orders & refills", hi: "रिपीट ऑर्डर और रीफ़िल", desc: "A reminder when your monthly products are due; reorder in one message.", descHi: "महीने का सामान ख़त्म होने से पहले याद दिलाते हैं; एक मैसेज में दोबारा ऑर्डर।" },
      { en: "Gift packs", hi: "गिफ़्ट पैक", desc: "Product gift packs for festivals and occasions, packed on request.", descHi: "त्योहार और मौक़ों के लिए प्रोडक्ट गिफ़्ट पैक, ऑर्डर पर पैकिंग।" },
      { en: "Business information", hi: "बिज़नेस की जानकारी", desc: "Honest information about joining, the plan and what the work involves.", descHi: "जुड़ने, plan और काम में क्या-क्या करना होता है — सब साफ़-साफ़।" },
      { en: "Team training & support", hi: "टीम के लिए ट्रेनिंग और सहयोग", desc: "Product training, meetings and help for people who join with you.", descHi: "साथ जुड़ने वालों के लिए प्रोडक्ट ट्रेनिंग, मीटिंग और मदद।" },
    ],
    whyUs: [
      { en: "Genuine company products", hi: "कंपनी के असली प्रोडक्ट" },
      { en: "Try before you buy", hi: "पहले आज़माएँ, फिर ख़रीदें" },
      { en: "Honest information, no pressure", hi: "सही जानकारी, कोई दबाव नहीं" },
      { en: "Delivered to your door", hi: "घर तक डिलीवरी" },
      { en: "Help after the sale", hi: "ख़रीद के बाद भी मदद" },
      { en: "Support for the whole team", hi: "पूरी टीम को सहयोग" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Message us", hi: "मैसेज करें", desc: "Tell us what you need — a product, a demo or business information.", descHi: "बताएँ क्या चाहिए — प्रोडक्ट, डेमो या बिज़नेस की जानकारी।" },
      { en: "See the products", hi: "प्रोडक्ट देखें", desc: "A demo at home or a meeting; try samples where available.", descHi: "घर पर डेमो या मीटिंग; जहाँ हो सके सैंपल आज़माएँ।" },
      { en: "Order and receive", hi: "ऑर्डर करें, पाएँ", desc: "Confirm your order on WhatsApp; delivered or handed over.", descHi: "WhatsApp पर ऑर्डर कन्फ़र्म करें; डिलीवरी या हाथों-हाथ।" },
      { en: "Stay in touch", hi: "जुड़े रहें", desc: "Reorder reminders, usage help and, if you wish, business guidance.", descHi: "रीऑर्डर की याद, इस्तेमाल में मदद और चाहें तो बिज़नेस की जानकारी।" },
    ],
    faq: [
      { q: "Are the products genuine?", qHi: "प्रोडक्ट असली हैं?", a: "Yes, they come straight from the company with its packing and bill; you can check the batch details yourself.", aHi: "हाँ, सीधे कंपनी से, उसकी पैकिंग और बिल के साथ; बैच की जानकारी आप ख़ुद देख सकते हैं।" },
      { q: "Can I buy without joining?", qHi: "बिना जुड़े ख़रीद सकते हैं?", a: "Yes. Anyone can order the products; joining the business is completely optional.", aHi: "हाँ। कोई भी प्रोडक्ट ऑर्डर कर सकता है; बिज़नेस में जुड़ना पूरी तरह आपकी मर्ज़ी है।" },
      { q: "Can I try a product first?", qHi: "पहले आज़मा सकते हैं?", a: "Where samples are available, yes; message us and we will arrange a demo or a sample.", aHi: "जहाँ सैंपल हो, हाँ; मैसेज करें, डेमो या सैंपल का इंतज़ाम करेंगे।" },
      { q: "How much can I earn if I join?", qHi: "जुड़ने पर कितनी कमाई होगी?", a: "That depends entirely on your own work and the company's plan; we explain the plan honestly in a meeting, with no promises.", aHi: "यह पूरी तरह आपकी मेहनत और कंपनी के plan पर निर्भर है; मीटिंग में plan साफ़-साफ़ समझाते हैं, कोई वादा नहीं।" },
      { q: "What if a product does not suit me?", qHi: "प्रोडक्ट सूट न करे तो?", a: "Message us; we guide you on usage, and return or exchange follows the company's policy.", aHi: "मैसेज करें; इस्तेमाल में मदद करते हैं, और रिटर्न या बदली कंपनी की policy के अनुसार।" },
      { q: "Do you deliver at home?", qHi: "होम डिलीवरी है?", a: "Yes, in our area; for other cities the company can ship directly. Ask us.", aHi: "हाँ, हमारे इलाक़े में; दूसरे शहर के लिए कंपनी सीधे भेज सकती है। पूछ लें।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI or cash on delivery; a company bill comes with every order.", aHi: "UPI या डिलीवरी पर नक़द; हर ऑर्डर के साथ कंपनी का बिल।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best opportunity", "join now", "earn more"],
  },

  distributor: {
    explain: [
      "which brands and products you distribute, and the area or territory you cover",
      "who you supply — retailers, shops, institutions, contractors — and whether customers can buy directly",
      "stock, regular supply, delivery to the shop and after-sales / warranty support",
      "how a new retailer starts: WhatsApp, price list, opening stock",
    ],
    services: [
      { en: "Wholesale supply to retailers", hi: "रिटेलर को थोक सप्लाई", desc: "Regular stock for shops and retailers in our area, delivered on schedule.", descHi: "इलाक़े की दुकानों और रिटेलर को नियमित माल, तय समय पर डिलीवरी।" },
      { en: "Authorised brand products", hi: "ब्रांड के अधिकृत प्रोडक्ट", desc: "Genuine company stock with bill and warranty, straight from the brand.", descHi: "कंपनी का असली माल, बिल और वारंटी के साथ, सीधे ब्रांड से।" },
      { en: "Delivery to your shop", hi: "दुकान तक डिलीवरी", desc: "Our vehicle delivers to your shop or site; no need to come.", descHi: "हमारी गाड़ी दुकान या साइट पर माल पहुँचाती है; आने की ज़रूरत नहीं।" },
      { en: "Bulk & institutional orders", hi: "थोक और संस्थागत ऑर्डर", desc: "Large orders for offices, hotels, hospitals, schools and contractors.", descHi: "ऑफ़िस, होटल, हॉस्पिटल, स्कूल और ठेकेदारों के लिए बड़े ऑर्डर।" },
      { en: "After-sales & warranty help", hi: "बिक्री के बाद और वारंटी सहायता", desc: "Warranty claims, replacements and service requests handled with the company.", descHi: "वारंटी क्लेम, बदली और सर्विस की बात कंपनी से हम करवाते हैं।" },
      { en: "New retailer onboarding", hi: "नए रिटेलर की शुरुआत", desc: "Price list, schemes and opening stock to start keeping our brands.", descHi: "price list, scheme और शुरुआती स्टॉक — हमारे ब्रांड रखना शुरू करें।" },
      { en: "Demo & product training", hi: "डेमो और प्रोडक्ट ट्रेनिंग", desc: "Product demos and training for your shop staff and customers.", descHi: "आपकी दुकान के स्टाफ़ और ग्राहकों के लिए डेमो और ट्रेनिंग।" },
    ],
    whyUs: [
      { en: "Authorised, genuine stock", hi: "अधिकृत, असली माल" },
      { en: "Regular supply, no stock-outs", hi: "नियमित सप्लाई, माल की कमी नहीं" },
      { en: "Delivery to your shop", hi: "दुकान तक डिलीवरी" },
      { en: "Bill and warranty on everything", hi: "हर चीज़ पर बिल और वारंटी" },
      { en: "Schemes passed on honestly", hi: "कंपनी की scheme ईमानदारी से" },
      { en: "Warranty claims handled for you", hi: "वारंटी क्लेम हम संभालते हैं" },
      { en: "Order on WhatsApp", hi: "WhatsApp पर ऑर्डर" },
    ],
    steps: [
      { en: "Send your requirement", hi: "ज़रूरत भेजें", desc: "Items, quantity and your shop or site location, on WhatsApp.", descHi: "चीज़ें, मात्रा और दुकान या साइट की लोकेशन, WhatsApp पर।" },
      { en: "Get the price list", hi: "price list लें", desc: "We share the current rates, schemes and stock available.", descHi: "मौजूदा रेट, scheme और उपलब्ध स्टॉक बताते हैं।" },
      { en: "Confirm the order", hi: "ऑर्डर कन्फ़र्म करें", desc: "Confirm on WhatsApp; the bill is made in your firm's name.", descHi: "WhatsApp पर कन्फ़र्म करें; बिल आपकी फ़र्म के नाम से बनता है।" },
      { en: "Delivered to you", hi: "आप तक डिलीवरी", desc: "Stock reaches your shop or site on the scheduled day.", descHi: "तय दिन माल आपकी दुकान या साइट पर पहुँचता है।" },
    ],
    faq: [
      { q: "Which brands do you deal in?", qHi: "कौन से ब्रांड रखते हैं?", a: "See the brands on this page; for a specific item or model, message us and we will check stock.", aHi: "इसी पेज पर ब्रांड देखें; किसी खास चीज़ या model के लिए मैसेज करें, स्टॉक देख लेंगे।" },
      { q: "Do you sell to individual customers too?", qHi: "आम ग्राहक को भी बेचते हैं?", a: "We mainly supply retailers, but ask us — for some products we sell directly or point you to a nearby shop.", aHi: "मुख्य रूप से रिटेलर को, पर पूछ लें — कुछ प्रोडक्ट सीधे भी देते हैं या पास की दुकान बता देते हैं।" },
      { q: "Is there a minimum order?", qHi: "कम से कम कितना ऑर्डर?", a: "It depends on the product; message us your requirement and we will tell you.", aHi: "प्रोडक्ट पर निर्भर है; अपनी ज़रूरत भेजें, हम बता देंगे।" },
      { q: "Do you give credit to retailers?", qHi: "रिटेलर को उधार मिलता है?", a: "Terms are decided after we have worked together for a while; new accounts start on payment. Talk to us.", aHi: "कुछ समय साथ काम करने के बाद शर्तें तय होती हैं; नए खाते भुगतान पर शुरू होते हैं। बात कर लें।" },
      { q: "Who handles warranty and replacements?", qHi: "वारंटी और बदली कौन देखता है?", a: "We do — send us the bill and the issue, and we take it up with the company.", aHi: "हम — बिल और समस्या भेजें, कंपनी से बात हम करते हैं।" },
      { q: "Which areas do you cover?", qHi: "किन इलाक़ों में सप्लाई है?", a: "Our territory is listed on this page; message your location to confirm.", aHi: "इसी पेज पर हमारा इलाक़ा दिया है; लोकेशन भेजकर कन्फ़र्म कर लें।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Bank transfer, UPI or cheque against the bill; GST invoice for every order.", aHi: "बिल के बदले बैंक ट्रांसफ़र, UPI या चेक; हर ऑर्डर पर GST इनवॉइस।" },
    ],
    generic: ["connect with us", "explore options", "quality products", "best price", "wide range"],
  },

  sales: {
    explain: [
      "the company and the products or services you sell, and who your customers are (dealers, businesses, households)",
      "what a customer gets from you: product information, quotation, demo, order follow-up and after-sales coordination",
      "that you are the company's one point of contact in your area",
      "your territory and how to reach you",
    ],
    services: [
      { en: "Product information & quotation", hi: "प्रोडक्ट जानकारी और कोटेशन", desc: "The right product for your need, with a written quotation.", descHi: "आपकी ज़रूरत के हिसाब से सही प्रोडक्ट, लिखित कोटेशन के साथ।" },
      { en: "Demo & presentation", hi: "डेमो और प्रेज़ेंटेशन", desc: "A demo at your office, shop or home, at your convenience.", descHi: "आपके ऑफ़िस, दुकान या घर पर, आपकी सुविधा के समय डेमो।" },
      { en: "Order booking & follow-up", hi: "ऑर्डर बुकिंग और फ़ॉलो-अप", desc: "Place the order through me and I track it till delivery.", descHi: "ऑर्डर मेरे ज़रिए दें, डिलीवरी तक पूरा फ़ॉलो-अप।" },
      { en: "Dealer & distributor appointment", hi: "डीलर / डिस्ट्रीब्यूटर नियुक्ति", desc: "Help shops and firms start keeping the company's products in their area.", descHi: "दुकानों और फ़र्मों को अपने इलाक़े में कंपनी के प्रोडक्ट रखने में मदद।" },
      { en: "Corporate & bulk deals", hi: "कॉर्पोरेट और थोक डील", desc: "Special pricing and terms for offices, institutions and large orders.", descHi: "ऑफ़िस, संस्थानों और बड़े ऑर्डर के लिए खास रेट और शर्तें।" },
      { en: "After-sales coordination", hi: "बिक्री के बाद समन्वय", desc: "Service, warranty and complaints taken up with the company for you.", descHi: "सर्विस, वारंटी और शिकायत की बात कंपनी से आपके लिए।" },
      { en: "Schemes & offers update", hi: "scheme और ऑफ़र की जानकारी", desc: "Current schemes and new launches shared with you on WhatsApp.", descHi: "मौजूदा scheme और नए launch की जानकारी WhatsApp पर।" },
    ],
    whyUs: [
      { en: "One contact for everything", hi: "हर काम के लिए एक संपर्क" },
      { en: "Replies on WhatsApp, quickly", hi: "WhatsApp पर जल्दी जवाब" },
      { en: "Honest advice, right product", hi: "सही सलाह, सही प्रोडक्ट" },
      { en: "Follow-up till delivery", hi: "डिलीवरी तक फ़ॉलो-अप" },
      { en: "Demo at your place", hi: "आपकी जगह पर डेमो" },
      { en: "Company-backed, with bill", hi: "कंपनी का भरोसा, बिल के साथ" },
      { en: "Help after the sale too", hi: "बिक्री के बाद भी मदद" },
    ],
    steps: [
      { en: "Tell me your need", hi: "ज़रूरत बताएँ", desc: "Message on WhatsApp — product, quantity and where you are.", descHi: "WhatsApp पर मैसेज करें — प्रोडक्ट, मात्रा और आप कहाँ हैं।" },
      { en: "Quotation or demo", hi: "कोटेशन या डेमो", desc: "You get a written quote; a demo if you want to see it.", descHi: "लिखित कोटेशन मिलता है; देखना चाहें तो डेमो।" },
      { en: "Confirm the order", hi: "ऑर्डर कन्फ़र्म करें", desc: "Order placed with the company; you get the bill and delivery date.", descHi: "कंपनी में ऑर्डर लगता है; बिल और डिलीवरी की तारीख़ आपको मिलती है।" },
      { en: "Delivery and support", hi: "डिलीवरी और सहयोग", desc: "Delivered and installed where needed; I stay your contact after that.", descHi: "डिलीवरी और ज़रूरत हो तो इंस्टॉलेशन; उसके बाद भी मैं ही आपका संपर्क।" },
    ],
    faq: [
      { q: "Can you send a quotation on WhatsApp?", qHi: "WhatsApp पर कोटेशन मिल जाएगा?", a: "Yes, send the product and quantity, and a written quotation comes on WhatsApp.", aHi: "हाँ, प्रोडक्ट और मात्रा भेजें, लिखित कोटेशन WhatsApp पर आ जाएगा।" },
      { q: "Can I see a demo before buying?", qHi: "ख़रीदने से पहले डेमो देख सकते हैं?", a: "Yes, at your office, shop or home; message a convenient time.", aHi: "हाँ, आपके ऑफ़िस, दुकान या घर पर; सुविधा का समय बता दें।" },
      { q: "Is there a better rate for bulk?", qHi: "थोक में बेहतर रेट मिलेगा?", a: "Usually yes; tell me the quantity and I check the current scheme with the company.", aHi: "आमतौर पर हाँ; मात्रा बताएँ, कंपनी की मौजूदा scheme देख लेते हैं।" },
      { q: "Who do I contact after the sale?", qHi: "बिक्री के बाद किससे संपर्क करें?", a: "Me — for service, warranty or any complaint, message on WhatsApp and it goes to the company through me.", aHi: "मुझसे — सर्विस, वारंटी या शिकायत के लिए WhatsApp करें, कंपनी से बात मेरे ज़रिए होती है।" },
      { q: "How do I become a dealer?", qHi: "डीलर कैसे बनें?", a: "Message your shop details and area; I explain the company's terms and the starting stock.", aHi: "दुकान की जानकारी और इलाक़ा भेजें; कंपनी की शर्तें और शुरुआती स्टॉक समझा देते हैं।" },
      { q: "Will I get a proper bill?", qHi: "पक्का बिल मिलेगा?", a: "Yes, a GST invoice from the company with every order.", aHi: "हाँ, हर ऑर्डर पर कंपनी का GST इनवॉइस।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Payment goes to the company's account by bank transfer or UPI, against the invoice.", aHi: "भुगतान इनवॉइस के बदले कंपनी के खाते में, बैंक ट्रांसफ़र या UPI से।" },
    ],
    generic: ["connect with us", "explore options", "best deals", "quality products", "customer satisfaction"],
  },

  agent: {
    explain: [
      "whose agent you are — the company, principal or market you represent, and what you deal in",
      "what you do for the customer: find the right option, negotiate, paperwork and follow-up till the deal closes",
      "that the commission is told upfront and you work fairly with both sides",
      "the area you work in and how to reach you",
    ],
    services: [
      { en: "Buyer–seller matching", hi: "ख़रीदार-विक्रेता मिलाना", desc: "Bring genuine buyers and sellers together for the right deal.", descHi: "सही सौदे के लिए असली ख़रीदार और विक्रेता को मिलाना।" },
      { en: "Bookings on the company's behalf", hi: "कंपनी की ओर से बुकिंग", desc: "Place bookings and orders with the principal company for you.", descHi: "आपके लिए मुख्य कंपनी में बुकिंग और ऑर्डर लगाना।" },
      { en: "Rate negotiation", hi: "भाव तय करवाना", desc: "Fair rates negotiated with the market knowledge of the day.", descHi: "बाज़ार की दिन की जानकारी के साथ वाजिब भाव तय करवाना।" },
      { en: "Paperwork & documentation", hi: "काग़ज़ी काम", desc: "Forms, agreements, bills and receipts done correctly and on time.", descHi: "फ़ॉर्म, agreement, बिल और रसीद — सही और समय पर।" },
      { en: "Follow-up till closure", hi: "सौदा पूरा होने तक फ़ॉलो-अप", desc: "Updates at every stage, from enquiry to delivery or payment.", descHi: "पूछताछ से डिलीवरी या भुगतान तक, हर कदम की ख़बर।" },
      { en: "Payment coordination", hi: "भुगतान का समन्वय", desc: "Payments routed and receipts shared so both sides are clear.", descHi: "भुगतान और रसीद दोनों पक्षों तक, ताकि हिसाब साफ़ रहे।" },
      { en: "After-deal support", hi: "सौदे के बाद सहयोग", desc: "Claims, complaints or service requests taken up with the company.", descHi: "क्लेम, शिकायत या सर्विस की बात कंपनी से करवाना।" },
    ],
    whyUs: [
      { en: "Commission told upfront", hi: "कमीशन पहले ही बताते हैं" },
      { en: "Genuine parties only", hi: "सिर्फ़ असली पार्टियाँ" },
      { en: "Paperwork done right", hi: "काग़ज़ सही बनते हैं" },
      { en: "Updates at every step", hi: "हर कदम की ख़बर" },
      { en: "Known in the market", hi: "बाज़ार में जान-पहचान" },
      { en: "Fair with both sides", hi: "दोनों पक्षों के साथ ईमानदारी" },
      { en: "Reach on WhatsApp", hi: "WhatsApp पर संपर्क" },
    ],
    steps: [
      { en: "Tell your requirement", hi: "ज़रूरत बताएँ", desc: "What you want to buy, sell or book, and by when.", descHi: "क्या ख़रीदना, बेचना या बुक करना है, और कब तक।" },
      { en: "Options and rates", hi: "विकल्प और भाव", desc: "Suitable options and the going rate, with the commission explained.", descHi: "उपयुक्त विकल्प और चालू भाव, कमीशन साफ़-साफ़ बताकर।" },
      { en: "Deal and paperwork", hi: "सौदा और काग़ज़", desc: "Terms finalised and the documents made properly.", descHi: "शर्तें तय, काग़ज़ सही तरह से तैयार।" },
      { en: "Closed and settled", hi: "सौदा पूरा, हिसाब साफ़", desc: "Delivery or payment done and receipts shared with both sides.", descHi: "डिलीवरी या भुगतान पूरा, रसीद दोनों पक्षों को।" },
    ],
    faq: [
      { q: "How much is your commission?", qHi: "कमीशन कितना है?", a: "It depends on the kind of deal; it is told clearly before any work starts. Message us for your case.", aHi: "सौदे के प्रकार पर निर्भर है; काम शुरू होने से पहले साफ़ बता दिया जाता है। अपने केस के लिए मैसेज करें।" },
      { q: "Who pays the commission — buyer or seller?", qHi: "कमीशन कौन देता है — ख़रीदार या विक्रेता?", a: "It depends on the market practice for that deal; we tell you upfront so there is no confusion.", aHi: "उस सौदे के बाज़ार के चलन पर निर्भर है; पहले ही बता देते हैं ताकि कोई भ्रम न रहे।" },
      { q: "Are you authorised by the company?", qHi: "कंपनी से अधिकृत हैं?", a: "Ask us and we show the authorisation or registration we hold; bookings go into the company's own records.", aHi: "पूछ लें, हम अपना authorisation या रजिस्ट्रेशन दिखाते हैं; बुकिंग कंपनी के रिकॉर्ड में जाती है।" },
      { q: "Do you handle the paperwork?", qHi: "काग़ज़ी काम आप करते हैं?", a: "Yes, forms, agreements and receipts are prepared and explained to you before signing.", aHi: "हाँ, फ़ॉर्म, agreement और रसीद तैयार करके, साइन से पहले समझाते हैं।" },
      { q: "Can I deal from another city?", qHi: "दूसरे शहर से सौदा हो सकता है?", a: "Often yes; updates, documents and payments can be handled on WhatsApp and bank transfer. Ask us.", aHi: "अक्सर हाँ; अपडेट, काग़ज़ और भुगतान WhatsApp और बैंक ट्रांसफ़र से हो जाते हैं। पूछ लें।" },
      { q: "What if the deal does not go through?", qHi: "सौदा न हुआ तो?", a: "Commission is only on a completed deal; any advance follows the terms agreed in writing.", aHi: "कमीशन सिर्फ़ पूरे हुए सौदे पर; कोई एडवांस हो तो लिखित शर्तों के अनुसार।" },
      { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "Payments for the deal go to the seller or company directly; commission by UPI or bank transfer against a receipt.", aHi: "सौदे का भुगतान सीधे विक्रेता या कंपनी को; कमीशन UPI या बैंक ट्रांसफ़र से, रसीद के साथ।" },
    ],
    generic: ["connect with us", "explore options", "best deals", "trusted service", "customer satisfaction"],
  },
};

export const SALES_DEFAULT: TradeData = {
  explain: [
    "what you sell or represent — the products, brands or services and who they are for",
    "how a customer buys: enquiry on WhatsApp, quotation or demo, order, delivery",
    "support after the sale: bill, warranty, replacements, reorders",
    "your area and how to reach you",
  ],
  services: [
    { en: "Product information", hi: "प्रोडक्ट की जानकारी", desc: "Which product suits your need, explained simply.", descHi: "आपकी ज़रूरत के लिए कौन सा प्रोडक्ट सही है, आसान भाषा में।" },
    { en: "Quotation on WhatsApp", hi: "WhatsApp पर कोटेशन", desc: "Send your requirement and get a written quote.", descHi: "ज़रूरत भेजें, लिखित कोटेशन पाएँ।" },
    { en: "Demo & samples", hi: "डेमो और सैंपल", desc: "See the product work before you decide.", descHi: "फ़ैसले से पहले प्रोडक्ट चलाकर देखें।" },
    { en: "Orders & delivery", hi: "ऑर्डर और डिलीवरी", desc: "Order confirmed on WhatsApp and delivered to your door.", descHi: "WhatsApp पर ऑर्डर कन्फ़र्म, घर या दुकान तक डिलीवरी।" },
    { en: "Bulk & business orders", hi: "थोक और बिज़नेस ऑर्डर", desc: "Supply for shops, offices and institutions in any quantity.", descHi: "दुकानों, ऑफ़िस और संस्थानों के लिए जितनी मात्रा चाहिए।" },
    { en: "After-sales support", hi: "बिक्री के बाद सहयोग", desc: "Bill, warranty, replacement and service help after you buy.", descHi: "ख़रीद के बाद बिल, वारंटी, बदली और सर्विस में मदद।" },
    { en: "Dealership & partnership enquiries", hi: "डीलरशिप और साझेदारी", desc: "Information for shops or people who want to work with us.", descHi: "हमारे साथ काम करना चाहने वाली दुकानों और लोगों के लिए जानकारी।" },
  ],
  whyUs: [
    { en: "Genuine products with bill", hi: "असली प्रोडक्ट, बिल के साथ" },
    { en: "Quick reply on WhatsApp", hi: "WhatsApp पर जल्दी जवाब" },
    { en: "Honest advice, no pressure", hi: "सही सलाह, कोई दबाव नहीं" },
    { en: "Delivery to your door", hi: "घर तक डिलीवरी" },
    { en: "Support after the sale", hi: "बिक्री के बाद भी साथ" },
    { en: "Fair, clear pricing", hi: "साफ़ और वाजिब दाम" },
  ],
  steps: [
    { en: "Message your need", hi: "ज़रूरत भेजें", desc: "Product, quantity and your location on WhatsApp.", descHi: "प्रोडक्ट, मात्रा और लोकेशन WhatsApp पर।" },
    { en: "Quote or demo", hi: "कोटेशन या डेमो", desc: "A written quote; a demo or sample if you want.", descHi: "लिखित कोटेशन; चाहें तो डेमो या सैंपल।" },
    { en: "Order and delivery", hi: "ऑर्डर और डिलीवरी", desc: "Confirm the order; it is delivered with the bill.", descHi: "ऑर्डर कन्फ़र्म करें; बिल के साथ डिलीवरी।" },
    { en: "We stay in touch", hi: "हम जुड़े रहते हैं", desc: "Reorders, service and any question, on the same number.", descHi: "रीऑर्डर, सर्विस और कोई भी सवाल, उसी नंबर पर।" },
  ],
  faq: [
    { q: "Are the products genuine?", qHi: "प्रोडक्ट असली हैं?", a: "Yes, with the company's bill and packing; warranty where the company gives it.", aHi: "हाँ, कंपनी के बिल और पैकिंग के साथ; जहाँ कंपनी देती है वहाँ वारंटी।" },
    { q: "Can I get a quotation first?", qHi: "पहले कोटेशन मिल सकता है?", a: "Yes, message the product and quantity and we send a written quotation on WhatsApp.", aHi: "हाँ, प्रोडक्ट और मात्रा भेजें, WhatsApp पर लिखित कोटेशन भेजते हैं।" },
    { q: "Do you deliver?", qHi: "डिलीवरी करते हैं?", a: "Yes, in our area; for other places, ask us and we tell you the options.", aHi: "हाँ, हमारे इलाक़े में; बाक़ी जगहों के लिए पूछ लें, विकल्प बताते हैं।" },
    { q: "Is there a better rate for bulk?", qHi: "थोक में बेहतर रेट मिलेगा?", a: "Usually yes; send the quantity and we share the current rate and scheme.", aHi: "आमतौर पर हाँ; मात्रा भेजें, मौजूदा रेट और scheme बताते हैं।" },
    { q: "Who do I contact after buying?", qHi: "ख़रीदने के बाद किससे संपर्क करें?", a: "The same number — for warranty, service, replacement or a reorder, message on WhatsApp.", aHi: "उसी नंबर पर — वारंटी, सर्विस, बदली या रीऑर्डर के लिए WhatsApp करें।" },
    { q: "Can I join or become a dealer?", qHi: "जुड़ सकते हैं या डीलर बन सकते हैं?", a: "Message us; we explain the terms honestly and what the work involves, with no promises.", aHi: "मैसेज करें; शर्तें और काम में क्या करना है, सब साफ़-साफ़ बताते हैं, कोई वादा नहीं।" },
    { q: "How do I pay?", qHi: "भुगतान कैसे करें?", a: "UPI, bank transfer or cash on delivery, against a bill.", aHi: "UPI, बैंक ट्रांसफ़र या डिलीवरी पर नक़द, बिल के साथ।" },
  ],
  generic: ["connect with us", "explore options", "quality products", "best deals", "customer satisfaction", "wide range"],
};
